### ISSUE TITLE
Craft Release - Updates

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon-design-kit#10]
- Ask to turn common elements into symbols with constrains for correct resizing:
  - text fields and text areas (and its specific instances like search bar etc)
  - Dropdown (two sizes)
  - check and radio boxes
  - buttons
  - tabs

**Comment by bsonefeld** [comment]
- [ ] Data tables with checkbox and nested rows are missing in Craft Library

**Comment by bsonefeld** [comment]
Tracking interally.
