### ISSUE TITLE
Type style for heading-05 in design kit is different from carbon website

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-design-kit#105]
## Detailed description

In the V10 beta Carbon sketch file, the productive heading-05 text symbol is 32px.

The Carbon website says the productive heading-05 should be 36px.

## Additional information

Carbon sketch file:
![Carbon Kit](https://user-images.githubusercontent.com/20582179/54688247-45c7c200-4aeb-11e9-91e7-d55a06a62733.png)

Website:
![CarbonSite](https://user-images.githubusercontent.com/20582179/54688275-55470b00-4aeb-11e9-83a8-2b0d874ba941.png)

## Add labels

for some reason labels aren't showing up for me in this repo

**Comment by laurenmrice** [comment]
this is correct on the website now, just needs to be updated in the kits.

**Comment by laurenmrice** [comment]
Hey tracey! fixed in all kits 🎉. It is 32px on the website and in the kits for token product-heading-05.
