### ISSUE TITLE
Accordian issue in Sketch: open/closed icons do not change

### ISSUE THREAD

**Issue by kathryn-gallagher** [carbon-design-system/carbon-design-kit#106]
> **Version:** Carbon Design System – linked, most updated (don't know the version)

> **Component:** Accordion, applies to all instances 

> **Issue:** The chevron icon does not change when the component is open and closed. 

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
**No**

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
**DBA AppBuilder, working towards Playback 0**

## Additional information

<img width="805" alt="Screen Shot 2019-05-02 at 10 29 21 AM" src="https://user-images.githubusercontent.com/50209317/57087231-37adb980-6cc5-11e9-8aa1-d376048f636a.png">

## Add labels
`project: libraries` `project: components`

**Comment by kathryn-gallagher** [comment]
Labels aren't showing up for me.

**Comment by aagonzales** [comment]
@kathryn-gallagher ok I fixed this, should be updated with the next update you get.
