### ISSUE TITLE
Accordian issue in Sketch – text field is not long enough in Title

### ISSUE THREAD

**Issue by kathryn-gallagher** [carbon-design-system/carbon-design-kit#107]
## Detailed description
In Sketch, the symbol does not allow for longer Titles. The symbol needs to be updated for the text field to scale.

> What version of the Carbon Design System Kit are you using?
Carbon Design System, linked, current (don't know version)

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Accordion component symbol in Sketch

> What did you expect to happen? What happened instead? What would you like to see changed?
The text field is too short– it doesn't scale for text longer than "Title." Please fix the Sketch symbol to allow for a longer text string.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
DBA AppBuilder, no

## Additional information

<img width="511" alt="Screen Shot 2019-05-02 at 10 10 20 AM" src="https://user-images.githubusercontent.com/50209317/57087760-61b3ab80-6cc6-11e9-80b0-e11a965fcb68.png">

<img width="787" alt="Screen Shot 2019-05-02 at 10 40 37 AM" src="https://user-images.githubusercontent.com/50209317/57087923-c4a54280-6cc6-11e9-9993-5749f9638a4e.png">

## Add labels
This is not showing up for me.

**Comment by aagonzales** [comment]
Fixed! Should be in the latest update.
