### ISSUE TITLE
Lock height of components

### ISSUE THREAD

**Issue by bsonefeld** [carbon-design-system/carbon-design-kit#11]
Moved from `carbon-components`

<hr>

antonmc commented on Jun 6
Maybe it is because I'm new to sketch, but I found that the components stretched whenever I changed the height of the artboard they were on.

I learned that there is a checkbox to keep height fixed, and learned to click that when resizing the artboard. I wonder if that should be defaulted for the Carbon components.

<hr> 

bsonefeld commented on Jun 7
Interesting find, @antonmc ! Could you post a screenshot or a GIF example of what's happening when you resize your artboard? Almost sounds like a Sketch bug to me, but in order to troubleshoot I want to make sure I understand the problem correctly :)

**Comment by aagonzales** [comment]
We are looking into this, especially with Sketch Libraries. Components don't always respond the way the way we expect them too with this feature. We are still learning but will hopefully have as much of this implemented when possible going forward.
