### ISSUE TITLE
Disable button in Modals

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon-design-kit#115]
## Title line template: [Title]: Brief description

Would be great if there was a disable button option in the modals. Thanks.

> What version of the Carbon Design System Kit are you using?
10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

SAMPLE:
![characteristics copy](https://user-images.githubusercontent.com/12818623/58120202-b87c1900-7bd2-11e9-95b5-0865d1114bb1.png)

**Comment by laurenmrice** [comment]
@heatherco In the sketch kit, if you select the modal you are able to switch out the button for a different state (disabled is included). 🙂

**Comment by heatherco** [comment]
yes there is lol. Thanks!
