### ISSUE TITLE
Add singular action button for existing modal component.

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon-design-kit#116]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

Add singular action button for existing modal component.

> What version of the Carbon Design System Kit are you using?
10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
![image](https://user-images.githubusercontent.com/12818623/58187234-6398db00-7c84-11e9-817b-112156d851a9.png)

**Comment by heatherco** [comment]
Hi Lauren, just an FYI, as a temporary solution to this, I used the model component with a left and right button. I set the right button without  any text and give it the same link.
Maybe you can provide this as a temporary options for those who only need one button until a component can be created.
![image (16)](https://user-images.githubusercontent.com/12818623/59545030-a1d19500-8ee6-11e9-847d-bb7ce686faf1.png)

**Comment by aagonzales** [comment]
Added! It will be available in the next kit update. 

It is not its own modal variation but we've added a footer modifier in the transitional modal that allows you to switch between single and double actions in the symbol overrides pattern.

![image](https://user-images.githubusercontent.com/11670886/60838679-e4f2f100-a190-11e9-8cef-0a5c97fc0b17.png)
