### ISSUE TITLE
Make text fields for modal flexible in width

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon-design-kit#118]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

Make text fields for modal flexible in width. Thank you.

> What version of the Carbon Design System Kit are you using?
10

![Screen Shot 2019-06-03 at 12 35 11 PM](https://user-images.githubusercontent.com/12818623/58818491-0b56c700-85fc-11e9-9a02-d7e0c28dbee2.png)

![Screen Shot 2019-06-03 at 12 33 21 PM](https://user-images.githubusercontent.com/12818623/58818501-11e53e80-85fc-11e9-94d4-fe6c3895b816.png)

![Screen Shot 2019-06-03 at 12 33 34 PM](https://user-images.githubusercontent.com/12818623/58818520-1ad61000-85fc-11e9-9978-291fffb2ca80.png)

**Comment by heatherco** [comment]
@llaurenmrice  please have look when you get a chance, thanks.

**Comment by aagonzales** [comment]
Field in modals intentionally only are 75% of the width of the modal. The symbol is not incorrect. 
https://www.carbondesignsystem.com/components/modal/style#structure

![image](https://user-images.githubusercontent.com/11670886/60828462-0dbabc80-a178-11e9-95dc-d8e748f35520.png)
