### ISSUE TITLE
Update IBM Colors

### ISSUE THREAD

**Issue by seejamescode** [carbon-design-system/carbon-design-kit#12]
<img width="781" alt="screen shot 2017-08-28 at 10 30 24 am" src="https://user-images.githubusercontent.com/7519029/29780604-f9d002f6-8bdb-11e7-9064-232bb42161f6.png">

Design kit currently displays IBM Colors 1.0. Supporting files and new palette can be found here: https://www.ibm.com/design/language/resources/color-library

**Comment by aagonzales** [comment]
@seejamescode We currently still use the v1 palette in production. When we switch in prod we will update the palette in the kit.

**Comment by aagonzales** [comment]
Carbon default theme will update the v2 color palette when Bluemix is ready.
