### ISSUE TITLE
text in tags need middle alignment.

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon-design-kit#122]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.
Text in tags need to be middle-aligned. Thanks

![Screen Shot 2019-06-11 at 5 02 25 PM](https://user-images.githubusercontent.com/12818623/59306703-ddf8c180-8c6a-11e9-8ae7-4bc48d9de4b3.png)

> What version of the Carbon Design System Kit are you using?
10

**Comment by heatherco** [comment]
@laurenmrice  can you please have a look at this when you get a chance.

**Comment by aagonzales** [comment]
@heatherco text in tag isn't supposed to be middle aligned. Its supposed to always have 8px of padding on either side of the text. After you change the text in the override panel you'll have to adjust the tag size to be the appropriate size. You can turn on the spacer to help you adjust.

![Jul-03-2019 11-49-51](https://user-images.githubusercontent.com/11670886/60610129-c489f780-9d88-11e9-8bf4-90263b66b762.gif)

**Comment by heatherco** [comment]
@aagonzales, thanks, but this is what I meant by not middle-aligned. The text looks slightly off-set. The text is just a little high. FYI: I wasn't like this before, probably accidentally happened during another change.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/12818623/60827608-950b2e80-a17e-11e9-9925-7a914d05b68a.png">

**Comment by laurenmrice** [comment]
We purposely have set the text within a tag one pixel up to keep the text visually center within the tag. If the text is centered with equal padding, the text looks bottom heavy within the container, especially when paired with the close icon for the filterable tag.

![tag](https://user-images.githubusercontent.com/43969356/61079214-fda91400-a3e7-11e9-8d39-f017f7807534.png)
