### ISSUE TITLE
Add selected state for default columns in data tables

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-design-kit#124]
For the different data column grouped columns, there's no option to have a default row have a selected state to match the selectable enabled state. 

<img width="966" alt="Screen Shot 2019-06-14 at 2 17 22 PM" src="https://user-images.githubusercontent.com/43549567/59529478-230d3580-8eaf-11e9-9093-5d6307018877.png">

Applications grouped column: correct selected state background color
Role + Status grouped column: incorrect background color—I can only get to a hover state

**Comment by dianatran18** [comment]
Side comment: It seems a little confusing when the selected row color is the same as the column header color. Thoughts? 

<img width="544" alt="Screen Shot 2019-06-14 at 2 56 11 PM" src="https://user-images.githubusercontent.com/43549567/59531730-af6e2700-8eb4-11e9-9189-20cf16c0cd28.png">

**Comment by aagonzales** [comment]
@dianatran18  Its under the "selectable" category not the default. You have to switch categories.
![image](https://user-images.githubusercontent.com/11670886/60841780-3f438000-a198-11e9-9c92-837d7c665136.png)

**Comment by aagonzales** [comment]
@dianatran18  Its under the "selectable" category not the default. You have to switch categories.
![image](https://user-images.githubusercontent.com/11670886/60841780-3f438000-a198-11e9-9c92-837d7c665136.png)

**Comment by aagonzales** [comment]
Missing states in selectable category for:
- selected + hover

**Comment by dianatran18** [comment]
Ah yes sorry I saw your slack thread with Marcel before and I forgot I opened this.

Thank you!

**Comment by marceltrautmann** [comment]
.

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.
(add to 10.5 release notes)
