### ISSUE TITLE
dropdown symbol missing overrides...

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#125]
Working with the individual pieces of the dropdown symbol in sketch (white theme).  Notice that the overrides seem to be missing from the "first" element (as compared to the middle/last).  Specifically field colour in this instance.  See screenie for details

![image](https://user-images.githubusercontent.com/51379566/59634079-eeea7c80-911b-11e9-8dd4-f8bcfadf4b01.png)

Side note: shouldn't it follow the 8pixel grid? note the slight overhang.

**Comment by marceltrautmann** [comment]
open

**Comment by marceltrautmann** [comment]
This guidance _might_ apply here as well...

![image](https://user-images.githubusercontent.com/51379566/60836959-02c25500-a195-11e9-9511-69f25805c310.png)
https://ibm-studios.slack.com/archives/C0M053VPT/p1561469191349600

**Comment by aagonzales** [comment]
We can't technically do it like that though. In code we'd have to add javascript to all our basic components to get them to hit mini-unit increments and our devs think that is a bad practice (to add unnecessary javascript). Therefore with these Sketch components we're following the dev functionality. Mike knows this is the reason why things don't fall on the mini unit.

**Comment by aagonzales** [comment]
Missing overrides issue is fixed, it will be available in the next update.
