### ISSUE TITLE
[Dropdown, G90 G100 kits] dropshadow layer background fill wrong color

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#127]
**G90 and G100 kit** [Dropdown - default - labeled - open] 

Drop shadow layer background fill is currently G10. Should be G90 and G80. 

![image](https://user-images.githubusercontent.com/15144993/59715336-3daa1c00-91d9-11e9-9a67-9d87a5affc87.png)

![image](https://user-images.githubusercontent.com/15144993/59715416-692d0680-91d9-11e9-8ba3-a3a28c13f0d9.png)

**Comment by aagonzales** [comment]
Fixed, available in next update.
