### ISSUE TITLE
[Data table] Icon symbols for rows do not have icon pinned

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-design-kit#129]
The icon rows, when re-sized, they do not have the icons "pinned" to the right hand size. This makes it difficult to create a design purely from the symbols
<img width="414" alt="Screen Shot 2019-06-25 at 11 50 57 AM" src="https://user-images.githubusercontent.com/21066152/60113363-9b8db500-973f-11e9-880f-b824710aa97c.png">
 that has a row with text and icons on it

**Comment by aagonzales** [comment]
Fixed! Will be in the next kit update.
