### ISSUE TITLE
Craft vs. Sketch Libraries

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon-design-kit#13]
Issue to look at the pros and cons of craft and Sketch libraries

**Comment by tay-aitken** [comment]
Found a great [article](https://medium.com/ux-power-tools/sketch-libraries-how-they-work-and-the-crazy-stuff-you-can-do-with-them-fc10f142ac80) about Sketch 47 Libraries (in Beta)

**Comment by tay-aitken** [comment]
## Craft
**Pros**
- A handful of people are already using it
- Content is nicely organized and easy to find/search for


**Cons**
**- Buggy**
- Always gets throw out of sync when Sketch updates
- Has issues syncing with Box 
- Personally feel like I have to contact Invision once every two months for a major Craft problem

## Sketch Libraries
**Pros**
- Baked into sketch, not having to rely on third party application

**Cons**
- Still in Beta
- Still very new could be some bugs
- Cannot sync text and layer styles (however will be coming in future)

**Comment by aagonzales** [comment]
"open original document" could be tricky

> Will I lose local overrides if I sync symbol changes from the library?
As long as the master symbol retains the same attributes and layer set, then all of your overrides should be preserved. 

- Yes! that's the problem we were having with Craft right?

> Does it work with text styles and layer styles?
Not yet, but it’s in Sketch’s roadmap.

- whomp ... but it will be nice when they have it.

**Comment by willowbrae** [comment]
Can I ask what is the source of: 
> Does it work with text styles and layer styles? Not yet, but it’s in Sketch’s roadmap.

I wrote sometime ago on Slack that "we will have to wait for text and fills to be synced" which was my assumption, I hope it didn't mislead you. I tried to ask Sketch about their roadmap on Twitter, but they didn't reply.

**Comment by aagonzales** [comment]
@willowbrae That reference is from the FAQ section in [this article](https://medium.com/ux-power-tools/sketch-libraries-how-they-work-and-the-crazy-stuff-you-can-do-with-them-fc10f142ac80)

**Comment by tay-aitken** [comment]
Officially using Sketch 47 libraries, working on the library creation now.
