### ISSUE TITLE
Data table header mismatch

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#131]
https://www.carbondesignsystem.com/components/data-table/code

Note that the column headers are all 47px except for the status column (far right) which is correct at 48px per the design spec.

![image](https://user-images.githubusercontent.com/51379566/60129053-267fa700-9762-11e9-9e79-bc5f399a66e6.png)

**Comment by aagonzales** [comment]
Issue moved to [carbon-design-system/carbon-website #1782](https://github.com/carbon-design-system/carbon-website/issues/1782) via [**ZenHub**](https://www.zenhub.com/)
