### ISSUE TITLE
Data table column header missing "selectable and expandable" symbol

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#132]
Data table column header missing "selectable and expandable" symbol.  Additionally why is there no column header with sorting built in?

![image](https://user-images.githubusercontent.com/51379566/60182745-e0265880-97f2-11e9-9d42-41e1c1c19cc3.png)

**Comment by aagonzales** [comment]
Add both, they will be available in the next kit update!

**Comment by marceltrautmann** [comment]
Thanks @aagonzales!

Follow up Q.  If a table column header is selectable and/or expandable can it not also be sortable?

![image](https://user-images.githubusercontent.com/51379566/61713006-91061180-ad25-11e9-9c93-75f3284a8c5f.png)

**Comment by aagonzales** [comment]
Yes, all those can be sortable but that's so many more symbols to make 😭([3 new variations * 4 column header sizes] * 4 kits). Let me think on it if there's a smarter way to add sort to these otherwise yes there should be symbols for those as well.

**Comment by aagonzales** [comment]
Notes to myself:

- expandable /
   - 01 enabled
   - 02 hover
   - 03 sort up
   - 04 sort down

**Comment by marceltrautmann** [comment]
sorry 😔

**Comment by marceltrautmann** [comment]
maybe just add a sort 'button' that we can lay in when we need it? (on it's own)

**Comment by aagonzales** [comment]
That would work, but sort also has a background color change.

**Comment by marceltrautmann** [comment]
Can the symbol have a frame for spacing, but be bg transparent?  Unless the icon itself changes I see no reason for bg states.

**Comment by aagonzales** [comment]
## Potential solution

4 header background symbols
– default
– sort-none
– sort-up
– sort-down

Remove “sortable” as its own category, change background in the overrides panel instead
Update 4 size & category cells to include background symbol

Symbol = background + sort icon
![image](https://user-images.githubusercontent.com/11670886/62979704-2018bd80-bdea-11e9-9ec4-6129a20f2e29.png)

**Comment by marceltrautmann** [comment]
keepAlive[bot]

**Comment by marceltrautmann** [comment]
keepAlive[bot]

**Comment by marceltrautmann** [comment]
fun

**Comment by marceltrautmann** [comment]
I'm unsure if this was ever solved, so keeping it alive.

**Comment by aagonzales** [comment]
The initial request was completed but there we still need to figure out the sortable with other column header types. Its just low priority to fix at the moment because it's easy just to manually add the sort icon when needed to a design.

**Comment by marceltrautmann** [comment]
should we close it?

**Comment by aagonzales** [comment]
No, we can keep it open, we should still do it at some point. (and I think we're finally removing stale bot soon)

**Comment by marceltrautmann** [comment]
keep alive

**Comment by marceltrautmann** [comment]
.

**Comment by marceltrautmann** [comment]
keep alive, 1 year in, still needed @aagonzales ?

**Comment by marceltrautmann** [comment]
keep alive

**Comment by marceltrautmann** [comment]
keep alive

**Comment by marceltrautmann** [comment]
keep alive

**Comment by marceltrautmann** [comment]
.

**Comment by marceltrautmann** [comment]
.
