### ISSUE TITLE
Selectable Data Table – single-select option not available in Sketch library

### ISSUE THREAD

**Issue by kathryn-gallagher** [carbon-design-system/carbon-design-kit#133]
**Selectable Data Table – single-select option not available in Sketch library**
The checkbox icon on the Selectable Data Table row component is not a symbol in Sketch, so I cannot switch to a single-select radio button icon.

![Screen Shot 2019-06-25 at 10 50 30 AM](https://user-images.githubusercontent.com/50209317/60113298-130b1680-9737-11e9-8045-b546408622ce.png)

**Comment by aagonzales** [comment]
I've adjusted the overrides to allow you to be able to change the icon in the overrides panel to achieve "single selection" option.

![image](https://user-images.githubusercontent.com/11670886/61671705-6462e300-acae-11e9-8bad-9bf83b098699.png)

**Comment by aagonzales** [comment]
(add to 10.5 release notes)
