### ISSUE TITLE
Missing symbols "selected" for datatable cells

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#134]
When working with sketch symbols for data table "selectable" cells there is an option for "selected"

However all the other cell types are missing the "selected" state, thus making it impossible to complete an entire row...

![image](https://user-images.githubusercontent.com/51379566/60269142-e3d1e200-98bb-11e9-83d2-72e1b5628604.png)

PLEASE MAKE THIS HIGH PRIORITY so I can finish my prototype without un-linking all my cells

**Comment by marceltrautmann** [comment]
The plot thickens.  In the interest of time I've detached my symbols to modify myself and discovered that the the icon cell utilized button icons.  How are these to behave on a selected background cell?

![image](https://user-images.githubusercontent.com/51379566/60270042-948cb100-98bd-11e9-84b4-1325eeecebe5.png)

**Comment by aagonzales** [comment]
"05-selected - enabled" has the checkmark "08 selected - row item" are for the other row items.
![image](https://user-images.githubusercontent.com/11670886/60282555-e0932200-98cc-11e9-992a-fb24e67430c0.png)

First comment is not a bug, second comment need to add a "selected" state to icon button.

**Comment by marceltrautmann** [comment]
First comment is a problem of mis-categorisation.
Just like ‘enabled, hover, focus & disabled’ - selected is a state, and as such should be grouped as one.  Selected is not infact a category, “selectable” on the other hand is

![image](https://user-images.githubusercontent.com/51379566/60284500-b562ff80-98d9-11e9-880e-84c831840109.png)

**Comment by aagonzales** [comment]
Duplicated issue: https://github.com/carbon-design-system/carbon-design-kit/issues/124

**Comment by aagonzales** [comment]
Updated:
- [ ] White
- [ ] G10
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.
(add to 10.5 release notes)
