### ISSUE TITLE
Lg Search Placeholder Text Color Incorrect

### ISSUE THREAD

**Issue by creckling** [carbon-design-system/carbon-design-kit#136]
## Detailed description

Using the Carbon 10 Sketch Library, Gray 10 Theme
Add Search/large/01 enabled to an artboard
The color of the placeholder text should be $text-03 (gray 50) but is set to $text-02

> What version of the Carbon Design System Kit are you using?
10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

search/large/01 enabled

> What did you expect to happen? What happened instead? What would you like to see changed?

placeholder text should be $text-03 according to the style documented in carbon (and also what search/small/01 enabled has as the text style)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson IoT

* Screenshots or Sketch file links
![image](https://user-images.githubusercontent.com/50208035/60292059-4e9a1200-98ea-11e9-924c-05ed7a3d57f9.png)

## Add labels 
(no way to do this in the UI)
libraries
bug

**Comment by aagonzales** [comment]
Fixed! Had to add new type style layer to address issue: `body-short-o2/text-03`.
Available in next update.
