### ISSUE TITLE
[Color token]: add missing tokens

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#138]
Missing tokens to be added:
- `hover-selected-ui`
- `skeleton-01`
- `skeleton-02`
- `inverse-support-01`
- `inverse-support-02`
- `inverse-support-03`
- `inverse-support-04`
- `inverse-hover-ui`

![image](https://user-images.githubusercontent.com/11670886/60844271-6e5cf000-a19e-11e9-8088-b2025a60f56f.png)
![image](https://user-images.githubusercontent.com/11670886/60844138-0dcdb300-a19e-11e9-9b9f-5738c1591abd.png)
![image](https://user-images.githubusercontent.com/11670886/60916205-6dd26100-a253-11e9-9d1e-56828939a5aa.png)
![image](https://user-images.githubusercontent.com/11670886/60916411-e0434100-a253-11e9-9241-0a3887f39a98.png)

![Screen Shot 2019-08-01 at 11.30.34 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/115e5ab0-8240-4bcb-b471-bc1379483d05)

**Themes done:**
- [x] White
- [x] G10
- [x] G90
- [x] G100

**Comment by aagonzales** [comment]
Update symbols to use these new tokens:
- skeleton state symbols
- notifications

**Comment by laurenmrice** [comment]
I added inverse-hover-ui token to this as well

**Comment by aagonzales** [comment]
Fixed! Available in next kit update. 

Add to V10.5 release notes
