### ISSUE TITLE
Gray 10 multi-line code snippet no background color override

### ISSUE THREAD

**Issue by sgraden** [carbon-design-system/carbon-design-kit#139]
## Detailed description

Using Gray 10 theme and an expandable table. Went to put a code snippet into the expansion of the table and it just ended up white on white with no ability to override the background color
![image](https://user-images.githubusercontent.com/6685872/60897732-330a0200-a22e-11e9-8679-48393f8e09fc.png)

Original message:
![image](https://user-images.githubusercontent.com/6685872/60897745-3b623d00-a22e-11e9-9ed0-bdf82300aca7.png)

May relate to #81 

> What version of the Carbon Design System Kit are you using?

Most recent?

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

May extend beyond this one, but I am noticing in Code snippet multi-line `code snippet / multi-line / closed`

_(issue extends to all input fields that could be on forms or tiles as well)_ 

> What did you expect to happen? What happened instead? What would you like to see changed?

Should be a color override to switch the input background to work on white layers.

## Steps to reproduce the issue

1. Open Code snippet multi-line
1. No background color override :'(

**Comment by laurenmrice** [comment]
- [ ] also need to change symbols to have background `field-01` instead of `ui-01`

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.

Add to v10.5 release notes
