### ISSUE TITLE
[Color token] interactive layer styles incorrect

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#142]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

White theme

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Elements > layer styles > interaction tokens
(and any symbols that use the layer styles mentioned below) 

> What did you expect to happen? What happened instead? What would you like to see changed?

Three of the interactive tokens are labeled as `Blue 60 hover` but all three swatches have different hex values associated with them.
`$hover-primary` #0353e9
`$hover-primary-text` #054ada
`$hover-tertiary` #0062ff
<img width="1011" alt="Screen Shot 2019-07-11 at 2 28 27 PM" src="https://user-images.githubusercontent.com/45692622/61075801-ca1ab980-a3e8-11e9-8822-67b317c2fa31.png">

I have not checked the `gray-10` `gray-90` or `gray-100` sketch libraries to see if the inconsistency is also happening there.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

The website defines the colors as
`$hover-primary` #0353e9
`$hover-primary-text` #054ada
`$hover-tertiary` #0353e9

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Digital Design team

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by aagonzales** [comment]
Fixed! Available in next kit update. It was wrong in the other kits as well.

Add to v10.5 release notes
