### ISSUE TITLE
[Text input] Add password version to kit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#143]
Add password text input to kit, its in code now.

**Comment by creckling** [comment]
more reqs are being discussed over here: https://github.com/carbon-design-system/carbon/issues/3512

**Comment by aagonzales** [comment]
Adding a slightly more generic version of the component to the kit, under `text input`. There are other scenarios that would need an icon in the text input so I've made it more configurable. The specific password input component can be built from this base
- Name: `text input / with icon`
- Specific "state" symbol for the hidden characters function. `text input / with icon / 01 label only / 08 input hidden`
 
![image](https://user-images.githubusercontent.com/11670886/62169235-4ec46d80-b2ed-11e9-9dda-a37f54a9a86b.png)

Complete in themes (WIP):
- [ ] White
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by aagonzales** [comment]
Added! It will be available in the next kit update.

Add to v10.5 release notes.
