### ISSUE TITLE
[Text area] missing symbol states

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#144]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

White kit

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

text input / text area / helper text

there is only one state for text area / helper text 
<img width="536" alt="Screen Shot 2019-07-12 at 2 00 12 PM" src="https://user-images.githubusercontent.com/45692622/61148806-99e91e80-a4ad-11e9-9220-63c4c2e5b65b.png">

> What did you expect to happen? What happened instead? What would you like to see changed?

I would expect all states to be available.
I wasn't sure if this was the best approach to nesting these states, I followed the current structure for helper text within text input.
<img width="766" alt="Screen Shot 2019-07-12 at 2 00 31 PM" src="https://user-images.githubusercontent.com/45692622/61148820-a3728680-a4ad-11e9-9023-844c061a3904.png">

Or if only one state is provided, I would expect it to be enabled state, not the current focus state.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

I assume all states are available in code

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Digital Design team / Dotcom team

**Comment by aagonzales** [comment]
Re-organizing the `text-input` structure. `text-area` is now a top level item instead of nested under `text-input`

![image](https://user-images.githubusercontent.com/11670886/62088466-0f354d00-b22b-11e9-804c-ee927547fb18.png)

**Comment by aagonzales** [comment]
**Complete**
- [ ] White 
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by aagonzales** [comment]
Updated! It will be available in the next kit update.

Add to v10.5 release notes
