### ISSUE TITLE
[Structured list] change type token

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#146]
The row item symbols in structured list are using `body-short-01` but should be `body-long-01`

`structured list / item / row / 2 column even / *all*`
`structured list / item / row / 2 column offset / *all*`
`structured list / item / row / 3 column even / *all*`
`structured list / item / row / 3 column offset / *all*`
`structured list / item / row / 4 column even / *all*`

**Comment by aagonzales** [comment]
- [ ] White
- [ ] G10
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Fixed! Available in the next kit update.

Add to V10.5 release notes
