### ISSUE TITLE
[Search] Add bottom as a override

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-design-kit#149]
As a sketch kit user, I want to toggle off the bottom border so that I can mock up a data table toolbar with an expanded search.

The search symbol has a border-bottom that cannot be toggled off in the overrides. 
![image](https://user-images.githubusercontent.com/19270502/61381840-45f58580-a871-11e9-9cf9-7e4a2d17fc0f.png)

This prevents me from mocking up data table toolbars because those search fields do not have a border-bottom

![image](https://user-images.githubusercontent.com/19270502/61381904-60c7fa00-a871-11e9-8e2a-a92490d44319.png)

**Comment by aagonzales** [comment]
- [ ] White
- [ ] G10 
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.

Add to v10.5 release notes
