### ISSUE TITLE
[Filterable tag] remove hover override

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#150]
There's a bug in the filterable tag where users have the option in the override panel to change the hover color and tag color.

<img width="1016" alt="Screen Shot 2019-07-17 at 6 05 47 PM" src="https://user-images.githubusercontent.com/45692622/61415019-9397df80-a8bd-11e9-8136-0cbf9cf33fe4.png">

Found in the white theme kit.

**Comment by aagonzales** [comment]
- [ ] White
- [ ] G10
- [ ] G90 
- [ ] G100

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.

Add to v10.5 release notes
