### ISSUE TITLE
[Tool tip]: symbol bug

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#151]
## Detailed description
White theme

There is a bug when scaling tooltip symbols that have an arrow on the right. The tooltips are not a combined shape so the right arrow and rectangle overlap:
<img width="605" alt="Screen Shot 2019-07-19 at 12 13 12 PM" src="https://user-images.githubusercontent.com/45692622/61550312-1fc21800-aa20-11e9-8c12-bf222e447696.png">

All of the icon tooltip pieces are not a combined shape, but nested in a folder

Update the following symbols to combined shapes:
- tooltip / icon tooltip / item / arrow bottom / center
- tooltip / icon tooltip / item / arrow bottom / left
- tooltip / icon tooltip / item / arrow bottom / right

- tooltip / icon tooltip / item / arrow middle / left
- tooltip / icon tooltip / item / arrow middle / right

- tooltip / icon tooltip / item / arrow top / center
- tooltip / icon tooltip / item / arrow top / left
- tooltip / icon tooltip / item / arrow top / right

**Comment by aagonzales** [comment]
- [ ] white
- [ ] g10
- [ ] g90
- [ ] g100

**Comment by aagonzales** [comment]
Fixed! Will be available in the next kit update.

Add to v10.5 release notes
