### ISSUE TITLE
missing datatable/columns symbol

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#153]
I attempted to switch my datatable columns to gray 100 (from gray 10), but found the symbol missing.

gray 10 theme
![image](https://user-images.githubusercontent.com/51379566/61715236-ab8eb980-ad2a-11e9-802f-19237478d0d5.png)

gray 100 theme
![image](https://user-images.githubusercontent.com/51379566/61715318-da0c9480-ad2a-11e9-8c41-ed364e9e462d.png)

**Comment by aagonzales** [comment]
Duplicate issue, investigating this tomorrow.
https://github.com/carbon-design-system/carbon-design-kit/issues/152
