### ISSUE TITLE
[Date picker] missing error state symbol

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#154]
The single date picker is missing the error state symbol in the white theme kit

`date picker / 02 single date calendar / input / 07 error`

![Screen Shot 2019-07-23 at 9.50.45 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/0db095f4-ec21-4940-b708-74d69f789464)

**Comment by aagonzales** [comment]
Added! Available in next kit update

Add to v10.5 release notes.
