### ISSUE TITLE
Grey 100 tab component override for group of 3

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-design-kit#156]
## Detailed description

When using the grey 100 theme for the tab component, the overrides do not function properly for the group of 3 option. I cannot turn off certain tabs or change state (tabs 2 and 3) like I do in the other themes or groups. Other groups (4-6) seem to work.

## Additional information

![image](https://user-images.githubusercontent.com/20582179/61732199-b2c1c180-ad42-11e9-919c-96034b487eed.png)

**Comment by aagonzales** [comment]
Looks like the tabs somehow were unlinked from the symbol. I've update the symbol and the fix will be available with the next kit update. 


![image](https://user-images.githubusercontent.com/11670886/62889800-b32cf700-bd07-11e9-9ddc-fa888bb7e25b.png)


Add to v10.5 release notes.
