### ISSUE TITLE
Expandable tile icon behaviour and color

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-design-kit#157]
## What package(s) are you using?
Expandable tile component in the Carbon v10 white theme, grey 10 theme and grey 100 themes have issues. 

## Detailed description

The expand/collapse icon in the expandable tile stretches when you resize the tile in the Grey 10 and White theme. 
![2019-07-23 15 26 56](https://user-images.githubusercontent.com/6569324/61745393-1c4fc900-ad5f-11e9-963f-30a55e9e3254.gif)

In the Grey 90 and grey 100 theme, the icons behave correctly. 
But in the grey 100 theme, the default icon color is black when it should be white. 
![image](https://user-images.githubusercontent.com/6569324/61745409-240f6d80-ad5f-11e9-8548-4618cb95e5db.png)

![image](https://user-images.githubusercontent.com/6569324/61745447-38ec0100-ad5f-11e9-9d3d-9cf6582f988f.png)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The icon in the grey 100 theme should be white. 
In the White and Grey 10 themes, the icon should have fixed heights and widths set in their responsive behaviour so that they remain the same when the tile is resized. They should also be pinned to the bottom right corner so they stay in the same relative position.  

The grey 90 theme has a correct implementation: 
![2019-07-23 15 29 13](https://user-images.githubusercontent.com/6569324/61745770-de9f7000-ad5f-11e9-98e5-4bceec2a2fe9.gif)
 

> What version of the Carbon Design System are you using?

July 22 2019

**Comment by aagonzales** [comment]
Fixed! Available in the next kit update.

Add to V10.5 release notes.
