### ISSUE TITLE
 Multi-select data table checkboxes have the same visual styling as boolean value columns

### ISSUE THREAD

**Issue by AlexisMaeLandis** [carbon-design-system/carbon-design-kit#158]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

My team is currently using a multi-select table with a column to show boolean values. The styling for the boolean values is the same as the checkboxes to select a row. We ran into some troubles with users thinking they could click the checkboxes in that column just as they would a row. 

> What version of the Carbon Design System Kit are you using?
Carbon 10.

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Multi-select data table checkboxes, boolean values

> What did you expect to happen? What happened instead? What would you like to see changed?
The visual styling of boolean values to be different than multi-select data table checkboxes.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Hardware Management Console for Z, GA1 (September 23)

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links

<img width="692" alt="Screen Shot 2019-07-24 at 3 01 23 PM" src="https://user-images.githubusercontent.com/41640763/61820876-ecb6c480-ae23-11e9-9206-ba431d00209d.png">

* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by aagonzales** [comment]
@AlexisMaeLandis I'm not sure what the ask is here. The checkboxes you current are using should only be used for items that are selectable. If the items isn't selectable then there does need to be a different visual indicator. Do you have any recommendation on how else to show the boolean values? This isn't also exclusively a design kit problem, you can use the icon cell option to insert a different type of icon as a visual indicator.
