### ISSUE TITLE
[Dropdown] Check textboxes for resizing issues

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#159]
Some dropdown textboxes are jumping input text to the next line. Might have to do with auto vs. fixed text and how the textboxes are being pinned. This is happening in Gray 10 theme but check all themes.

Example:
![Screen Shot 2019-07-24 at 10.17.16 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/5bd9e689-1606-40a9-8ea4-f383e7a766e6)

**Comment by aagonzales** [comment]
I believe we fixed all these.
