### ISSUE TITLE
[Progress indicator] Vertical variant has textbox resizing issues

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#160]
Might be a textbox fixed vs. auto and pinning issue. This is happening in Gray 10 theme but check all themes.

Example:
![Screen Shot 2019-07-25 at 1.44.55 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/4d79cb54-5862-45ac-9557-8e0084cef518)

**Comment by oliviaflory** [comment]
I also noticed a pinning issue on the White theme where the second item is moving into the third

<img width="164" alt="Screen Shot 2019-07-26 at 10 12 37 AM" src="https://user-images.githubusercontent.com/45692622/61958279-0a546d00-af8f-11e9-95f2-89ccd1360a0d.png">

**Comment by aagonzales** [comment]
Both are fixed! Available with next kit update.

Add to v10.5 release notes.
