### ISSUE TITLE
[Dropdown/Text inputs, etc] Audit inconsistent lengths and propose default

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#161]
We have noticed that our variants of dropdowns and text inputs are all different lengths in our design kits.

Audit:
![Screen Shot 2019-07-29 at 1.34.01 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/5330d0b2-b018-44d1-a741-8853a3e701ad)

It would be a good idea to align these on a common default length when appropriate instead of having so many different variations.

**Comment by oliviaflory** [comment]
FYI: for the digital kit I've changed our inputs and dropdowns to 288px, that size seemed to fit nicely on sm, md, and xl breakpoints as many of our designers will start with one of those.

**Comment by laurenmrice** [comment]
oh great, yeah I was leaning towards 288px as well. ^

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
updated in all kits 🎉 available in next update. text inputs and dropdowns are at 288px and number input i'm keeping at 160px.
