### ISSUE TITLE
ComboBox  symbols

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon-design-kit#162]
ComboBox is provided in Carbon Components React:
http://react.carbondesignsystem.com/?path=/story/combobox--default

but I don't see there is a corresponding Sketch symbol defined. Are you going to provide a ComboBox symbol?

**Comment by laurenmrice** [comment]
We do have a combo box symbols. It is under Dropdown / 02 combobox. 

![Screen Shot 2019-08-01 at 11.13.12 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/29ede70c-da00-46c5-a7ea-0fe6b51708d9)

**Comment by zhenwan** [comment]
Got it. Thanks!
