### ISSUE TITLE
SkeletonText symbols

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon-design-kit#165]
SkeletonText is provided in Carbon Components React:

http://react.carbondesignsystem.com/?path=/story/skeletontext--default

but I don't see a corresponding Sketch symbol defined. Are you going to provide a SkeletonText symbol?

**Comment by laurenmrice** [comment]
@zhenwan We do have skeleton symbols for components that need them in the kits. We introduce skeletons as a `state`. Here is the 'button' skeleton states as an example:

![Screen Shot 2019-08-01 at 11.18.17 AM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/84726188-728b-4152-8244-03c580691734)

**Comment by zhenwan** [comment]
Thanks !!
