### ISSUE TITLE
[Color tokens] Update values in kits

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#167]
Found inconsistencies in the kit we need to update:

--------------------------------------------------------------------------------------------------------

**White theme**
- [x] `interactive-02`
Gray 80
3d3d3d

--------------------------------------------------------------------------------------------------------

**Gray 10 theme**
- [x] `interactive-02` 
Gray 80
3d3d3d

- [x] `inverse-support-04`
Should say Blue 50 on elements page, the style is correct though.

- [x] `highlight`
Blue 20
c9deff

--------------------------------------------------------------------------------------------------------

**Gray 90 theme**
- [x] `highlight`
Blue 70
054ada

--------------------------------------------------------------------------------------------------------

**Gray 100 theme**
- [x] `highlight`
Blue 80
0530ad

- [x] `skeleton-02`
Gray 80
3d3d3d

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.

Add for v10.5 release notes
