### ISSUE TITLE
[Date picker, drop shadow] Missing drop shadow on G10, G90, G100 themes

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#171]
### Specific to G10, G90, G100 themes only: 

1. Date picker's dropdown part is missing dropshadow: 

![image](https://user-images.githubusercontent.com/15144993/62882862-6db4fd80-bcf8-11e9-8baf-71c3b8f4d7ae.png)

2. Drop shadow symbol (taken from Dropdown) has a G10 fill on these themes too. Should be using `$ui-background` color. 

![image](https://user-images.githubusercontent.com/15144993/62882960-a1902300-bcf8-11e9-9970-00795954cead.png)

**Comment by aagonzales** [comment]
- [ ] White
- [ ] G10
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Fixed! Available in next kit update.

Add to v10.5 release notes
