### ISSUE TITLE
[Colors] Update kit's color hexs to V2

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#174]
### Update design kit's color values to V2 color (or export elements via Josh's magic)
Final V2 color palette sketchfile: https://ibm.box.com/s/uuc0792cw6lg3ovkoeo8sec3nr6vfghh

**Comment by joshblack** [comment]
@shixiedesign if we update this in elements then we can 100% generate it in Sketch!

**Comment by laurenmrice** [comment]
wooohooo!

**Comment by shixiedesign** [comment]
@aagonzales @laurenmrice Just wanna make sure you guys have your eyes on this issue! I think the last time we discussed it, we think it will be faster to manually update the token values instead of waiting on export from code, because we do not know if exporting from code will keep the layer styles linked to symbols.

**Comment by laurenmrice** [comment]
Yep, color styles have been updated manually for this release in all kits 👍. Will test with updated from the IDL kit once code is imported into the plugin

**Comment by josh-tt** [comment]
Just received a notice that the Sketch Libraries were updated and found this issue about v2 colors.  Is there a Changelog for the minor library updates available? When downloading the new libraries to make it local from Sketch Cloud, I'm a bit confused by a few things which appear to be bugs, but perhaps are a misunderstanding on my part.

1. The IBM Design Language Library file on https://www.carbondesignsystem.com/resources is different from the one on https://www.carbondesignsystem.com/get-started/design . The v2 sketch file has fewer colors than the v1 sketch file, which has hover colors, so I'm wondering what the deal is.

2. I'm assuming v2 to is the latest going by the date of last update. However, when I download the Libraries from Sketch Cloud to view locally, I can see certain styles that appear to still reference IBM Design Language/color/gray/ (which I presume is a reference to another existing library, but I'm wondering why it's not v2). 

For example, in the White theme, if you go to Tags (which seem to not be vertically centered btw) and view the tag color, the Appearance panel shows IBM Design Language as the path and what appear to be the v1 colors.

**Screenshots:**
https://snipboard.io/0zO36Z.jpg 
https://snipboard.io/CikWzL.jpg

3. Some colors (in previous and the latest libraries), seem to reference the v1 colors. For example $hover-secondary is #606060, yet in the V2 IBM Language document says Gray 60 is #6F6F6F.

Can anyone provide some clarity here?

Thank you!

**Comment by laurenmrice** [comment]
@josh-tt 

We left the Getting Started file as the v1 file until we knew that our v2 file would work correctly for everyone. We will update that link to the new v2 file.

We will be deprecating the hover colors with our v2 color palette update (replacing with a lighten/darken approach) so that is why there will be fewer colors.

Tag is an interesting component. Some people are seeing it in their files as centered and for others it is jumping a little high. We are currently trying to resolve that issue.

For the Gray 60/Gray 60 hover discrepancy: The `hover-secondary` is a Gray 60 hover color value (#606060) which is different than the Gray 60 color value (#6f6f6f) which is intentional.

**Comment by josh-tt** [comment]
Thanks @laurenmrice. Helps to clarify things. Would be great if there was a Changelog for each Sketch Library update.

Regarding Tag,  I simply have to tick align to middle on the text layer and it's fixed as the y-position is 3px, not 4px.

**Comment by laurenmrice** [comment]
I just made an update to tag to hopefully fix that alignment 👍 @josh-tt
