### ISSUE TITLE
Sketch dropdown menu input is wrapped

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-design-kit#177]
## Detailed description

When users select the Sketch Carbon Design System White Theme dropdown menu with label, the "Input text" placeholder text displays as wrapped:

![image](https://user-images.githubusercontent.com/12902530/63130597-9b13dc80-bf80-11e9-8b43-eb6aafcbe463.png)

When users enter longer input text, the text wraps, too:

![image](https://user-images.githubusercontent.com/12902530/63130543-6dc72e80-bf80-11e9-89e4-cc003e51bdcf.png)

Will you please fix the Sketch Carbon Design System White Theme dropdown menu with label, "Input text"?

**Comment by aagonzales** [comment]
@lnajjar Can you make sure you've updated your library. This fix has already been made. Please re-open if its still broken and you are up-to-date.

**Comment by lnajjar** [comment]
Huh. Something weird happened.

Anna, my Sketch app still lets me insert Carbon Design White Theme symbols
(components) and IBM Design Language colors and icons. But, I cannot edit
aspects like labels and placeholders.

When I try to install the libraries, I get an error that I already have
them.

Have you run into this problem?

What do you think will happen if I delete the libraries and re-install
them? Will I lose all my work?


Lawrence Najjar
lnajjar100@gmail.com
http://www.lawrence-najjar.com/new-index.html
(512) 740-6852

**Comment by aagonzales** [comment]
You don't need to re-install or re-add, you need to update the library. Did you look for the updates?

It can shown in the upper right corner of Sketch. You can to select "Shared library updates available"

![image](https://user-images.githubusercontent.com/11670886/63378695-6923c100-c358-11e9-9e21-3aeb3fb36865.png)

It might also be hidden under a tag.

![image](https://user-images.githubusercontent.com/11670886/63378612-3aa5e600-c358-11e9-9cc8-a174aa200985.png)

That should prompt the preference window to open. You'll then click on "Download" beside the Carbon Libraries.

![image](https://user-images.githubusercontent.com/11670886/63378841-aee08980-c358-11e9-8a07-6a146e8e4006.png)

**Comment by lnajjar** [comment]
I am familiar with shared library update notifications and always perform
the updates.

No, as you can see, I don't have any update notifications:

[image: image.png]


So, when you do: Skype > Insert > Carbon Design System (White theme) >
dropdown > 01 default > 01 label > closed > 01 enabled

do you get this:

[image: image.png]


which produces this:

[image: image.png]


even if you stretch it out horizontally like this:

[image: image.png]




Lawrence Najjar
lnajjar100@gmail.com
http://www.lawrence-najjar.com/new-index.html
(512) 740-6852

**Comment by aagonzales** [comment]
@lnajjar The images didn't come through. Can you repost them. 

FYI it helps to have this level of detail in the initial comment. 

> So, when you do: Skype > Insert > Carbon Design System (White theme) >
dropdown > 01 default > 01 label > closed > 01 enabled

**Comment by aagonzales** [comment]
Ok it was just on that one set of dropdown. I was looking at a different variation. Sketch recently pushed an update that fixed a lot of out auto-width text boxes. I thought we had fixed all of them but this was slipped through. Sorry for the confusion.
