### ISSUE TITLE
Sketch text input Helper text is not italicized

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-design-kit#178]
## Detailed description

> Describe in detail the issue you're having.

The Carbon Design text input Helper text is displayed as italicized:

https://www.carbondesignsystem.com/components/text-input/code

![image](https://user-images.githubusercontent.com/12902530/63130309-98fd4e00-bf7f-11e9-9d1c-3218f73e35b3.png)

The Sketch Carbon Design System White Theme text input component comes in with non-italicized text. I cannot change the Sketch text input helper text to italicized to match the Carbon Design system.

![image](https://user-images.githubusercontent.com/12902530/63130210-4f146800-bf7f-11e9-88ae-32c857827c5c.png)

Will you please fix the Sketch Carbon Design System White Theme text input component so the text input helper text is italicized?

**Comment by laurenmrice** [comment]
Thanks for finding this ! We will be updating this style eventually according to this open issue: https://github.com/carbon-design-system/carbon/issues/2329

Once we implement our updated color palette we will make these changes in code and in the kit :)

**Comment by aagonzales** [comment]
It actually is currently italic in the master file. I'm not seeing "helper text" anywhere in the kit where it is non-italic at the moment. @lnajjar Please check you're Sketch and Carbon kits are update to date. Here are instructions on how to update your library. Also make sure you haven't overridden any of the styles. https://www.sketch.com/docs/libraries/library-updates

From White theme master file
![image](https://user-images.githubusercontent.com/11670886/63379734-89ed1600-c35a-11e9-883c-964f3ccaaf86.png)

**Comment by lnajjar** [comment]
Yes, my Sketch and Carbon Design System (White theme) libraries are
up-to-date.

This is weird.

Are you on a Macintosh?

You mention a "Master" file. Is that what is available to outside users?

If somehow, mysteriously some of the library component update checkboxes
got selected off, how do I get them selected on?


Lawrence Najjar
lnajjar100@gmail.com
http://www.lawrence-najjar.com/new-index.html
(512) 740-6852

**Comment by aagonzales** [comment]
Yes, I'm on a Mac.

No, only the Carbon team can access the master file (otherwise anyone could push changes to the libraries that might not be approved). You can download them from [Sketch cloud](https://sketch.cloud/s/JaVzz), but once you do that they will no longer be connected and receive updates. 

> If somehow, mysteriously some of the library component update checkboxes
got selected off, how do I get them selected on?

Are the controls showing up in the overrides panel on the left? That is where you would turn them on.

**Comment by laurenmrice** [comment]
Helper text has been changed to Regular instead of Italic and is now a different color. Add to v10.6 release notes
