### ISSUE TITLE
[Sketch kit] pinning issue with gray 90 & gray 100 arrow bottom left & right

### ISSUE THREAD

**Issue by janedepgen** [carbon-design-system/carbon-design-kit#182]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file. 

> What version of the Carbon Design System Kit are you using?
Connected via Sketch Cloud, up to date as of Aug 27 3:50pm

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
- `theme: gray 100 / tooltip / piece / arrow bottom-left`
- `theme: gray 100 / tooltip / piece / arrow bottom-right`
- `theme: gray 90 / tooltip / piece / arrow bottom-left`
- `theme: gray 90 / tooltip / piece / arrow bottom-right`

> What did you expect to happen? What happened instead? What would you like to see changed?

1) The bottom arrow appears to be pinned to the top of the symbol instead of the bottom for the 4 symbols listed above. When resizing to change the height of the tooltip the arrow stays in place and disappears beneath the tooltip container.

2) `theme: gray 90 / tooltip / piece / arrow bottom-right` also seems to be pinned to the left instead of the right

**Comment by laurenmrice** [comment]
Fixed! Available in the next update. Add to v10.6 release notes
