### ISSUE TITLE
[sketch kit] - overflow menu, ghost button dark themes have dark icons

### ISSUE THREAD

**Issue by janedepgen** [carbon-design-system/carbon-design-kit#185]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

Up to date Sketch Cloud libraries

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Gray 100 & Gray 90 overflow menu / 01 enabled
Gray 100 & Gray 90 icon button / 01 enabled

> What did you expect to happen? What happened instead? What would you like to see changed?

icon colors are black instead of white, don't show up on dark themes

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

dependency – using these symbols in Watson Health add on library

**Comment by aagonzales** [comment]
@janedepgen they're the correct color in the kit so I'm wondering if the color is getting overridden when placed in another file. I'll update the overrides in the symbols so that you can choose the icon color is this happens.

**Comment by laurenmrice** [comment]
Fixed! Available in the next update. Add to v10.6 release notes
