### ISSUE TITLE
[Date picker] type style

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#187]
## Detailed description

I'm working on the expressive theme design kit, and noticed the `date picker` and `time picker` are using `code-02` type style within the symbol. 
<img width="790" alt="Screen Shot 2019-09-04 at 10 16 04 AM" src="https://user-images.githubusercontent.com/45692622/64263282-618a1d80-cefd-11e9-97c5-b3bbc5420300.png">

When I double checked the documentation and Story book, the component is using `body-short-02`
<img width="212" alt="Screen Shot 2019-09-04 at 10 16 53 AM" src="https://user-images.githubusercontent.com/45692622/64263388-8f6f6200-cefd-11e9-8143-0de566e53f38.png">

The most obvious difference is the width of the "mm"s and the dot that appears in the center of the zero in the mono type.

> What version of the Carbon Design System Kit are you using?

White theme

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

- date picker / simple date / mm/yyyy
- date picker / simple date / mm/dd/yyyy
- date picker / single date calendar
- date picker / range date
- date picker / time picker
- date picker / pieces / hh:mm

> What did you expect to happen? What happened instead? What would you like to see changed?

Can we confirm which type token these components should be using

`code-02` or `body-short-01`

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

design kit is documented as `code-02`
website/code are documented as `body-short-01`

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I am working on the expressive theme design kit, which is dependent on the theming work Matt and Josh are working on for the October release. 

If the component should be using `code-02` I will need to propose adding another type style to accommodate the 16px type size. 
I'm thinking `code-03` would make the most sense for how the type scales work.
`font family`: `IBM Plex Mono`
`font size`: `16px`
`font weight`:`regular`
`line height`: `24px` (also open to 22px)

## Additional information

screen shots included in issue summary

**Comment by oliviaflory** [comment]
not stale

**Comment by oliviaflory** [comment]
not stale

**Comment by laurenmrice** [comment]
The date picker is now using `code-02` now. This is what we also have in the kits.
