### ISSUE TITLE
[Slider] design kit and code discrepancy 

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#188]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

The slider component has a number of discrepancies between the code, design kit and documentation in the following areas:

- start and end value type style (purple)
- number input type style (purple)
- track color (cyan)
- padding between number values, track and number input field (teal)

<img width="991" alt="Screen Shot 2019-09-10 at 2 41 59 PM" src="https://user-images.githubusercontent.com/45692622/64641048-56d9f780-d3d9-11e9-85a0-8fdcbb631786.png">

*I'm not sure if this should be in the design kit repo, or carbon mono repo*

> What version of the Carbon Design System Kit are you using?

White theme

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Related to slider component, and number component which is linked within the slider component (if number input should be mono type style)

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the design kit, code and documentation to match.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

Inconsistent type style usage and documentation noted above.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Working on the Expressive design kit, which will be released after the theming work in October.

**Comment by laurenmrice** [comment]
@oliviaflory Thanks for catching this, the text should be mono for start/end and number input for Slider. We should also be using the ui-03 for the lines. I will make separate issues addressing changes for these for the website, kit, and in code.

**Comment by oliviaflory** [comment]
Thanks for the update @laurenmrice 

Does that mean that the number input component also use mono? Currently, the number input is using Plex sans in the Design kit

What about the spacing between the start/end values and the slider track and the spacing between the end value and number input? They vary between 8px and 16px in the code, kit and documentation.

**Comment by laurenmrice** [comment]
Yes the number input should be mono. The spacing should be 8px between the start/end values and slide tracker. The spacing should be 16px between the end value and number input.

**Comment by laurenmrice** [comment]
Going to close this issue and address these in the following separate open issues. 

Website: #4013
Component: #4012
Kit:  #196 (fixed!)
