### ISSUE TITLE
[Token] Serveral updates

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#189]
_Mirroring issue https://github.com/carbon-design-system/carbon-website/issues/295_

New tokens are added after palette update & component accessibility fixes: https://github.com/carbon-design-system/carbon/pull/3962

### Values

| White | G10 | G90 | G100 |
| --- | --- | --- | --- |
| Red 60 | Red 60 | Red 60 | Red 60 |  

### Usage 
3:1 accessible
Danger button background, danger border, error icon

### Values

| White | Gray 10 | Gray 90 | Gray 100 |
| --- | --- | --- | --- |
| Gray 60 | Gray 60 | Gray 50 | Gray 50 | 

### Usage 
Tertiary text, helper text.

### Values update

| White | Gray 10 | Gray 90 | Gray 100 |
| --- | --- | --- | --- |
| Gray 80** | Gray 80** | Gray 30 | Gray 30 | 
** = changed

### Usage update
Remove "helper text"

### Usage:
Remove "danger button background"

**Comment by aagonzales** [comment]
Updated! Available in the next kit update. 

Add to v10.6 release notes
