### ISSUE TITLE
[File uploader] Add drag and drop variations

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#190]
PR: https://github.com/carbon-design-system/carbon/pull/3873#pullrequestreview-287660573

![image](https://user-images.githubusercontent.com/11670886/64815668-bd8f1a80-d56b-11e9-88cb-58cfcd474a3f.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
released 🙌
