### ISSUE TITLE
[Sketch kit] pinning issue with gray 90 & gray 100 data set table  column 48 deafult selectable+expendable header

### ISSUE THREAD

**Issue by skwon14** [carbon-design-system/carbon-design-kit#193]
The checkbox on the selectable + expendable table header is resized when resizing the column width.  The checkbox should stay the same even the column size is changed. 

Please view the screenshot below.

<img width="309" alt="Screen Shot 2019-09-16 at 2 30 40 PM" src="https://user-images.githubusercontent.com/48769110/64983817-66e94f80-d88f-11e9-8df1-0bbfd6a32369.png">

**Comment by laurenmrice** [comment]
Fixed! Available in the next update. Add to v10.6 release notes

**Comment by skwon14** [comment]
Thanks for the quick fix!
