### ISSUE TITLE
licence clarity

### ISSUE THREAD

**Issue by rayglover-ibm** [carbon-design-system/carbon-design-kit#2]
It's not clear what I can do, legally, with the contents of this repository. Indeed, it's not clear who owns what, in particular the fonts contained in `HelvNeueforIBM.zip`. Some clarity would be useful.

**Comment by aagonzales** [comment]
The Sketch file, like the component library is open sourced. We are double-checking into the legal issues with the typeface and we'll let you know. For the moment, we have removed the typeface from the repo and will add it back if we get official word. 

**Please not that without the proper typeface the assets in the Sketch file will render poorly and not to spec.**

**Comment by kendor** [comment]
HelvNeueforIBM.zip (v1 Nov2015) is available via the IBM Northstar site(!)...

https://www.ibm.com/standards/web/design/design-checklist/
https://www.ibm.com/standards/web/attachments/HelvNeueforIBM_v1_Nov2015.zip

But, yes, I too would appreciate clarity on the Open Source licensing/usage status(?).

**Comment by aagonzales** [comment]
We followed up with IBM Design and Monotype (the holder of our license) and we do not currently have permission to distribute the Helvetica Neue for IBM fonts outside of the IBM ecosystem. Therefore the font will not be downloadable and will stay removed from the repo. 

_As a footer note: IBM is in the process of designing a custom typeface which will then hopefully be able to attach to the kit in the future._
