### ISSUE TITLE
[Icon kit] Checkbox: Need to change to new icon library in themed kits

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#200]
Need to change out checkbox and indeterminate  icons in all kits once the inner fill becomes editable for those icons.

Ref: https://github.com/carbon-design-system/carbon/issues/4053

- [x] In code: fixed by pr https://github.com/carbon-design-system/carbon/pull/5888
- [x] In Icon kits

-------------------------------------------------------------------------------------------------

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

**Comment by laurenmrice** [comment]
not stale. still waiting to resolve bug that is being generated from the sketch plugin

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
Sketch icon libraries have been updated. We can now make these icon changes in the themed libraries. 👍

**Comment by jillianhowarth** [comment]
Updated the checkbox icons. They'll be available in the next kit update 🎉
