### ISSUE TITLE
[Date picker] override missing

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#201]
Cannot override the text value inside of date picker / pieces / day / 04 today in white theme sketch kit, looks like the Text value override is turned off.

<img width="582" alt="Screen Shot 2019-09-25 at 11 20 31 AM" src="https://user-images.githubusercontent.com/45692622/65614974-94688400-df86-11e9-93dc-ef3fa2a4f208.png">

**Comment by aagonzales** [comment]
Fixed!
v10.8
