### ISSUE TITLE
[Notification] inconsistent overrides

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#202]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

The inline multi-line notifications have varying overrides across all themes. I expected only the text values to have overrides, but am able to change the `border-left` color and `background color` in high and low contrast variants.

*I have not checked the other variants (01 inline and 03 toast) across the themes*

> What version of the Carbon Design System Kit are you using?

All themes

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

### white
notification / high contrast / 02 multi-line
- success border left

notification / low contrast / 02 multi-line
- informational background
- success border left / background
- error background

### gray 10
notification / high contrast / 02 multi-line
- success border left

notification / low contrast / 02 multi-line
- informational background
- success border left / background
- error background

### gray 90
notification / high contrast / 02 multi-line
- informational border left / background
- success border left / background
- warning  background
- error background

notification / low contrast / 02 multi-line
- informational border left 
- success border left 

### gray 100
notification / high contrast / 02 multi-line
- warning border left

**Comment by laurenmrice** [comment]
Fixed! Available in the next update. Add to v10.6 release notes
