### ISSUE TITLE
Sketch symbols name convention of IBM Design Language

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon-design-kit#203]
I am working on a Sketch plugin which needs to parse the symbol name of IBM Design Language. I have seen that the symbol names  are well organized except several exceptions(see the screen capture): ‘/’ character is used to separate the node (leave) name in the name tree, but I see ‘/’ character is used in the node name as well,  i.e. “new/tab”, “loading––dark/16" and “loading––white/16”. is it possible to change these symbol names so that they will follow other symbols naming convention?

![image](https://user-images.githubusercontent.com/14806866/65796995-b9e6c080-e133-11e9-9e3c-fe179461bc8f.png)

**Comment by zhenwan** [comment]
Any update to this issue?

**Comment by josh-tt** [comment]
Would also be better if the symbol names had spaces `name / name` instead of `name/name`. This way we can use a plugin like [Puzzle Tokens](url) to edit the styles using scss or less.

**Comment by aagonzales** [comment]
The icon names follow how they're named in code so we can't customize that. The `/` is what puts it in the tree structure. 

If you want to change the name of specific icons it needs to be changed in code first. This also may be working differently in the new v2 language library (I didn't check). 

Also issue with the Language kit (not Carbon) should be opened here: https://github.com/IBM/design-kit

**Comment by josh-tt** [comment]
@aagonzales Thanks! I will continue the conversation in the other github link because I believe it's still an inconsistency that should probably be resolved. ;)
