### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by Ragha100** [carbon-design-system/carbon-design-kit#206]
Currently single slider option is supported where we can see the range selected however there is no option to choose the lower value and higher value slider. Please look in to this requirement  and consider a design request.

Thank you

**Comment by laurenmrice** [comment]
Currently in the Slider component you can type into the input field to change it to any value within range, it can also be the start or end value. 

Are you talking about additionally adding a link to the start and end value to automatically change the input value?
