### ISSUE TITLE
 "ui shell / left panel / group / side-nav / default" symbol's sub-symbols and their Overrides in Sketch don't follow the same sequence 

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon-design-kit#208]
This issue only exists in White Theme
![image](https://user-images.githubusercontent.com/14806866/66343856-20c56000-e912-11e9-98f0-e3ffb8c62138.png)

**Comment by laurenmrice** [comment]
Thanks for catching this ! fixed in the next kit update 🎉
