### ISSUE TITLE
Gray 90 Multi-select dropdown using wrong 'Selected' color

### ISSUE THREAD

**Issue by jimmydyer** [carbon-design-system/carbon-design-kit#209]
## Gray 90 Multi-select dropdown using wrong 'Selected' color

`Gray 90 Theme`
![Threat_details-AIA-v16_sketch](https://user-images.githubusercontent.com/54411478/66425921-5a5f9f00-e9d6-11e9-9e12-bb03ccabff66.png)

As you can see in the image above when I updated my sketch library, all the multi-select dropdown components reflected this. The numbers in the pill changed to white.

> What version of the Carbon Design System Kit are you using?
![Preferences](https://user-images.githubusercontent.com/54411478/66426152-d954d780-e9d6-11e9-914b-ac6aca39cc52.png)

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
![Screen Shot 2019-10-08 at 2 21 35 PM](https://user-images.githubusercontent.com/54411478/66426262-0f925700-e9d7-11e9-8a86-636139501d4a.png)

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected the number in the pill to remain the same color. Instead, the number in the pill changed to white in which you can no longer see the number.

## Steps to reproduce the issue

1. Use the gray 90 theme
2. Insert multi-select dropdown with `Selected` state visible

**Comment by laurenmrice** [comment]
Thanks for catching this. This was resolved in the latest sketch update  👍
