### ISSUE TITLE
User Testing :: Sketch 47 Libraries Kit

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon-design-kit#21]
Looking to have 5-6 sponsor users to use the design kit + sketch 47 libraries. We have created a Carbon library and are looking for bugs, usage problems, frustrations, and how users are utilizing symbols. More official research plane to follow soon.

**Comment by tay-aitken** [comment]
[Tutorial](https://www.youtube.com/watch?v=suP1sOU4J3E) for Sketch 47 libraries
[Article](https://medium.com/ux-power-tools/sketch-libraries-how-they-work-and-the-crazy-stuff-you-can-do-with-them-fc10f142ac80) about Sketch 47 library capabilities

**Comment by alexeiboronnikov** [comment]
I'm happy to help you

**Comment by tay-aitken** [comment]
@alexeiboronnikov are you interested in having us test with you?

**Comment by tay-aitken** [comment]
Had to move this epic over to the internal repo so that the users that only had a GHE account could participate.

**Comment by alexeiboronnikov** [comment]
@tay-aitken yep, I'm interesting in testing

**Comment by tay-aitken** [comment]
Hi @alexeiboronnikov! Do you work at IBM? We are currently only testing internally for the first round.

**Comment by alexeiboronnikov** [comment]
@tay-aitken ah I see, I do not work at IBM
