### ISSUE TITLE
Text cursor fill color using gray100 from color palette v1

### ISSUE THREAD

**Issue by ericgendreau** [carbon-design-system/carbon-design-kit#211]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

The issue relates to `text input` and `text area` components for both the gray10 and white themes, with and without helper text.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected the cursor to be the gray100 (#161616) from the v2 color palette but it's using the gray100 (#171717) from v1.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Z. No pressing ship or release dates.

**Comment by laurenmrice** [comment]
Thanks for catching this ! fixed in the next kit update 🎉
