### ISSUE TITLE
In Sketch library, the UI Header has a 'hack spacer' using text instead of a spacer object. 

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#213]
## Detailed description

The UI Header has a 'hack spacer' using text instead of a spacer object. I was trying to understand why that was done instead of using the included spacer symbol.

> What version of the Carbon Design System Kit are you using?

Latest

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

UI Shell Headers.

> What did you expect to happen? What happened instead? What would you like to see changed?

A 'hack spacer' is used instead of the library 'spacer symbol'. 

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Open Sketch library and open a Header.
2. Check the symbol and you will see a 'text' hack layer used instead of an actual 'spacer' symbol. 

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels

Libraries

**Comment by aagonzales** [comment]
It was the only way to get the links to auto-responded to each other when you adjust the text length. The catch was it only worked when the spacing was 16px or less so we had to put an "invisible" character in there to get a longer padding distance. It was a hack we found on the internet. I can't remember the article where we got the information from. 

Anyways, the hack isn't needed anymore now that Sketch has released auto layout settings.
