### ISSUE TITLE
The .clr paleltte file seems to give Sketch incorrect values.

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#214]
## Detailed description

When applying Grey 100 for example from the apple color (view>show colors) in sketch, the hex value generated is #161616 when in fact is should be #171717. Resetting the 'hsb' values in Sketch seems to correct the issue. I'm not sure if this is a sketch bug or apple color picker bug (or perhaps related to profiles), but it through me off when trying to use the .clr palette. It would be better (more safe) to simply include the palettes as document colors perhaps or simply provide a 'sketch palette' doc with the kit if one already isn't available somewhere.  

This issue is relatively minor, but led to a lot of confusion and general doubt/distrust as to whether or not it was safe to design using the .clr palette file. 

> What version of the Carbon Design System Kit are you using?
Latest

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

> What did you expect to happen? What happened instead? What would you like to see changed?

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Add .clr palette file to system
2. Open sketch
3. Create a rectangle
4. View > Colors to open system color picker.
5. Apply grey 100 too the object (#161616)
6. Manually re-enter the values for hsb and becomes #171717

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

![image](https://user-images.githubusercontent.com/29612594/66801263-11b26380-ef4b-11e9-8ab7-857a60585c20.png)

**Comment by aagonzales** [comment]
`#171717` is the old Gray 100 value. In the new v2 palette `#161616` is correct. 
Refer to our blog post about the color updates.
https://medium.com/carbondesign/because-colors-are-beautiful-52dd4cc39f09
