### ISSUE TITLE
Shell header text overlaps nav items. 

### ISSUE THREAD

**Issue by talaeh** [carbon-design-system/carbon-design-kit#216]
Bug found in new sketch kit where shell header text overlaps nav items. 
<img width="678" alt="Screen Shot 2019-10-15 at 1 52 36 PM" src="https://user-images.githubusercontent.com/56605319/66856757-e4b67e80-ef53-11e9-8983-cf4e373a991b.png">

White theme

**Comment by aagonzales** [comment]
Duplicate issue: https://github.com/carbon-design-system/carbon-design-kit/issues/226#issuecomment-553534490
Fixed! Available in next kit update.
