### ISSUE TITLE
Apply Smart Layout to symbols that are breaking because of sketch update

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#218]
Start applying smart layout in places where we have physical breaks in our symbols in the kits.

- [x] UI Shell header + links
- [x] Check radio button
   - Horizontal group
- [x] Check tag 
- [x] Check notification
- [x] Breadcrumb
- [x] Button
- [x] Tooltip - icon
- [x] Code snippet - inline

**Comment by aagonzales** [comment]
This setting
![image](https://user-images.githubusercontent.com/11670886/67116600-5ab22400-f1a6-11e9-9708-d35897621c68.png)

makes this interaction
![Oct-18-2019 12-55-04](https://user-images.githubusercontent.com/11670886/67116711-a238b000-f1a6-11e9-8692-e545ad7770e0.gif)

**Comment by aagonzales** [comment]
Even spaced container
- set container to be `fixed width`
![image](https://user-images.githubusercontent.com/11670886/67121661-a74f2c80-f1b1-11e9-86e8-5ca6e6454a16.png)
- Button was set to have `fixed-width`
![Oct-18-2019 14-17-28](https://user-images.githubusercontent.com/11670886/67121842-188edf80-f1b2-11e9-8a2a-e7f863d2e4bf.gif)

**Comment by aagonzales** [comment]
## Vertical - top down

- Use to make things auto-response vertically
![image](https://user-images.githubusercontent.com/11670886/67125836-44fb2980-f1bb-11e9-81d3-251919c356ce.png)
![Oct-18-2019 15-27-28](https://user-images.githubusercontent.com/11670886/67126445-b091c680-f1bc-11e9-84a9-b10abe62ebea.gif)

**Comment by aagonzales** [comment]
## Icon centered aligned 
- Need to place icon in a "group" folder and pin the corner to the left and right. 
   - Do not add layout to the group.
   - ![image](https://user-images.githubusercontent.com/11670886/67247756-f2727500-f427-11e9-8ff3-b5695c8082bd.png)

- Layout: horizontal + center
   - ![image](https://user-images.githubusercontent.com/11670886/67247869-3f564b80-f428-11e9-9936-58d2f864779a.png)
![Oct-21-2019 17-32-10](https://user-images.githubusercontent.com/11670886/67248064-cd323680-f428-11e9-9a13-e1399a454101.gif)
(Used the override panel instead of inline typing which wasn't working 🤔 )

**Comment by aagonzales** [comment]
If things are working, check these setting first:
- Text alignment: auto width
- No layers that need to respond are in grouped layers
- Layout is applied to the artboard

**Comment by aagonzales** [comment]
UI Shell fixes from Mariusz 

![image](https://user-images.githubusercontent.com/11670886/68791085-35ca9880-060e-11ea-8c5d-8c6b5ec5c1ff.png)

![image](https://user-images.githubusercontent.com/11670886/68791123-47ac3b80-060e-11ea-8a8a-7374a53cfbc9.png)

![image](https://user-images.githubusercontent.com/11670886/68791137-4da21c80-060e-11ea-9378-dfe5a7361ee6.png)

**Comment by laurenmrice** [comment]
not stale

**Comment by mariuszmickiewicz** [comment]
Few types of tooltips fixed and made smart in these themes:

- [ ] White
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by mariuszmickiewicz** [comment]
Also I recently updated **UI Shell header** – now icons on the right can be removed (a symbol turned off) and all other icons will align back to the right (no empty space between them). Not yet uploaded to Cloud I think.
