### ISSUE TITLE
UI Shell - Chevron in wrong direction

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/carbon-design-kit#219]
In Carbon Design Kit - Grey 10 theme, the component "ui shell/left panel/item/sub-menu/01 parent/01 open", the chevron is pointing down and should be pointing up.

I checked today and synched the library through Cloud. 

Thanks!

**Comment by aagonzales** [comment]
Fixed! Available with the next kit update
v10.8 release notes
