### ISSUE TITLE
Megan Baxter

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon-design-kit#22]
## Overview
Over the next sprint, as you are using the beta design kit + library sketch file, please document any bugs, frustrations, feedback, issues, etc. you have while using the kit. The items below list put a few of the things to keep an eye out for

- Misspellings (layers, components, placeholder text, symbols)
- Missing symbols
- Components not resizing properly or components that are not resizing at all
- Instances where you had to detach from the symbol because you needed to make a change that was not offered in the overrides panel
- Icon symbols not easily swapping out (getting resized weirdly)
- Shape/text/icon not aligned to the pixel grid or not sized to a whole pixel
- Inconsistent symbol handling (naming) and build structure (layer order)
- A whole component is not as granular (built out of smaller component units) as it could be

**Comment by crirox** [comment]
Hey, I've noticed this one error to a button not matching the container background and text going on two lines.
<img width="488" alt="skaermbillede 2017-12-04 kl 15 25 51" src="https://user-images.githubusercontent.com/15385207/33557598-ffb2aa38-d907-11e7-98e3-f6cf95dd8b26.png">
