### ISSUE TITLE
Vertical progress indicator: Broken responsiveness [sketch 58]

### ISSUE THREAD

**Issue by ShaunLynch** [carbon-design-system/carbon-design-kit#221]
## Detailed description

When I attempt to resize the component the pinning does not work and ruins it's intended composition.

![image](https://user-images.githubusercontent.com/35451841/67376254-ba7c4680-f57b-11e9-93df-24fb5de1a503.png)

> What version of the Carbon Design System Kit are you using?

Gray 10 / Sketch library up to date

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Progress indicator/vertical/pieces

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the title not to reposition once I make the component taller.

Bonus: Would be great to have the following things also

- Multi-line titles
- Guidance on intended minimum space between on step to the next

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Blockchain

No pressing release dates to be concerened about

## Steps to reproduce the issue

1. Place Vertical progress indicator sketch symbol
2. Attempt resize

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed vertical progress indicator. 🎉

The steps in a progress indicator should all be the same height. The height will be determined by the tallest section. You have control to do this if you use the `items` in the kit, but the `group` is a little trickier to make consistent if there are different lengths of titles/optional text.
