### ISSUE TITLE
UI shell header: Overlapping Titles 

### ISSUE THREAD

**Issue by smunoz1010** [carbon-design-system/carbon-design-kit#223]
I’m having a UI shell header symbol issue after the latest library update in sketch. I am using Carbon X. The exact symbol is “ui shell / header / group / base + nav + actions”. The titles in my nav are now overlapping. I would like for the spacing to return between [Name] and the first link so they are not overlapping.

Here are the steps I took to reproduce this issue in Sketch:

1. Click insert 
2. Choose Carbon Design System (White Theme)
3. Choose ui shell / header / group / base + nav + actions
4.  Enter override for [Name]
5. Enter override for Link 1
<img width="510" alt="overlapping nav" src="https://user-images.githubusercontent.com/57410038/68230350-79922200-ffbe-11e9-9c82-c8d1e78a466a.png">
<img width="476" alt="original nav" src="https://user-images.githubusercontent.com/57410038/68230352-7a2ab880-ffbe-11e9-9fa6-d5ee9322e4a1.png">

**Comment by aagonzales** [comment]
(duplicate issue) https://github.com/carbon-design-system/carbon-design-kit/issues/226#issuecomment-553534490
Fixed! Available in next kit update
