### ISSUE TITLE
Artboards should use background shapes with layer styles instead of artboard background

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#224]
## Detailed description

In the Sketch docs, the Artboards use the 'Artboard' background instead of a shape layer with an assigned style. It would be better/more clear if a locked background layer with an assigned style was used instead. It would not only be easier to understand which token is being used for the background, but it would also be easier to change if the user wished to experiment with other colors. 

> What version of the Carbon Design System Kit are you using?

Latest at time of writing. 
> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

All artboards.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to see a background shape used with an assigned Style to see what token is in use and to be able to adjust it if desired.

## Steps to reproduce the issue

1. Open a carbon Sketch Theme
2. Check any artboard.
3. Notice that the background color is set in the Artboard settings and not as a background shape on the artboard which would be more intuitive and useful.

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

Library

**Comment by laurenmrice** [comment]
Fixed in all themes. Will be in next update
