### ISSUE TITLE
incorrect rendering of data table tool&action bars...

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#225]
I can't determine what the actual problems is, but see the attached grabs of the rendering for the datatable toolbar and action bar.  The visual seems to extend beyond the actual container;

![image](https://user-images.githubusercontent.com/51379566/68408632-b6435200-0153-11ea-805c-a25b9f1b493e.png)
![image](https://user-images.githubusercontent.com/51379566/68408651-be9b8d00-0153-11ea-9de4-e24c03f181d5.png)
 
White theme

**Comment by marceltrautmann** [comment]
Any update here?  I'm finding it hard to move forward with this in the way since it's hard to lay the page foundation.

**Comment by lukefirth** [comment]
+1 on this, we've got a pretty table centric set of offerings and are experiencing the exact same looking problem with the grey 10 theme

Affecting symbols I'd already placed:
![image](https://user-images.githubusercontent.com/30671949/68881028-46f5d100-0704-11ea-9470-176f63b2a202.png)

And the brand new ones I place have the same extending and overlapping problems @marceltrautmann s show above.

**Comment by marceltrautmann** [comment]
Is there a process to get this prioritized?  Can someone confirm that it's at least in the Q?

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed in all kits ! This fix may set your text to default so you might have to override it again.
