### ISSUE TITLE
UI Shell, Tool Tip and Dropdown bugs in latest Sketch library updates

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#226]
## Detailed description

Unfortunately I have no time to check it in more detail, so I'm sure I missed some things, but I noticed several broken things in the latest update (due to smart layout I'm guessing).

Ui shell  - Many header texts overlapping/messed up
https://snipboard.io/UdKlhj.jpg
Tool Tip - buttons misaligned
https://snipboard.io/cIgkQV.jpg
Drop down - Several items now have a | symbol
https://snipboard.io/ewiKvS.jpg

> What version of the Carbon Design System Kit are you using?

Latest via sketch library update, but downloaded from sketch cloud.

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.
Bug, Libraries

**Comment by aagonzales** [comment]
UI Shell is fixed! (thanks to some help from Mariusz)

![image](https://user-images.githubusercontent.com/11670886/68791868-cc4b8980-060f-11ea-9caf-accd1a17b7e0.png)

**Comment by aagonzales** [comment]
- tooltip button is fixed! It was missing its smart-layout settings
- dropdown style fixed! Its overrides were messed up.

**Comment by aagonzales** [comment]
All fixed and available in the kit update. 
Add to v10.8 release notes
