### ISSUE TITLE
Incorrect Tabs Spacer

### ISSUE THREAD

**Issue by rgblee** [carbon-design-system/carbon-design-kit#228]
The spacer on the right side of the tabs in the sketch symbol library shows spacing-09. But on the carbon system page it shows spacing-05. I was expecting it to be spacing-05.

This problem resides in the Carbon Design sketch library for Gray 10. I don't know if it exists in other themes.

I work on Cloud Pak for Data. December deadline.

**Comment by aagonzales** [comment]
Confirmed, tabs symbol is still using the told spacing token. Needs to be updated to `spacing-05`

**Comment by laurenmrice** [comment]
fixed! will be in next kit update
