### ISSUE TITLE
Dropdown > Multi-select > Interactive tag regression

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-design-kit#229]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

> What did you expect to happen? What happened instead? What would you like to see changed?

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by lnajjar** [comment]
There appears to be a regression with the Carbon Design System Sketch library for Dropdown > Pieces > Multi-select. All the multi-select values in my design changed to "2." Will you please fix this error?

![image](https://user-images.githubusercontent.com/12902530/68886950-bad0b300-06dd-11ea-8623-68638dc676a4.png)

**Comment by aagonzales** [comment]
@lnajjar Unfortunately, I think this is an outcome of updating the symbol and Sketch automatically resetting the overrides. I am unaware of a way to fix this regression problem you are having, if you know of a way to correct this in Sketch we would appreciate your help.
