### ISSUE TITLE
Error in dropdown component

### ISSUE THREAD

**Issue by DianaStanciulescu** [carbon-design-system/carbon-design-kit#232]
In the Carbon design kit, dropdown section, symbols "dropdown / 03 multi-select / 01 label / open / 01 enabled" and "dropdown / 03 multi-select / 02 no label / open / 01 enabled" and "dropdown / 03 multi-select / 03 inline / open / 01 enabled" , the dropdown shows the chip with 2x showing that some options are selected even though no option is selected. 

There should be no chip here, and these components should show the version when nothing is selected,  the component that shows selected filters is already presented below this one. 

This is a screenshot of what I mean. The :"filters are selected" text should also be replaced or removed.

![Screenshot 2019-11-19 at 13 39 51](https://user-images.githubusercontent.com/51086727/69143682-382b6780-0ad2-11ea-93f9-69c311d9294e.png)

**Comment by DianaStanciulescu** [comment]
Not sure if it was resolved.

**Comment by laurenmrice** [comment]
Thanks Diana! Will start getting this fixed per theme.
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme
