### ISSUE TITLE
Cannot resize height of Data table Title (w/ desc) symbol

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#235]
When needing an addition line of text in the **Data table Title with description** symbol I discovered that I cannot rease the height of the BG element

![image](https://user-images.githubusercontent.com/51379566/69245178-5cd81b80-0b74-11ea-805f-eaa2d776205a.png)
 
I believe this is because the background rectangle is set to "fixed size"
![image](https://user-images.githubusercontent.com/51379566/69245310-96a92200-0b74-11ea-8fb0-5cc47364b9c3.png)

**Comment by marceltrautmann** [comment]
mine is grey-10 kit, but assume it might be throughout

**Comment by laurenmrice** [comment]
Can you send your usecase for this ? We currently have the symbols set up so that it is fixed (purposefully) so you can not resize in height.

**Comment by marceltrautmann** [comment]
As you can see in the attached, my description goes to three lines, yet when I increase the container to encompass this the BG doesn't expand...

![image](https://user-images.githubusercontent.com/51379566/69373353-9b073500-0c71-11ea-9d38-f787472892a3.png)

**Comment by laurenmrice** [comment]
fixed in next update
