### ISSUE TITLE
Slider component needs spacing adjusted

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#236]
as the title suggests, the spacing in the slider component is alittle off.  see example below, right side is a typical form field, left is the slider.

grey-10

![image](https://user-images.githubusercontent.com/51379566/69246228-564aa380-0b76-11ea-93ae-90d18960978c.png)

**Comment by marceltrautmann** [comment]
unsure the intent, but might also wanna tweak the centering of the number value in the field (currently set to 0)

**Comment by laurenmrice** [comment]
Fixed in:

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Available in next update

**Comment by marceltrautmann** [comment]
I'm not sure that numeric text is set to center in the box

![image](https://user-images.githubusercontent.com/51379566/69376260-f805e980-0c77-11ea-9b91-54539035dbfe.png)

I'm gonna assume you wanna change the justifcation to center

![image](https://user-images.githubusercontent.com/51379566/69376391-33081d00-0c78-11ea-992b-79333e654a29.png)
