### ISSUE TITLE
Radio button spacing expands as label text is entered

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#237]
Grey-10 / radio button / group / horizontal / 3 entries

As I enter label text, the horizontal spacing increases between the three radio elements

![image](https://user-images.githubusercontent.com/51379566/69343917-7e043f00-0c3c-11ea-8833-7272271c5699.png)

**Comment by laurenmrice** [comment]
I am unable to recreate this bug using the gray 10 theme. make sure your kits are up to date. Would you mind sending a giph/video of what is happening?

**Comment by marceltrautmann** [comment]
screen recording in the zip
![image](https://user-images.githubusercontent.com/51379566/69359717-160f2200-0c57-11ea-9d90-78221862644d.png)
![image](https://user-images.githubusercontent.com/51379566/69359731-1dcec680-0c57-11ea-894c-332501a10a77.png)

[Screen Recording 2019-11-21 at 12.02.51 PM.mov.zip](https://github.com/carbon-design-system/carbon-design-kit/files/3875863/Screen.Recording.2019-11-21.at.12.02.51.PM.mov.zip)

**Comment by laurenmrice** [comment]
Fixed in:

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme
