### ISSUE TITLE
Regression errors on radio buttons

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-design-kit#238]
## Detailed description

The Carbon Design System Sketch kit updates this week caused regression errors with radio buttons. 

> What version of the Carbon Design System Kit are you using?
Latest update

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Sketch > Insert > Carbon Design System (White theme) > radio button > item > 01 unselected

> What did you expect to happen? What happened instead? What would you like to see changed?
When I change the radio button "Item label," I expect the radio button on the canvas to match the change. It actually shows a totally different name from what I entered. Bizarrely, the totally different name is from another radio button in my user interface.

![image](https://user-images.githubusercontent.com/12902530/69378492-1bc73080-0c74-11ea-8756-9ace5a85ef7f.png)

![image](https://user-images.githubusercontent.com/12902530/69378539-2d103d00-0c74-11ea-8155-54d7ed943602.png)

Also, the item labels for some radio buttons in my user interface before the Carbon Design System Sketch Kit also changed.

![image](https://user-images.githubusercontent.com/12902530/69381974-9f385000-0c7b-11ea-8e92-d9595bd6f89f.png)
 
When I double-click on these original radio button labels, they temporarily display the original label.

![image](https://user-images.githubusercontent.com/12902530/69382033-c727b380-0c7b-11ea-867c-50dc24b2346c.png)

When I click off, the radio button item labels revert their bizarre labels.

It seems to me that this bizarre behavior is similar to the behavior described for text input fields in Issue 230: [https://github.com/carbon-design-system/carbon-design-kit/issues/230](url)

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by aagonzales** [comment]
@lnajjar are you still having this problem? I am not able to reproduce this problem and I'm not quite sure what is causing this unless is some sort of Sketch bug. "Using another statistic" isn't in the library symbol so I'm not sure why its pulling that in instead of the override.
