### ISSUE TITLE
IBM V2 Sketch Doc has incorrect orange

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#239]
## Detailed description

It's FC7B1E instead of FF832B. 

> What version of the Carbon Design System Kit are you using?

Latest downloaded V2 IBM Language doc from Sketch Cloud.

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Orange style

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected it to be FF832B. It's FC7B1E.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

Yes, should be FF832B

## Steps to reproduce the issue

1. Download and open the V2 language doc.
2. Check 'orange' style
3. It's incorrect.

## Additional information
Screenshot:
https://snipboard.io/AficGh.jpg

## Add labels
tybe:bug, kit:sketch

**Comment by aagonzales** [comment]
Confirmed, it should be #ff832b. Will get this updated.

**Comment by laurenmrice** [comment]
Fixed and will be in the next update 👍🏻
