### ISSUE TITLE
No text style assigned in UI Header l2 menu item

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#241]
## Detailed description

There is no text style assigned to ui shell / header / item / sub-menu / 02 child / 01 enabled
L2 Menu Item. Color is #BEBEBE.

Not sure if this is a mistake and should be a v2 color.

> What version of the Carbon Design System Kit are you using?

Latest. Grey 10 Theme.

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Symbols Page
 ui shell / header / item / sub-menu / 02 child / 01 enabled
L2 Menu Item

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to see a text style assigned to the text. 

## Steps to reproduce the issue

1. Open grey 10 theme
2. Go to ui shell / header / item / sub-menu / 02 child / 01 enabled
3. Check the text for L2 menu item
4. No text style is aligned.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
libraries, bug

**Comment by laurenmrice** [comment]
Fixed in next updates! 🎉
