### ISSUE TITLE
Radio and/or checkbox pattern misalignment

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#242]
I just happened to be swapping a radio pattern with a checkbox pattern and happened to notice that one has a misalignment when stacked from the top left corner (I assume the checkbox as it's label is 1 pixel in).

Grey-10/checkbox/group 5

![image](https://user-images.githubusercontent.com/51379566/69744145-a04efe80-110d-11ea-8335-fa0bc72f33ff.png)

**Comment by marceltrautmann** [comment]
This is the result after nudging the checkbox labels 2 pixel left

![image](https://user-images.githubusercontent.com/51379566/69744708-b8734d80-110e-11ea-9703-1e74d8f89d5b.png)

**Comment by marceltrautmann** [comment]
keep alive

**Comment by marceltrautmann** [comment]
keep alive

**Comment by marceltrautmann** [comment]
anyone confirm this has been seen?

**Comment by designertyler** [comment]
Thanks!

I'm seeing the 2px nudge, too.

It's happening in checkbox / group / 1 - 5 in all themes.

**Comment by laurenmrice** [comment]
on it!

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed! 🎉 available now
