### ISSUE TITLE
Text on inline loading has additional tracking (Sketch kit)

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon-design-kit#243]
The type here in the inline loading component has more space between letters than it should (should just be default tracking for plex). Looks like this is just in the sketch kit 

EDIT: Also, the carbon guideline lists 14px type, yet the sketch kit component is 12px

<img width="813" alt="Screen Shot 2019-11-22 at 2 23 31 PM" src="https://user-images.githubusercontent.com/47458576/69457988-f3067000-0d33-11ea-8865-92b377245f50.png">

**Comment by laurenmrice** [comment]
thanks Pete, yeah the kit was using `label-01`at 12px. So we should be using the `body-short-01` instead at 14px?

**Comment by peter-garvin** [comment]
Does the label-01 have extra space between letters?

**Comment by peter-garvin** [comment]
Oh to answer your question label vs body-short – I'm not sure which one is correct, but the carbon page shows it as body-short

**Comment by laurenmrice** [comment]
hey petttte . The code is using the wrong tracking and is not using our type token. I'm going to make a component issue for that and close this kit one since its a code bug

**Comment by laurenmrice** [comment]
Fixed in code: https://github.com/carbon-design-system/carbon/pull/5172
