### ISSUE TITLE
Changelogs in sketch should include a version number with each sketch library update

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#245]
## Detailed description

The cover pages don't have version number information for the libraries. When using the themes locally this means keeping track of things by manually. It would be great if the changelog page listed the Sketch theme version number with each sketch file update.

> What version of the Carbon Design System Kit are you using?

Dunno :) Latest

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Cover Page

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect to see info about the Theme file version number. 

## Steps to reproduce the issue

1. Open a Carbon theme in sketch. 
2. Check cover page.
3. It's 10.5.0 for months now despite having been updated with fixes

## Add labels
Request

**Comment by laurenmrice** [comment]
We have updated this to the current version. We usually are up to date with this but got behind because of other pressing priorities at the end of last year. 👍🏻
