### ISSUE TITLE
Inline dropdown sketch component open state inconsistency

### ISSUE THREAD

**Issue by sph2116** [carbon-design-system/carbon-design-kit#247]
## Detailed description

The Down chevron in the inline dropdown sketch component when in the Open state does not turn 180 degrees to become an Up chevron

> What version of the Carbon Design System Kit are you using?
Carbon v10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Page: Dropdown
Artboard: Dropdown - White theme
Layer/symbol: component/dropdown / 01 default / 03 inline / open

> What did you expect to happen? What happened instead? What would you like to see changed?
When the dropdown element is opened, the chevron should point up to match the regular dropdown

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Yes, the inline dropdown is shown with the Up Chevron when in the open state here: https://www.carbondesignsystem.com/components/dropdown/style

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
zOSMF

## Steps to reproduce the issue

1. Place the dropdown / 01 default / 03 inline / open component and observe the chevron positioning

## Additional information
The chevron in the Inline dropdown component (left) is supposed to turn 180 degrees when it's open like the regular dropdown (right). In the Sketch symbol, it is always pointing down whether it is open or closed
![Screen Shot 2019-12-09 at 4 51 41 PM](https://user-images.githubusercontent.com/31591569/70540417-38e47600-1b33-11ea-8067-e2623118feca.png)

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

`libraries`

**Comment by laurenmrice** [comment]
Fixed with the next update 🎉
