### ISSUE TITLE
Open Inline dropdown responsiveness  / Sketch Kit file

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/carbon-design-kit#248]
## In the Inline dropdown chevron position seams to be fixed too far from the right edge of the symbol. When expanded the chevron wouldn't 'stick' to the right edge as expected. 

> What version of the Carbon Design System Kit are you using?
Carbon v10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Symbol: Dropdown / Default / Inline / Open 
Noticed in the Gray 10 theme 

> What did you expect to happen? What happened instead? What would you like to see changed?
When longer copy is entered and dropdown expanded to accommodate it the chevron should stick to the right edge of the symbol 

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
The code works fine. The symbol is not consistent with the component

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
No pressing ship

## Additional information

* Screenshots or Sketch file links
![image](https://user-images.githubusercontent.com/24441071/70642436-322a3180-1c0d-11ea-8907-4464facd4940.png)

* Notes
Thanks! You guys are doing a great job. Enjoying working with the kit and it's getting better with every new release.

**Comment by laurenmrice** [comment]
thanks for making this issue ! fixed ! 🎉 available in next kit update
