### ISSUE TITLE
[Dropdown multi-select]: Incorrect spacing in Sketch kit

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-design-kit#249]
The code and website place the tag 16px ($spacing-05) from the left.
![image](https://user-images.githubusercontent.com/19270502/71016773-43ff4f00-20bb-11ea-9dc3-f977f2d70a76.png)

The kit is showing the tag 8px from the left. It looks like it happens in all 4 themes in dropdown>multi-select

![image](https://user-images.githubusercontent.com/19270502/71016379-b15eb000-20ba-11ea-8d34-5995cb6a4a25.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme
