### ISSUE TITLE
label–01 is using different color in sketch library than specified on carbon page

### ISSUE THREAD

**Issue by ldohle** [carbon-design-system/carbon-design-kit#253]
## Title line template:

Label is using different color in sketch library than specified on carbon page

## Detailed description

> What version of the Carbon Design System Kit are you using?

Carbon Design Kit 10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Carbon X text styles, Carbon Design System (grey 10), the label-01 (text-02)

> What did you expect to happen? What happened instead? What would you like to see changed?

In the Carbon X text styles, Carbon Design System (grey 10), the label-01 (text-02) text style is #525252, but according to the Carbon page should be #393939. This affects all components using lables, like dropdowns etc.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

Discrepancy between carbon page and design kit

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM TRIRIGA, next release for TRIRIGA Building Insights by then end of Jan

## Steps to reproduce the issue

1. Link a sketch file with the Carbon Design Kit (grey 10) sketch library
2. Select text style label-01
3. Check the color.
4. Compare to color specified on carbon page for label-01 text-02

**Comment by laurenmrice** [comment]
Thanks for opening this, I see that it is inconsistent between the kit and the website. We are currently reevaluating the hex colors of text-02 and text-03. I will keep this open until we come to a final decision :)

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
`label-01` in the sketch kit will reflect the correct `text-02` color. The website needs to be updated to reflect these hex value changes. I opened an issue here to resolve it https://github.com/carbon-design-system/carbon-website/issues/1368

**Comment by laurenmrice** [comment]
fixed! it is correct on the website and the kit now
