### ISSUE TITLE
body-short-01 is using different colour in sketch library than specified on carbon page

### ISSUE THREAD

**Issue by ldohle** [carbon-design-system/carbon-design-kit#254]
## Title line template:

Label is using different colour in sketch library than specified on carbon page

## Detailed description

> What version of the Carbon Design System Kit are you using?

Carbon Design Kit 10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Carbon X text styles, Carbon Design System (grey 10 and white theme), the body-short-01 (text-03)

> What did you expect to happen? What happened instead? What would you like to see changed?

In the Carbon X text styles, Carbon Design System (grey 10 and white theme), the body-short-01 (text-03) text style is #8d8d8d, but according to the Carbon page should be #a8a8a8. 

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

Discrepancy between carbon page and design kit

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM TRIRIGA, next release for TRIRIGA Building Insights by then end of Jan

## Steps to reproduce the issue

1. Link a sketch file with the Carbon Design Kit (grey 10 or white theme) sketch library
2. Select text style body-short-01 text-03.
3. Check the colour.
4. Compare to colour specified on carbon page for text-03.

**Comment by laurenmrice** [comment]
Thanks for opening this issue! Our most up to date kits and website have the correct values for body-long-01 text-03 (gray 40, #a8a8a8) . Check to see if you have any updates that need to be installed.
