### ISSUE TITLE
[wireframe kit] Consider creating a low fi kit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#261]
Various teams have expressed that it would be useful to have access to a carbon kit that was low fidelity. They say that sometimes when they show concepts or express ideas in our high fi kits that people get bogged down in the visual details. A wireframing kit would help avoid these issues.

---------------------------------------------------------------------------------------------------

Here is feedback so far from designers around this topic:
<img width="375" alt="Screen Shot 2020-01-14 at 11 45 50 AM" src="https://user-images.githubusercontent.com/43969356/72368314-7359a980-36c3-11ea-88e9-514f5c4fbab6.png">
<img width="375" alt="Screen Shot 2020-01-14 at 11 45 57 AM" src="https://user-images.githubusercontent.com/43969356/72368316-75bc0380-36c3-11ea-8082-e9879a6b996d.png">

---------------------------------------------------------------------------------------------------
![Screen Shot 2020-01-23 at 4 41 07 PM](https://user-images.githubusercontent.com/43969356/73030408-339b6c00-3dff-11ea-96cc-e1e91cce0336.png)

**Comment by laurenmrice** [comment]
<img width="964" alt="Screen Shot 2020-01-14 at 11 44 59 AM" src="https://user-images.githubusercontent.com/43969356/72368332-80769880-36c3-11ea-963e-48299dcdc78b.png">

**Comment by laurenmrice** [comment]
<img width="1008" alt="Screen Shot 2020-01-14 at 11 44 47 AM" src="https://user-images.githubusercontent.com/43969356/72368348-840a1f80-36c3-11ea-981a-a35c308874d5.png">

**Comment by laurenmrice** [comment]
Mark Marrara  may be a good contact for this as he is trying to find ways to help designers create more wireframes and lo fis during the design process

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
not stale

**Comment by designertyler** [comment]
More feedback from the community
![image](https://user-images.githubusercontent.com/19270502/90264063-2afb9900-de16-11ea-9dcd-8778169996e2.png)


We have simplified versions of the components in the thumbnails of the component overview page. Could this be a starting point?
![image](https://user-images.githubusercontent.com/19270502/90264154-4797d100-de16-11ea-8869-c3e8f10d7843.png)



Here's an example I found of an extremely low fi sketch kit. I don't know if we want to go this far, but it's nice to see as a comparison. 

https://www.dominikgorecki.com/2013/06/sketch-wireframe-kit/

**Comment by dansilveira-ux** [comment]
Following up on this to see if this is something that is getting worked on or I can help contribute to build.

**Comment by TheresaDRamsey** [comment]
We need low-fi!  Ideally a low-fi that easily converts to higher fi. Skipping straight to hi-fi, which is the path many designers take now with Carbon, means that we aren't often aren't ensuring the design concept works. Clients comment on details, not the big picture. Clients can help us rearrange chairs on the Titantic, it's still going to sink. 

I'd love to see something actually pencil sketch like.  Then just change the theme and it becomes hi-fi.

**Comment by TheresaDRamsey** [comment]
not stale...still very much needed

**Comment by dansilveira-ux** [comment]
I am currently working on a Mid-Fi Carbon kit, if you are interested in testing it out let me know!

**Comment by TheresaDRamsey** [comment]
not stale, still needed.

**Comment by laurenmrice** [comment]
Thank you everyone for your responses! We still have not made a wireframe kit yet but someone did share a sketch plugin that transforms your hi-fi designs into wireframes and it uses IBM Plex. https://ibm.ent.box.com/s/26nhkeeinsuz5hxzx6l1gwygy0cm0855

**Comment by dansilveira-ux** [comment]
Currently finishing up a low-fi carbon kit that will be released soon on the Carbon site. Let me know if you have any questions. Thanks.

**Comment by dansilveira-ux** [comment]
Remain open, this is being worked on.
