### ISSUE TITLE
[Tab] change padding-right to 16px

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#262]
The padding of tabs has been changed to be 16px instead of 64px to allow for more room for type. Need to update to reflect code.

![image](https://user-images.githubusercontent.com/11670886/72380419-f9351f00-36da-11ea-9869-a44b9d54a59f.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed! will be in next kit update
