### ISSUE TITLE
[Pagination] Off-center numbers in white theme

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-design-kit#265]
The numbers in the white theme Pagination / standalone / group symbol are left-aligned in their box
![image](https://user-images.githubusercontent.com/19270502/72623113-26b3df80-390a-11ea-9bfd-7add22c256e9.png)

when the other themes are centered:

![image](https://user-images.githubusercontent.com/19270502/72623143-33d0ce80-390a-11ea-94e5-38d25881bed0.png)

This causes the selected indicator to look off when compared to the other themes. 

![image](https://user-images.githubusercontent.com/19270502/72623011-f10ef680-3909-11ea-8db9-2fbedf25ce27.png)

This also occurs in the Pagination / standalone / group / overflow symbol

![image](https://user-images.githubusercontent.com/19270502/72623512-de48f180-390a-11ea-9e9d-f47ec809d8eb.png)

**Comment by laurenmrice** [comment]
fixed ! will be in next update 🎉
