### ISSUE TITLE
[Icon kit] icon color styles showing up in overrides panel

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#268]
Was wondering if this bug is coming from the plugin.

When we try to lock color styles of an icon that sits within a component symbol, it still shows up as options in the overrides panel. Locking layers in the symbol should hide it from showing up in the overrides panel and for some reason I believe this is only happening with the icons from the new libraries.

Ex:
![Screen Shot 2020-01-17 at 2 17 32 PM](https://user-images.githubusercontent.com/43969356/72643452-54158300-3934-11ea-8ad9-c173f67be435.png)

**Comment by laurenmrice** [comment]
Test I did between using old IDL icons compared with our new IDL icons. Notice the structure of how they appear in the panel of the symbol

Old icons:
![Screen Shot 2020-01-17 at 3 23 01 PM](https://user-images.githubusercontent.com/43969356/72647119-5fb97780-393d-11ea-89fd-f35587415956.png)


New icons:
- We may need to include seperate color style options inside the icon 
![Screen Shot 2020-01-17 at 3 23 08 PM](https://user-images.githubusercontent.com/43969356/72647130-6516c200-393d-11ea-943e-76543624f761.png)

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
This has been fixed in code, just waiting to close once we publish the actual library. 👍🏻

**Comment by mariuszmickiewicz** [comment]
This can be solved in many cases not by only turning off the overrides themselves, but by turning off the "Allow overrides" completely.
