### ISSUE TITLE
[Icon kit] Missing an icon in Design Kit

### ISSUE THREAD

**Issue by skwon14** [carbon-design-system/carbon-design-kit#269]
Missing 'Container software' icon in design kit. 

<img width="250" alt="Screen Shot 2020-01-17 at 2 13 36 PM" src="https://user-images.githubusercontent.com/48769110/72644349-c9865100-393e-11ea-8a24-df410401671b.png">

**Comment by laurenmrice** [comment]
added ! 🎉 will be in next update
