### ISSUE TITLE
Tooltip arrows are inconsistent between themes

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon-design-kit#272]
Light and dark theme arrows are different sizes and angles on light theme vs dark theme. Dont know what the proper spec should be 

![Screen Shot 2020-01-23 at 10 57 33 AM](https://user-images.githubusercontent.com/47458576/73005999-83623f00-3dcf-11ea-96f2-d6e57e70ac8b.png)

**Comment by peter-garvin** [comment]
in image above: 
1st - light theme tooltip
2nd - dark theme tooltip
3rd - dark theme tooltip overlayed on top of light theme

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed ! will be available in next update ! 🎉
