### ISSUE TITLE
incorrect type spec for text input and text area

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon-design-kit#273]
Text input and text area are using body-short in the sketch kit, but the spec on carbon calls for body-long

https://www.carbondesignsystem.com/components/text-input/style

**Comment by laurenmrice** [comment]
Text input should be `body-short-01`. Text area should be `body-long-01`. This one is not right in the kits. I think we should add another row to the style table on the website to include the difference between text input and text area so its more clear. I will make a separate issue for that.

Going to change the text area to `body-long-01` in kits:
- [ ] White theme
- [ ] Gray 10 theme 
- [ ] Gray 90 theme 
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
in all kits. will be in next update! 👍🏻
