### ISSUE TITLE
No text-03 option for body-long text styles

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon-design-kit#274]
Body-long-01 and body-long-02 do not have a text-03 and disabled-02 style. The use case for this is placeholder text in text input and text area

https://www.carbondesignsystem.com/components/text-input/style

related: #273

**Comment by aagonzales** [comment]
- [ ] G100
- [ ] G90
- [ ] G10
- [ ] White

**Comment by laurenmrice** [comment]
Added! should be available now
