### ISSUE TITLE
[Icon kit] 20px checkmark icon does not appear

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon-design-kit#275]
Other checkmark icons work, but the 20px variant is not showing up in the kit

<img width="1064" alt="Screen Shot 2020-01-27 at 5 04 05 PM" src="https://user-images.githubusercontent.com/47458576/73221868-8a6ab380-4127-11ea-8e92-913f41a228ce.png">

**Comment by laurenmrice** [comment]
not stale

**Comment by laurenmrice** [comment]
fixed ! will be in next update of the library
<img width="1018" alt="Screen Shot 2020-03-30 at 10 10 23 AM" src="https://user-images.githubusercontent.com/43969356/77928931-ad702b80-726e-11ea-9863-c075cc9d2e05.png">
