### ISSUE TITLE
Search: incorrect states

### ISSUE THREAD

**Issue by peter-garvin** [carbon-design-system/carbon-design-kit#277]
In code, the placeholder text remains visible until the user starts typing. The sketch kit does not include the placeholder text on this state

<img width="1152" alt="Screen Shot 2020-01-29 at 12 02 56 PM" src="https://user-images.githubusercontent.com/47458576/73383725-8063c480-428f-11ea-91dd-d36f7c64791c.png">
<img width="740" alt="Screen Shot 2020-01-29 at 12 03 34 PM" src="https://user-images.githubusercontent.com/47458576/73383726-8194f180-428f-11ea-91e8-a3c7b45f26f9.png">

**Comment by peter-garvin** [comment]
Also, the disabled state has an active icon
<img width="705" alt="Screen Shot 2020-01-29 at 12 30 56 PM" src="https://user-images.githubusercontent.com/47458576/73385728-4399cc80-4293-11ea-8b62-95087313a8ea.png">

**Comment by laurenmrice** [comment]
- yes the placeholder text should still be visible until something has actually been typed. 
- that disabled state is wrong.

will update in the kits!
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Will be available in next update!

The disabled icon is correct in our master file for the gray 10 theme. But I did add it to the override panel so you can change the color on your end. I think this is a sketch problem.

**Comment by peter-garvin** [comment]
@laurenmrice sorry I didnt realize this before, but could you double check the search icon color? on carbon site its listed as icon-01 but on gray 10 kit it is icon-02

**Comment by laurenmrice** [comment]
hey petttte. good catch. we should be using the icon-02, so that is a bug in code and needs to be updated on the website. I will make as issue for that 👍🏻

**Comment by laurenmrice** [comment]
Fixed in code: https://github.com/carbon-design-system/carbon/pull/5222#event-2995381534
