### ISSUE TITLE
[Time picker] Add states to time picker in Sketch kit

### ISSUE THREAD

**Issue by kylearichard** [carbon-design-system/carbon-design-kit#278]
## Enhancement: add states to `time picker` in Sketch kit

In the current design kit (latest version as of today, 01/29/20), the `time picker` component only includes enabled and skeleton states, shown below. 

<img width="337" alt="Screen Shot 2020-01-29 at 2 06 12 PM" src="https://user-images.githubusercontent.com/59894790/73401710-844c1280-42a0-11ea-87e2-f5c70c974eef.png">

Ideally, there would also be states to show the following for the text input area:

- [ ] Disabled
- [ ] Focus
- [ ] Filled

And separate states for each of the two dropdowns to show the following:

- [ ] Open, 2 options
- [ ] Open, 3 options
- [ ] Selected

Since the component is not built out of the sub-components used in its implementation (namely, a text input field and two dropdowns), even detaching the symbol does not provide us with the level of control found in other components of the kit. It'd be great to be able to independently toggle the various states of each sub-component, similarly to what's available in the `form` and `modal` components, where we can change states of buttons, fields, etc. using the overrides from the master component.

**Comment by laurenmrice** [comment]
Yes, I think we need to add the disabled, focus, filled state as well as an open state you can control the length of and a open selected. I will match this similarly to the structure of what we do for our select component.

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Added to all kits, will be available in next update
