### ISSUE TITLE
[Date picker] Numbers jump in different states

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-design-kit#281]
Some of the different states for each individual calendar day jump down 1px.
* Hover
* Focus
* Selected
* End range
* In range

One of the numbers also isn't center aligned
* Next month

**Request**
Can we add in a disabled state as well?
Use case example: If the calendar only allows to select current or past days, but not future dates. 

You can see all examples below:
<img width="763" alt="Screen Shot 2020-02-04 at 2 59 11 PM" src="https://user-images.githubusercontent.com/43549567/73783742-35035780-4762-11ea-8bb2-2d8c8311f351.png">

This was tested on the **White theme** but I would check the others as well!

**Comment by laurenmrice** [comment]
Going to fix these numbers and add a disabled state 👍🏻

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed ! will be available in next update 🙌🏻
