### ISSUE TITLE
Dropdown Combobox clear element missing...

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#282]
confirmed in white & gray10 themes...

Dropdown/combobox/label&nolabel/**new selection.**

Per the CDS site this pattern should include an X to clear the selection

![image](https://user-images.githubusercontent.com/51379566/74167878-ebe65400-4bf6-11ea-85ce-87597f800ef4.png)

However in the kit it does not

![image](https://user-images.githubusercontent.com/51379566/74168012-1afcc580-4bf7-11ea-9041-4c3217bd605a.png)

**Comment by laurenmrice** [comment]
In code, I think we need to change this to not have the close icon visibly shown if you are no longer clicked on the dropdown and are active in another part of the page. Discussion here for enhancement: https://github.com/carbon-design-system/carbon/issues/4992

We have it present in the kit when the dropdown is open and is being interacted with. It also should be present if you are in the middle of typing something.

**Comment by marceltrautmann** [comment]
but if it's not visible when working on another part of the page the user won't have any clue that they can dismiss it.  Isn't that bad?
