### ISSUE TITLE
Usage examples?

### ISSUE THREAD

**Issue by veeral-patel** [carbon-design-system/carbon-design-kit#285]
Hi, thanks for this great library!

Are there any screenshots of UIs that utilize Carbon, or even better, web apps that use Carbon, that I can check out?

Happy to sign up for whatever IBM products I need to (but would prefer not to do so if possible!)

I'd like to learn how Carbon was designed to be used in real UIs.

**Comment by josh-tt** [comment]
I would also love to see more examples (with live links) beyond what is up on the IBM Design Language site here: https://www.ibm.com/design/language/gallery/

**Comment by laurenmrice** [comment]
IBM Cloud will be updating parts of their ui tomorrow with the implementation of Carbon v10. You don't need to signup to view the catalog, but to view other sections you may need a login.

Carbon is planning on adding a gallery page to our site with UI examples using v10, but for now you can still view the link that Josh referenced^. There are some ui examples showing grid usage here https://www.carbondesignsystem.com/guidelines/2x-grid/implementation

**Comment by veeral-patel** [comment]
Thanks! For future reference, here are the sites I found useful:

https://cloud.ibm.com/catalog
https://www.ibm.com/design/language/gallery/
https://www.carbondesignsystem.com/guidelines/2x-grid/implementation

@laurenmrice As an aside - what's the difference between https://www.carbondesignsystem.com/ and https://www.ibm.com/design/language? Why are there two different sites?

**Comment by laurenmrice** [comment]
The Carbon Design System is specifically used for product design and has working code. We use the IBM Design Language as our foundation and have implemented the languages guidelines and principles throughout our system. The IBM Design Language focuses more on creating core elements like: a full color grade palette, icons, pictograms, grid and typography scales for different kinds of experiences (print, .com, product).

**Comment by veeral-patel** [comment]
@laurenmrice got it. IBM Design Language is a design language while Carbon Design System is a set of components and patterns you can actually use when building a product.
