### ISSUE TITLE
[ghost button] rename icon button to ghost icon button

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#286]
Rename symbols for the `icon button` to `ghost icon button` in sketch to match code.

- [x] In code

-------------------------------------------------------------------------------------------------

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

**Comment by aagonzales** [comment]
Updated! Available with next kit push.
Note: the tooltip on hover will have to be manually added for the moment. 

![image](https://user-images.githubusercontent.com/11670886/75702537-47968100-5c7b-11ea-9f6b-9aad111abe76.png)
