### ISSUE TITLE
rename fixed tabs to container tabs

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon-design-kit#287]
## Detailed description

Currently the kit has the **container** tabs named **fixed** tabs which is inconsistent with the website

> What version of the Carbon Design System Kit are you using?
Most recent downloadable one

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Fixed tabs

> What did you expect to happen? What happened instead? What would you like to see changed?
I expect the name to mimic the website

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Yes, see above

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Cloud

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed ! will be in next update  👍🏻
