### ISSUE TITLE
[Icon kit] Filter icon 16px

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#288]
In the icon kit _Filter_ icon 16px is incorrect. It shows _settings--adjust_ one instead.  

![image](https://user-images.githubusercontent.com/12408951/75451504-f59ae600-5970-11ea-9892-f90aef69cdc4.png)

**Comment by laurenmrice** [comment]
Tanks @mariuszmickiewicz for catching this. I am going to close this because we already are tracking it here https://github.com/carbon-design-system/carbon/issues/4990. 

This has been corrected in code, and needs to be transferred into the sketch libraries through out plugin. :)

**Comment by mariuszmickiewicz** [comment]
Great, thank you!
