### ISSUE TITLE
[Design Kit] Table header action bar – divider misaligned

### ISSUE THREAD

**Issue by skotschi** [carbon-design-system/carbon-design-kit#291]
## Detailed description

The divider line left to the cancel button is not correctly aligned. The line changes alignment with the length of the label  in the “Action 1” override.

> What version of the Carbon Design System Kit are you using?
10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
data table / table header / action bar / large / group

> What did you expect to happen? What happened instead? What would you like to see changed?
The divider should be aligned to the left of the "Cancel" button, disregarding th length of "Action 1"

## Screenshots
![Screenshot 2020-03-03 at 09 02 27](https://user-images.githubusercontent.com/20372317/75755399-d2848380-5d2e-11ea-8a49-e85729faea0a.png)
![Screenshot 2020-03-03 at 09 02 14](https://user-images.githubusercontent.com/20372317/75755403-d31d1a00-5d2e-11ea-9507-1f7d92e477c7.png)

**Comment by laurenmrice** [comment]
Thanks for catching this ! Yes, the divider in the large headers was not pinned correctly. Should be fixed in this mornings update !

**Comment by skotschi** [comment]
Hi @laurenmrice,
sadly the issue has not been resolved. The line is now too far on the right of the action bar. 
![Screenshot](https://user-images.githubusercontent.com/20372317/75863450-ca951400-5e00-11ea-96e9-443ff205c55f.png)

**Comment by laurenmrice** [comment]
Oh okay, I see what is happening now. I added a space between the hairline and the buttons and pinned them differently and am going to push an update. Once you update your kits let me know if you are still experiencing problems. thanks !

**Comment by skotschi** [comment]
Looking great. Thank you for your support on this!

**Comment by laurenmrice** [comment]
of course ! and thanks for telling us :D
