### ISSUE TITLE
"button / 04 ghost / icon only / 06 disabled" state color isn't disabled

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#293]
_gray 10 / button / 04 ghost / icon only / 06 disabled_ state isn't really disabled (icon color)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed !
