### ISSUE TITLE
Tab container 17px left margin

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-design-kit#296]
The labels in the tab / container / item symbol might have been shifted over an extra pixel and now have a 17px left margin.

This appears in all 4 themes.

![image](https://user-images.githubusercontent.com/19270502/76223573-71a2f280-61e9-11ea-8c34-e1eae4d41e94.png)

**Comment by laurenmrice** [comment]
working on it now. going to check container and default tabs

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! will be in next update 🎉
