### ISSUE TITLE
Would like to have a quick chat with designers of this library/kit to understand how the kit is built/compiled etc.

### ISSUE THREAD

**Issue by mellis3** [carbon-design-system/carbon-design-kit#299]
I am in charge of creating a large design system for my group.
I've been researching library architecture and I am wondering if it would be possible to discuss with one of the lead designers how they architected the Sketch Library.

For instance:
- are they using one large sketch file with many pages for each component type
- are they using individual files for each component type and then merging together to create the final library?
- how are the different theme files generated? Are all the components separated or is this done through overrides etc?

Thank you!

Mike Ellis
Supply Chain Design Manager - Walmart Labs

**Comment by aagonzales** [comment]
@mellis3 Hello! Lauren (@laurenmrice) and I would love to chat with you about all this. Are you wanting to set up a call or just talk in this issue?

**Comment by mellis3** [comment]
Hi @aagonzales - nice to meet you.
If you don't mind it would be great to do a 30 minute call. Do you use Zoom?

Would any of the following times work for you both?
- Monday March 16th at 3pm Central Time
- Tuesday March 17th at 10:30am Central
- Wednesday March 18th anytime after 9am Central
- Thursday March 19th between 10am and 12pm Central
- Friday March 20th at 2pm Central

Thanks! Looking forward to meeting you and discussing.

**Comment by aagonzales** [comment]
@mellis3 Here at big blue we use Webex but we can access Zoom if you share a link. Monday March 16th at 3pm Central Time would work for us! Our email addresses are agonz@us.ibm.com and rice@us.ibm.com.

**Comment by paolarico** [comment]
Hi, I follow the development of your design system very closely for a long time now and like Mike I am in charge of creating a large design system for my group and the university. I saw this message and I was wondering if this call is open to more people. I work for the University of Southern California and will love to hear and participate in this conversation. Very nice to e-meet you and I hope to hear from you soon. I can join the Zoom meeting as well. My email is paola.rico@usc.edu 😀
