### ISSUE TITLE
Requesting a Group Icon

### ISSUE THREAD

**Issue by lizhatfi** [carbon-design-system/carbon-design-kit#30]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.
This is a request for a new icon for a group of users.

> What version of the Carbon Design System Kit are you using?
Carbon Design Kit - 8.1.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Style/Icons/User exists.  Requesting Style/Icons/Group

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud Object Storage.  Mid year would be great.  

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.
Library
Icons

**Comment by tay-aitken** [comment]
Hi @lizhatfi we currently aren't taking icon requests at this time due to lack of resources but would be happy to work with you designing and contributing a  group icon.

**Comment by lizhatfi** [comment]
Ok thanks Tayler. Closing.
