### ISSUE TITLE
[Sketch Library]: Data table icon cells have inconsistent hover state

### ISSUE THREAD

**Issue by skotschi** [carbon-design-system/carbon-design-kit#303]
## Detailed description

Data table cells for icons in the Grey 10 theme use the wrong layer style for the top rule in the hover variant for all different sizes. It is "active-ui" but should be "ui-03".

> What version of the Carbon Design System Kit are you using?

Grey 10
Version 10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

- data table / cell / 24 compact / icon / 02 hover
- data table / cell / 32 short / icon / 02 hover
- data table / cell / 48 default / icon / 02 hover
- data table / cell / 64 tall / 1 line / icon / 02 hover
- data table / cell / 64 tall / 2 lines / icon / 02 hover

## Additional information

<img width="732" alt="Screen Shot 2020-03-31 at 10 35 51" src="https://user-images.githubusercontent.com/20372317/78005573-08238900-733c-11ea-8228-ecb930c89393.png">
<img width="417" alt="Screen Shot 2020-03-31 at 10 41 01" src="https://user-images.githubusercontent.com/20372317/78005646-27221b00-733c-11ea-8ecd-c15d356f8440.png">
<img width="904" alt="Screen Shot 2020-03-31 at 10 35 23" src="https://user-images.githubusercontent.com/20372317/78005695-3a34eb00-733c-11ea-8695-f52e60391302.png">

**Comment by laurenmrice** [comment]
Good catch! Will fix this for the Gray 10 theme, and check the other themes as well.

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed! will be in the next update. Also made sure the icons colors were consistent
