### ISSUE TITLE
[Sketch Kit]: Ghost Button doesn't resize corectly

### ISSUE THREAD

**Issue by skotschi** [carbon-design-system/carbon-design-kit#304]
## Detailed description

The ghost button with text an icon does not resize correctly with the text override. Especially in German with long words that causes issues frequently.

Carbon v. 10.5.0

### Affected components

- button / 04 ghost / small / 02 text and icon / 01 enabled
- button / 04 ghost / medium / 02 text and icon / 01 enabled
- button / 04 ghost / default / 02 text and icon / 01 enabled

### Expected result

The primary button scales as expected so it might work for reference.

## Additional information

<img width="620" alt="grafik" src="https://user-images.githubusercontent.com/20372317/78008658-37d49000-7340-11ea-8509-007c98072caa.png">

**Comment by laurenmrice** [comment]
Yes, looks like there is a pinning issue with the type.

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed ! will be in next update 🙌🏻
