### ISSUE TITLE
[Sketch Library]: Inconsistency with layout and spacing in Sketch and the Website

### ISSUE THREAD

**Issue by kiadorii** [carbon-design-system/carbon-design-kit#305]
## Detailed description
There are inconsistency with the naming and colors of the layout and spacing in Sketch and the Website. 

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Spacing scale color is purple in the website but in Sketch, they are teal.
Layout scale in website is teal but it is purple in Sketch.

## Additional information
![Screen Shot 2020-03-31 at 8 07 33 PM](https://user-images.githubusercontent.com/31292683/78095616-3f218b00-738c-11ea-8776-df5377b233eb.png)
<img width="321" alt="Screen Shot 2020-03-31 at 8 07 16 PM" src="https://user-images.githubusercontent.com/31292683/78095622-4183e500-738c-11ea-8e93-eba7a145be57.png">

![Screen Shot 2020-03-31 at 8 07 44 PM](https://user-images.githubusercontent.com/31292683/78095629-447ed580-738c-11ea-9245-f6a7defb6f7f.png)
<img width="287" alt="Screen Shot 2020-03-31 at 8 08 06 PM" src="https://user-images.githubusercontent.com/31292683/78095631-46489900-738c-11ea-8d2c-f780fe50e4c6.png">

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by aagonzales** [comment]
We are currently working through some new production guidelines in regrades to how we show layout and spacing tokens. Once we have the new guidelines we will update these to be consistent. 

Also I think currently the website it the incorrect color applications so this might now be a dev bug. But thanks for point this out!

**Comment by aagonzales** [comment]
Spacing and layout tokens have been combined into one scale. There should no longer be confusion for this point.
