### ISSUE TITLE
Inline Loading: Sketch component out-of-date

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-design-kit#306]
In carbon-design-system/carbon#5018, the error icon for the inline loading component was changed from outline to filled.

This is not yet reflected in the sketch kit.

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed ! will be in next update 🙌🏻
