### ISSUE TITLE
[notification] update default time stamp

### ISSUE THREAD

**Issue by jillianhowarth** [carbon-design-system/carbon-design-kit#308]
Update the default toast time stamp to match the updated notification usage guidance. It should be `00:00:00 AM` instead of `Time stamp [00:00:00]`

**Comment by aagonzales** [comment]
- [ ] White theme
- [ ] G10
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Fixed! Available in the next kit update.
