### ISSUE TITLE
[notification] action button states not responding with custom type

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#309]
Need to fix notifications with action buttons to have state backgrounds respond to custom text.
![image (4)](https://user-images.githubusercontent.com/43969356/78891668-9cbd7380-7a2d-11ea-9291-4cc86cf5904e.png)

**Comment by aagonzales** [comment]
- [ ] White theme
   - [ ] Inline - low contrast - single line
   - [ ] Inline - low contrast - multi-line

**Comment by laurenmrice** [comment]
fixed ! available in next update
