### ISSUE TITLE
Hex Values different between color palette and Carbon themes. 

### ISSUE THREAD

**Issue by sarah-the-sweet** [carbon-design-system/carbon-design-kit#310]
When I go to the Appearance panel in Sketch, go through the gray 10 theme, and choose inverse-support-02 (which is supposed to be Green 40), the hex value is different than when I choose green 40 in my colors panel. I'm using the latest library: IBM_Colors_RGB_HEX_V10.2. 

From @laurenmrice : 
That is a bug with the ase/clr file. 

> What version of the Carbon Design System Kit are you using?
Carbon 10, and I keep it up to date. 

> What did you expect to happen? What happened instead? What would you like to see changed?
Consistent hex values

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
The hex values are different between themes and the color palette. 

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Cloud Identity. And no, not necessarily. We're creating documentation for our developers and were hoping to reference these values.  

## Additional information

* Screenshots or Sketch file links

<img width="492" alt="Screen Shot 2020-04-14 at 2 47 09 PM" src="https://user-images.githubusercontent.com/15874450/79268748-e4defa80-7e60-11ea-80fd-c327f7b252fc.png">
<img width="807" alt="Screen Shot 2020-04-14 at 2 39 40 PM" src="https://user-images.githubusercontent.com/15874450/79268872-18ba2000-7e61-11ea-8032-db32ce7873f7.png">

* Notes
Thank you! 

## Add labels
libraries

**Comment by laurenmrice** [comment]
closing because this has been fixed !
