### ISSUE TITLE
large modal / progress / no label: cancel button needs to be pinned

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon-design-kit#311]
## Detailed description

The cancel button becomes unaligned

> What version of the Carbon Design System Kit are you using?

most up to date

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

modal / group / 04 large / 04 progress / no label

> What did you expect to happen? What happened instead? What would you like to see changed?

when modal is stretched taller, the cancel button doesn't stay pinned to bottom therefore it's no longer aligned to the other buttons in the modal

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Cloud Platform, just putting together a prototype on a new project so no pressing dates

## Steps to reproduce the issue

1. take modal
2. stretch modal taller
3. see cancel button

## Additional information
<img width="802" alt="Screen Shot 2020-04-16 at 2 29 53 PM" src="https://user-images.githubusercontent.com/12436158/79498778-741a1880-7fef-11ea-806a-3b70da8bbc3b.png">

**Comment by laurenmrice** [comment]
Thanks Erica ! will fix 👍🏻

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
fixed ! will be in next update 👍🏻
