### ISSUE TITLE
[Sketch Kit]: Request – Weekdays in calendar should be overrides 

### ISSUE THREAD

**Issue by skotschi** [carbon-design-system/carbon-design-kit#312]
## Detailed description

The Calendar component currently shows the week starting on sunday and overrides are locked. Different regions have different definitions of the first day of the week so the weekday  should be overrides (also for localization).

> What version of the Carbon Design System Kit are you using?

10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

date picker / pieces / calendar

> What did you expect to happen? What happened instead? What would you like to see changed?

Have text values in the "Weekdays"-Group as overrides 
<img width="367" alt="grafik" src="https://user-images.githubusercontent.com/20372317/79545220-a039a600-8090-11ea-85d2-fb4af5e4a1a1.png">

**Comment by aagonzales** [comment]
Themes:
- [x] White
- [x] G10
- [x] G90
- [x] G100

Fixed! Available in the next kit update.
