### ISSUE TITLE
[Sketch Library]: Gray 10 theme > selectable and expandable data table header symbol > background color

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/carbon-design-kit#313]
## The background appears darker than in the rest of the headers

> Version 10

## Additional information

![image](https://user-images.githubusercontent.com/24441071/79605224-7f3b7a00-80bd-11ea-9bc9-f22e386da094.png)

**Comment by laurenmrice** [comment]
I recreated this table using the current libraries and I am not experiencing the same color change. if you disconnect that symbol and view the color, does it say `ui-03` #e0e0e0?

I would make sure you are on the latest version of sketch and have our libraries updated.

**Comment by assiroud** [comment]
Thanks getting to this so fast Lauren!  Just double checked and that's right - it's back to normal. Not sure what kind of glitch was it last week. Thanks again. You are doing a great job.

**Comment by laurenmrice** [comment]
okay awesome ! I am glad its back to normal :)
