### ISSUE TITLE
[dropdown] increase inline field height 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#316]
Ref: https://github.com/carbon-design-system/carbon/issues/5966

Need to change inline dropdown bounding box to 40px instead of 32px. Also noticed some weird spacing issues width wise.

**Comment by aagonzales** [comment]
Also fixing the left/right padding for the inline dropdown to be 16px instead of 8px.

- [ ] White
- [ ] Gray10
- [ ] Gray90
- [ ] Gray 100

**Comment by aagonzales** [comment]
Fixed! Available with the next kit update.
