### ISSUE TITLE
[ui shell] update colors

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#319]
Update the colors in the UI Shell symbols to use the new Language V2 palette. All colors should be pointing to new v2 language kit and should not be pointing to a specific carbon theme file. Any hover colors not in the v2 library should be entered as raw hex values. 

Related: https://github.com/carbon-design-system/carbon-design-kit/issues/240#issuecomment-574421475

**Comment by mariuszmickiewicz** [comment]
* Layer styles are updated. 
* Icon/symbols overrides still require more testing, to be sure it won't affect overrides made by the library user.
