### ISSUE TITLE
[Sketch Kit] – Month/Year Text alignment

### ISSUE THREAD

**Issue by skotschi** [carbon-design-system/carbon-design-kit#320]
# [Sketch Kit] – Month/Year Text alignment

## Detailed description
The Text in the Month/Year symbol used inside the calendar should be center aligned instead of left aligned, as it is in code.

> What version of the Carbon Design System Kit are you using?

10.5.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

date picker / pieces / month year / default

> What did you expect to happen? What happened instead? What would you like to see changed?

Text is center aligned so that the text stays centred when the override changes.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

Correct behaviour reflected in code, see https://react.carbondesignsystem.com/?path=/story/datepicker--fully-controlled

## Additional information
![01 placeholder](https://user-images.githubusercontent.com/20372317/81060296-7840a400-8ed2-11ea-87ad-93375ad1bb5c.png)

<img width="497" alt="Screen Shot 2020-05-05 at 13 14 06" src="https://user-images.githubusercontent.com/20372317/81060349-91e1eb80-8ed2-11ea-9fac-ee12fd927b64.png">

**Comment by aagonzales** [comment]
Fixed! Available in the next kit update.
