### ISSUE TITLE
[helper text] move helper text below the field

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#327]
In code the helper text has now been moved below the field. We need to make those changes to our symbols in the kit that have helper text.

![Artboard](https://user-images.githubusercontent.com/43969356/84314911-7a7bcb00-ab2e-11ea-945b-81fdf87a1adb.png)

--------------------------------------------------------------------------------------------------

- [x] dropdown
   - [x] white
   - [x] gray 10
   - [x] gray 90
   - [x] gray 100
- [x] text area
   - [x] white
   - [x] gray 10
   - [x] gray 90
   - [x] gray 100
- [x] text input
   - [x] white
   - [x] gray 10
   - [x] gray 90
   - [x] gray 100

**Comment by half5cat** [comment]
In addition, the helper text seems to have the same color as the label: https://react.carbondesignsystem.com/?path=/story/dropdown--default

**Comment by aagonzales** [comment]
Helper text should be user color `text-02` now that its changed back to its original value.
https://github.com/carbon-design-system/carbon/pull/5867

**Comment by aagonzales** [comment]
Done! Available in the next kit update. There might still be some instances for `text-02` that haven't been updated. We should make an index for all the type styles so those are easier to update.
