### ISSUE TITLE
Sketch kit request: linked data table cells

### ISSUE THREAD

**Issue by alissach** [carbon-design-system/carbon-design-kit#329]
## Detailed description

This is a Sketch kit request to either...
1. add a new symbol for linked data table cells in all of the Sketch libraries, OR 
2. add an option to override data table cell text to be a link. 

My team (IBM Cloud Virtual Private Cloud) uses linked data table cells everywhere, and I'm pretty sure other teams on IBM Cloud products have a need for this. 

Because there's no Carbon symbol for this, it's significantly slower for us to create a clickable prototype. We waste a lot of time detaching the data table cell symbols, ungrouping everything for easier management, changing it to a link. Then it's not a symbol so it's a lot harder to simply change cell text. Or, we have to make our own symbol local which also takes a lot of time.

Please add this to the Sketch kit as it'd significantly reduce the time we have to spend managing our own Sketch files for consistency.

### What version of the Carbon Design System Kit are you using?
Not sure how to answer this. I'm using the most updated ones, according to Sketch Cloud.

### Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Ideal location of this linked cell would be: [theme]/data table/cell/[row height]/default/
Or again, just allow cell text overrides to make it a link.

### What did you expect to happen? What happened instead? What would you like to see changed?
I would love to see a new symbol for linked data table cells in all of the Sketch libraries, OR an option to override cell text to be a link. I'm pretty sure other teams besides VPC have a need for this as well, at least on IBM Cloud products.

### Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Nope.

### What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM Cloud, Virtual Private Cloud. Not pressing, but would really increase our productivity. We'd prefer not to create our own Sketch library just to add this symbol, which is used pretty much in every data table throughout VPC.

## Additional information

Ideally each theme, each table height, within each **Default** and **Expandable** folder would have a "linked" option. 
![image](https://user-images.githubusercontent.com/16602130/84404976-1eb44f00-abcd-11ea-91ab-3a260300bdf0.png)

Alternatively - and probably easier to implement - just allow style overrides for the data table cell text so it's either the regular text (As Is) or the appropriate linked text. 

If you have further questions please contact me via Slack: @ Alissa Chan

## Add labels
**Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.**
I'm unable to add labels...

**Comment by laurenmrice** [comment]
I enabled text style overrides for the cells in data tables for all themes so you will be able to attach the link-01 color 👍🏻. Will be in the next update!
