### ISSUE TITLE
An alternative design kit for opensource softwares like inkscape

### ISSUE THREAD

**Issue by Brun0fl** [carbon-design-system/carbon-design-kit#33]
Hi, 
Good day team,
I don't have a sketch license, but I do use inkscape.org that uses vector files with .svg extension file.
I would like to know if, in near future, this team would consider exporting the carbon-design-kit sketch files to opensource formats that could be used in other operating systems like windows, linux and OSX without a sketch license.

Thanks!

**Comment by havesomeleeway** [comment]
If you have adobe XD, I'm actually working on one for Adobe XD and I can send you some of my work so far if you are interested.

**Comment by Brun0fl** [comment]
Yes I do, is it published ?
Thanks!

**Comment by havesomeleeway** [comment]
It isn't published. I'm still working my way replicating it using the Sketch copy that I downloaded as well as referring to the site. There are some 'irritating' components such as the calendar, tables that I am leaving till the end. If you can wait, I aim to finish it by the end of next week. I can share it with you by then. Else, I can send you what I have now.

**Comment by Brun0fl** [comment]
Sounds great! I can wait one week or two. Thanks!

**Comment by tay-aitken** [comment]
@havesomeleeway that's so awesome that you are building that! If you would like to contribute it back to Carbon we would be thrilled! Would love to set up a meet up to go over what you have done.

We haven't supported additional kit file types in the past due to a lack of resources (only 2 of us visual designers here on the Carbon team). Having more than one kit to maintain gets really tricky. However if there was an easy way to export the kit to other programs we would definitely be into trying it out. We can try to do some research into tools that might accomplish this. If you guys have any tool suggestions please let us know!

**Comment by havesomeleeway** [comment]
I don't think there is an easy way to do this. Unfortunately there is just no proper version controlling for design tools as of yet that are widely served. I have heard of Plant and Kactus but it's still only available to a controlled population. 

What I have done so far is to download the latest kit, look at the specifications .pdf, then work off that. I can't remember which file it is but it's the pdf with the components slapped onto it. 

Unfortunately, I do not own a Sketch license. My primary workstation is a Windows and I have an old and dying Mac from 2011 at home. 

@tay-aitken , if you have Adobe XD, I could share the files with you once i'm done. You could take a look at them, compare it with your Sketch files then inform me on the changes that you would like made.

**Comment by Brun0fl** [comment]
There is an app called Figma <https://www.figma.com/features>, that promises to import sketch files with high fidelity without the need of having a sketch license, I haven't tried it yet, but looks like it may be possible to export into other formats. Will keep searching if other promising options are available.

**Comment by tay-aitken** [comment]
@havesomeleeway would it be helpful, if in the future we export the components page with specs? using something like [Marketch](https://github.com/tudou527/marketch)?

I do have an adobeXD license. I would love to check it out. @ me in this issue when you've finished and we can go over the file :)

@Brun0fl I will check that out and see if the capabilities align!

**Comment by havesomeleeway** [comment]
@tay-aitken I think whatever that is available on the `/style` pages of the components works well enough for my use case. Take a look at the latest issue I created. I wrapped up the first draft of the carbon kit in `.xd`

**Comment by tay-aitken** [comment]
@Brun0fl thanks for making the issue and @havesomeleeway thanks for you exploration in =to Adobe Xd. This work is being tracked in issue #36 so I am closing this issue. We are looking into possibility supporting more than a sketch kit. Thanks for the suggestion,
