### ISSUE TITLE
[Data tables]: Missing example of data table tall with 2 lines 

### ISSUE THREAD

**Issue by half5cat** [carbon-design-system/carbon-design-kit#331]
##  Detailed description

In the Sketch Kit file under the symbols you can find "2 lines" versions of the tall cells (e.g. data table / cell / 64 tall / 2 lines / selectable / 01 unselected). There is no representation of this in the example page "Data table". I am actually unsure if this might be deprecated as there is also no documentation on the Carbon Website.

## Screenshot of an example cell

![01 unselected](https://user-images.githubusercontent.com/1887866/85305991-24077880-b4ae-11ea-94e3-1545e6257446.png)

**Comment by laurenmrice** [comment]
That is a good point. Someone on our team is currently working on revising the data table documentation. I am going to make a dev issue to include this variation of the tall rows in react, so it will show up in the component demo.
