### ISSUE TITLE
[link] Update focus style

### ISSUE THREAD

**Issue by half5cat** [carbon-design-system/carbon-design-kit#333]
The focus style from the Sketch Kit is not reflecting the actual behaviour: https://www.carbondesignsystem.com/components/link/usage and https://react.carbondesignsystem.com/?path=/story/link--default

This is what the sketch file contains:
![image](https://user-images.githubusercontent.com/1887866/85843490-865bc400-b7a1-11ea-9dda-1fa5b2d38764.png)

And this is how it should be:
![image](https://user-images.githubusercontent.com/1887866/85843550-97a4d080-b7a1-11ea-95de-02b90ae6a8f9.png)

This also affects the breadcrumbs styles.

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Will be available in the next update  🎉
