### ISSUE TITLE
[Progress indicator] Focus style is misrepresented

### ISSUE THREAD

**Issue by half5cat** [carbon-design-system/carbon-design-kit#334]
In the progress indicator components, the focus style is show as this:
![image](https://user-images.githubusercontent.com/1887866/85880296-10c11980-b7dc-11ea-843d-6a1a7f3564a0.png)

But it should actually look like this:
![image](https://user-images.githubusercontent.com/1887866/85880233-f9822c00-b7db-11ea-9958-86963694552d.png)

Sources:
https://www.carbondesignsystem.com/components/progress-indicator/usage
https://react.carbondesignsystem.com/?path=/story/progressindicator--default

**Comment by laurenmrice** [comment]
Yes, the focus style should have the 3px underline and the hover as well should have a regular underline. Will fix!

**Comment by laurenmrice** [comment]
- [x] White theme
- [x] Gray 10 theme (in progress)
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Will be available in the next update. 🎉
