### ISSUE TITLE
Update text-02 color

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#335]
`text-02` should go back to its original value.
https://github.com/carbon-design-system/carbon/pull/5867
https://carbon-elements.netlify.app/themes/examples/preview/#text02

**Comment by laurenmrice** [comment]
- [ ] White
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by laurenmrice** [comment]
fixed!
