### ISSUE TITLE
[Select] Inline style misrepresented

### ISSUE THREAD

**Issue by half5cat** [carbon-design-system/carbon-design-kit#337]
The inline Selcet is different from its documentation: Padding should be 8px. I am unsure about the height. the image is different from the text. Text says 32 px, picture says 40px. Might be related to https://github.com/carbon-design-system/carbon-design-kit/issues/316 ?

**Comment by laurenmrice** [comment]
The inline dropdown should be the specs as follows. We need to update the style images on the website to reflect this:

![Artboard](https://user-images.githubusercontent.com/43969356/88078152-b8163f80-cb41-11ea-8efc-b75ace8d90cb.png)

-The left and right padding of the inline dropdown should be 16px to line up with the options in the menu when open.
-The padding between the chevron and the text should be 8px. 
-The height of the inline dropdown should be 48px, 40px or 32px (depending on which size you are using).

**Comment by laurenmrice** [comment]
I am going to close this issue and track this change separately in our website repo. 👍🏻
