### ISSUE TITLE
Overflow Menu Items height

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon-design-kit#338]
In "Carbon Design System (Gray 10 theme)" Sketch library we have the Overflow Menu Items set to 34px height. 

<img width="2672" alt="Screenshot 2020-06-10 at 15 53 06" src="https://user-images.githubusercontent.com/1560160/84270078-caf52780-ab32-11ea-9f48-f55a6f9d1bd3.png">

I wanted to check if this is deliberate (given that this value is not divisible by 8) or something that should be addressed? 

For example, inspecting the Live Demo on https://www.carbondesignsystem.com/components/overflow-menu/usage/ shows 40px used for the items height.

<img width="1980" alt="Screenshot 2020-06-10 at 15 52 03" src="https://user-images.githubusercontent.com/1560160/84270089-cdf01800-ab32-11ea-9972-11ff4fbfd8f0.png">

**Comment by aagonzales** [comment]
Oops responded before fully reading the issue. 
1. 34px is incorrect in that we use 32px being an increment of 8
2. However your question was whether it should 32px or 40px rows. Originally in the system we had 32px be the default height of items in the system. We eventually changed the default height to be 40px. So the default overflow component should be rendering with 40px row height items. This is wrong in the kit. 
3. We are working on adding size variants to several components. Overflow menu will be one of them, in the future it will have a 32px and 40px row height option (maybe one larger as well).

**Comment by laurenmrice** [comment]
Fix overflow to have 32px height rows instead of 34px
- [ ] White theme
- [ ] Gray 10
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed ! Will be in the next kit update. 🎉

As for incorporating different overflow menu sizes, we will make a separate issue for this in our carbon repo to include more sizes in code (a 40px and possibly a 48px). Once the sizes are in code then we will add them into the kit!
