### ISSUE TITLE
[checkbox] update focus style

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#339]
Focus style of checkbox has recently been updated in code. Need to update symbol.
https://react.carbondesignsystem.com/?path=/story/checkbox--checked
![image](https://user-images.githubusercontent.com/11670886/87345998-8d5f3200-c516-11ea-9af4-35493fe28724.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by mariuszmickiewicz** [comment]
In the code: 
* base component (checkbox + label) is 24px high with 4px margin below
* checkbox icon is 16x16 (no 1px padding, which makes it 2px bigger than in the kit), with 24x24 container

In the kit:
* base component is 20px high with 8px margin 
* checkbox icon is 16x16 (1px internal padding), 20x20 container

The easiest thing to do would be to add focus element which goes outside the checkbox artboard. This way it wouldn't break anything in the files where people already use it, but it also wouldn't count when measuring the spaces between the checkbox component and other ones. 
Visually both versions would match (focus on both would go outside the grid), but still the way of measuring things would stay different.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/12408951/90492192-336b1100-e141-11ea-892d-de15fbef25a1.png">

**Comment by laurenmrice** [comment]
- [x] White theme
- [x] Gray 10 theme (in progress)
- [ ] Gray 90 theme
- [ ] Gray 100 theme
