### ISSUE TITLE
CodeSnippet: "Show more" button inconsistent between Sketch and implementation

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-design-kit#343]
## Detailed description

According to the code implementations and the [carbon website](https://www.carbondesignsystem.com/components/code-snippet/style#multi-line-code-snippet) the "Show more" button in the multi-line code snippet has black / dark gray font color. The sketch kit uses the ghost button and therefore displays the button in blue.

> What version of the Carbon Design System Kit are you using?

Sketch library from Sketch cloud (updated 3rd of July)

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

CodeSnippet

## Additional information

Sketch
![image](https://user-images.githubusercontent.com/28265588/88032327-16d9ba00-cb3e-11ea-8cd4-d41a775b04e3.png)

Carbon Website
![image](https://www.carbondesignsystem.com/static/5492b85d79a8ed2787ed197fb794fcf8/3cbba/code-snippet-style-2.png)

React storybook
![image](https://user-images.githubusercontent.com/28265588/88032267-00cbf980-cb3e-11ea-8094-c7246f865a9b.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Will be in the next update

**Comment by janhassel** [comment]
Wow! thanks for the fast update, @laurenmrice! 🚀
