### ISSUE TITLE
Small toggles, off state

### ISSUE THREAD

**Issue by heatherco** [carbon-design-system/carbon-design-kit#344]
Sketch libraries grey 10 and white: the small toggles in off state are not consistent with the big toggle versions. Also at their current state in the sketch file, they do not meet the 3:1 accessibility ratio.

<img width="994" alt="Screen_Shot_2020-07-07_at_11_12_02_AM" src="https://user-images.githubusercontent.com/12818623/86803907-6dc29800-c044-11ea-9439-c0be13080f82.png">

**Comment by aagonzales** [comment]
Check to make sure all toggle states in all themes have the updated values
https://github.com/carbon-design-system/carbon/issues/3614

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! will be in next kit update 🎉
