### ISSUE TITLE
README says "then on the next age"

### ISSUE THREAD

**Issue by starpit** [carbon-design-system/carbon-design-kit#345]
## Detailed description

The top-level README has this text "then on the next age", which probably should have been "then on the next page"

> What version of the Carbon Design System Kit are you using?

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

> What did you expect to happen? What happened instead? What would you like to see changed?

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by mariuszmickiewicz** [comment]
Thanks @starpit !
