### ISSUE TITLE
[content switcher] add select+focus symbol

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#347]
Selected + focus was not passing accessibility. We have updated the style and it needs its own symbols now.
See: https://github.com/carbon-design-system/carbon/issues/6465

![image](https://user-images.githubusercontent.com/11670886/88689452-1a31f000-d0c0-11ea-80ae-1f416258bb65.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Added! will be in the next kit update 🎉
