### ISSUE TITLE
[code snippet] allow copy button to be hidden

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#348]
Allow people to hide copy button in a code snippet.

-----------------------------------------------------------------------------------------------------------------------------

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

**Comment by mariuszmickiewicz** [comment]
@laurenmrice 
I checked Gray 10 and Gray 90 and I see that currently it is possible to turn of the Copy button (with the exception of Skeleton in Gray 10 and White).
* Does this mean someone already worked on this issue?
* Or the request means that text area should react to the fact button is not there (that would be tricky with multi-line component where Show less button is present)?

As a general note: I would add a state like this one for the icon button 
button / 04 ghost / small / 03 icon / **00 none**
with empty symbol. 

This way it would be much easier to "remove it" it and then bring it back, as it would be a sibling of the current symbols. Currently if it is turned off by choosing "No symbol" then a designer needs to know where exactly this button is in the whole hierarchy of the symbols.

**Comment by laurenmrice** [comment]
No one has worked on doing this yet as far as I know. Adding a state for this makes sense to me. 👍🏻 @mariuszmickiewicz

**Comment by mariuszmickiewicz** [comment]
I added an ability to hide the _Copy_ button in some skeleton states. 
Seems to me that this request is more related to the code (React) where it is not possible to hide this button currently. Also in React skeleton states look a bit different: no _Copy_ or _Show more_ buttons are visible.

**Comment by laurenmrice** [comment]
We recently added being able to remove copy functionality in code, it just has not gone live yet. For skeleton states, we kept the icon for context in the kits.
