### ISSUE TITLE
[modal] update buttons to have rule seperator

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#349]
Update fluid buttons in modals to have a `gray-20, 1 px` solid separator for 3:1. And add `button-separator` token

![Artboard](https://user-images.githubusercontent.com/43969356/89467418-1eeb4980-d73b-11ea-8dc4-3d5f2281fd46.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
added! will be available in next update 🎉

**Comment by ingedmundo** [comment]
V r.    Si.  R. R.     I.     I```

```y.  Y y. Y
