### ISSUE TITLE
Text style duplicates

### ISSUE THREAD

**Issue by josh-tt** [carbon-design-system/carbon-design-kit#355]
Text styles have duplicates due to lacking 'space' in name resulting in duplicate listings in 'components' when working offline with the libraries. 

## Detailed description

It appears that some Text styles lack a 'space' causing duplicates to show up in components view and making it troublesome to manage the file via SCSS. 

> What version of the Carbon Design System Kit are you using?

Latest downloaded from Sketch Cloudl

View example:
https://snipboard.io/uGS04n.jpg
## Steps to reproduce the issue

Download Gray 10 from cloud.
Open Gray 10. 
Open Sketch Manager Plugin
You will see duplicate styles, some with space between them some without.  
For example: body-long-01 and body-long-01[space}

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.
Bug

**Comment by mariuszmickiewicz** [comment]
The moment text, layer style or symbol is managed (renamed, moved etc.) by internal Sketch's _Components_ panel the space in the name is removed (untouched elements remain the same -> currently with spaces). In this particular case it seems like the plugin can't handle this very well — default _Components_ panel can handle it better. Btw. Sketch 69 is going to introduce a new Components panel, let's wait and see how it handles (I assume it will be ok as in the current one).

Anyway, spaces vs not should be addressed somehow (Sketch people said they will look into this, but of course no promises).
FYI @laurenmrice

**Comment by mariuszmickiewicz** [comment]
@josh-tt Did you have a chance to play with Sketch 69 components panel? It should have the same functionality as the plugin you use.
