### ISSUE TITLE
UI Shell - Left Panel - Gray 90 - colours

### ISSUE THREAD

**Issue by xkov** [carbon-design-system/carbon-design-kit#356]
## Detailed description

In Sketch, the group of items in UI Shell > Left Panel > **Side Nav** and **Side Rail** have unexpected colours. I expected them to have dark backgrounds and light foregrounds in the Gray 90 and Gray 100 themes, but they are light. They seem similar to the light theme versions.

> What version of the Carbon Design System Kit are you using?

The latest, updated 11 Aug 2020 (I think it's 10.10)

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Yes. UI Shell > Left Panel > **Side Nav** and **Side Rail**

> What did you expect to happen? What happened instead? What would you like to see changed?

The symbol items I place on my Sketch (v68.1) artboard I expected to be dark themed.
The items are light themed.
Appropriate dark theme colours applied.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

I have seen examples on Carbon gallery web pages, where on a dark themed design the UI Shell Side Rail and Side Nav follow the general dark theme. 

## Steps to reproduce the issue

1. In Sketch, go to 
Insert > Symbols > Carbon Design System (Gray 90 theme) > ui shell > left panel > group > side rail > open
or
Insert > Symbols > Carbon Design System (Gray 90 theme) > ui shell > left panel > group > side-nav > default
(or similar items there)
and add the symbol to the artboard
2. Observe the colours are in a light theme

## Add labels
`libraries` `kit: sketch` `theme` `color`

<img width="545" alt="Screen Shot 2020-08-28 at 10 34 35 am" src="https://user-images.githubusercontent.com/58238106/91529407-94b68f80-e94c-11ea-9b54-43a47b3a5877.png">

**Comment by laurenmrice** [comment]
The Carbon UI Shell does not have themes right now but is something we plan to implement for our next major release in June. This is an open issue for the different possible theme options https://github.com/carbon-design-system/carbon/issues/4839.
