### ISSUE TITLE
[Inline loading] Color of success icon

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#357]
What should be the color of the success icon?

Code uses green
<img width="134" alt="image" src="https://user-images.githubusercontent.com/12408951/91951895-10279080-ed01-11ea-8c00-353dee8f9e4e.png">

Sketch kit uses `interactive-01`
<img width="167" alt="image" src="https://user-images.githubusercontent.com/12408951/91952297-2b929b80-ed01-11ea-9c03-3444a5a290df.png">

Example image uses `interactive` color, but not filled icon.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/12408951/91952688-4533e300-ed01-11ea-8c5c-0c5520a3b09b.png">

**Comment by laurenmrice** [comment]
It should be the second one: blue fill with white inner fill.

**Comment by laurenmrice** [comment]
We are going to go with the `checkmark--filled` icon with `support-02` color

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Will be in next update 🎉
