### ISSUE TITLE
[text input] add no label version

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#359]
Make a `no label` version like we have for dropdowns.

All three sizes for:
- [x] White
- [x] Gray 10
- [x] Gray 90
- [x] Gray 100

![Artboard](https://user-images.githubusercontent.com/43969356/92755226-9ecb8b80-f359-11ea-89c8-4d1510b295f0.png)

**Comment by mariuszmickiewicz** [comment]
Added large, medium, small for Gray 10 theme.

**Comment by mariuszmickiewicz** [comment]
All themes done.
