### ISSUE TITLE
Adobe XD Kit Review

### ISSUE THREAD

**Issue by havesomeleeway** [carbon-design-system/carbon-design-kit#36]
## Description

As I wrap up my work on the Adobe XD Carbon Components kit, I thought it would be good to layout the components that I have currently so that we can review them. As far as possible, I have cross referenced both the kit from Sketch as well as the components from the website for consistency. Where there are consistency conflicts, I fall back onto what is available on the site. 

💾 Download the kit: https://drive.google.com/file/d/1SFevPh1ALrlQOHYSFgUyA7raiyt-5uQT/view?usp=sharing

If you do not have Adobe XD but want to take a look at the kit, use the link below. It still requires an Adobe account because the **dictators** at Adobe said so.
https://xd.adobe.com/spec/1f560469-37bd-44ca-931b-c03dfdd80b55

If there is anything that you would like worked on, please add them to the To-do list or reply below.

## Notes / To-do

**[Accordion](http://www.carbondesignsystem.com/components/accordion/code)**
- [ ] N/A

**[Breadcrumb](http://www.carbondesignsystem.com/components/breadcrumb/code)**
- [ ] N/A

**[Button](http://www.carbondesignsystem.com/components/button/code)**
- [x] Include both Primary and Secondary buttons
- [x] Remove Icons from Danger buttons

**[Checkbox](http://www.carbondesignsystem.com/components/checkbox/code)**
- [ ] Add `indeterminate` state for checkbox

**[Code Snippet](http://www.carbondesignsystem.com/components/code-snippet/code)**
- [ ] Replace `copy-icon` with a proper symbol

**[Content Switcher](http://www.carbondesignsystem.com/components/content-switcher/code)**
- [x] Add Content Switcher with Icon

**[Data Table](http://www.carbondesignsystem.com/components/data-table/code)**
- [ ] N/A

**[Date Picker](system.com/components/date-picker/code)**
- [ ] Better formatting of the UI on the date picker

**[Dropdown](http://www.carbondesignsystem.com/components/dropdown/code)**
- [ ] Add multi-select dropdown
- [ ] Add Inline multi-select dropdown
- [ ] Add filter dropdown

**[File Uploader](http://www.carbondesignsystem.com/components/file-uploader/code)**
- [ ] N/A

**[Form](http://www.carbondesignsystem.com/components/form/code)**
- [ ] N/A

**[Link](http://www.carbondesignsystem.com/components/link/code)**
- [ ] N/A

**[List](http://www.carbondesignsystem.com/components/list/code)**
- [ ] N/A

**[Loading](http://www.carbondesignsystem.com/components/loading/code)**
- [x] Use a better .svg for big loader
- [ ] Use a better .svg for small loader

**[Modal](http://www.carbondesignsystem.com/components/modal/code)**
- [x] Add `Passive Danger` Modal
- [x] Add `Transactional Danger` Modal

**[Notification](http://www.carbondesignsystem.com/components/notification/code)**
- [ ] N/A

**[Number Input](http://www.carbondesignsystem.com/components/number-input/code)**
- [ ] N/A

**[Overflow Menu](http://www.carbondesignsystem.com/components/overflow-menu/code)**
- [x] Better formatted according to https://codepen.io/team/carbon/full/MOEwjp/
> Example from my Adobe Kit: 
![screen shot 2018-03-06 at 10 13 01 pm](https://user-images.githubusercontent.com/25948209/37036770-9645dce2-218b-11e8-9002-3594f51ac32a.png)

**[Pagination](http://www.carbondesignsystem.com/components/pagination/code)**
- [ ] Add Pagination `v1`? (Will not bother if it is depreciated)

**[Progress Indicator](http://www.carbondesignsystem.com/components/progress-indicator/code)**
- [ ] N/A

**[Radio Button](http://www.carbondesignsystem.com/components/radio-button/code)**
- [ ] N/A

**[Search](http://www.carbondesignsystem.com/components/search/code)**
- [x] Add `big search with options`

**[Select](http://www.carbondesignsystem.com/components/select/code)**
- [x] Add `Inline select`

**[Slider](http://www.carbondesignsystem.com/components/slider/code)**
- [ ] N/A

**[Structured List](http://www.carbondesignsystem.com/components/structured-list/code)**
- [ ] Add multiple columns like how it appears on the site

**[Tabs](http://www.carbondesignsystem.com/components/tabs/code)**
- [ ] N/A

**[Tag](http://www.carbondesignsystem.com/components/tag/code)**
- [x] Better formatted according to https://codepen.io/team/carbon/full/GOWdob/
> Example from my Adobe Kit: 
![tag](https://user-images.githubusercontent.com/25948209/38397293-81e5ce6e-396f-11e8-9a27-f7cf6caac3c3.png)

**[Text input](http://www.carbondesignsystem.com/components/text-input/code)**
- [ ] N/A

**[Tile](http://www.carbondesignsystem.com/components/tile/code)**
- [ ] N/A

**[Toggle](http://www.carbondesignsystem.com/components/toggle/code)**
- [ ] N/A

**[Tooltip](http://www.carbondesignsystem.com/components/tooltip/code)**
- [ ] N/A

## Notes
Here are some of the things that I have yet to achieve for this kit, either due to a lack of time or features on Adobe's part. 

* Proper layer naming - At least for myself, I realised that this is not a key issue when navigating Adobe XD. 

* Better "CSS" - I try to refer to the Carbon Components on CodePen/ Carbon Design Website for the most accurate padding and spacing of the components. This is an on-going process especially for some of the more complex components such as the Calendar. 

* Reusable Colors & Symbols - Until Adobe releases a better way to maintain the Swatches and Symbols for Adobe XD, this will be quite a mess to maintain. Hopefully there will be a way to arrange the colors by shades eventually. In the interim, I aim to make sure that the colors across the entire kit is consistent.

* Icon Libraries - You will have to download them off the Carbon Design site for now

* Text Styles - Same with reusable colors and symbols, it's a nightmare to maintain

## Other Updates

- [x] Added z-depth layer sheet (06/03/18)
![layer types](https://user-images.githubusercontent.com/25948209/37008015-18d7e888-211b-11e8-94ab-d5552a0f40af.png)
- [x] Changed all of the red to #E0182D
- [x] Added Interior Left Nav (06/03/18)
![interior left nav](https://user-images.githubusercontent.com/25948209/37032407-6312c85c-217d-11e8-9d65-ad0d801c8592.png)
- [x] Updated tags (06/04/18)
Reduced the height of the tags from `30px` -> `20px`.

**Comment by havesomeleeway** [comment]
@tay-aitken 👋 here

**Comment by tay-aitken** [comment]
Hey Lee! Will take a look at this today/tomorrow! Thanks again for sharing it!

**Comment by Brun0fl** [comment]
Very nice, thanks a lot for sharing!

**Comment by tay-aitken** [comment]
Hi @havesomeleeway! Wow this looks great! (sorry it took me so long to get back to you). Ill share this with the rest of the team and let you know the thoughts :)

**Comment by havesomeleeway** [comment]
Actually, that happened to be an oversight. I've since referenced http://carbondesignsystem.com/components/tag/code and made the necessary [changes](https://xd.adobe.com/spec/1f560469-37bd-44ca-931b-c03dfdd80b55/#screen/48bfee6a-7b51-45fb-9c92-7dad99b1ee30/Tag).

**Comment by havesomeleeway** [comment]
@tay-aitken I understand that there is an updated kit in Sketch. The April update to Adobe XD brought more stability to the Sketch -> Adobe XD import functionalities. I will have to take some time to see if it works better than what it did in March. 

If it does, it'll better allow me to maintain consistency between the Sketch and the XD kit.

**Comment by tay-aitken** [comment]
Nooooo, was that die to the update? I will try opening it as well!
