### ISSUE TITLE
[Text input] vertical scaling + smart layout

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#362]
Pinning the text input component needs to be revisited, right now it is a bit broken. It is not a big problem as horizontal scaling is most important and this works fine. Fixing this will lay a base for smart layout for error states and long hint texts.

### Scaling and smart-layout

**White** (all sizes)
- [x] Label only
- [x] Label + helper text
- [x] No label
- [x] Password - label only
- [x] Password - label + helper text

**Gray 10** (all sizes)
- [x] Label only
- [x] Label + helper text
- [x] No label
- [x] Password - label only
- [x] Password - label + helper text

**Gray 90** (all sizes)
- [x] Label only
- [x] Label + helper text
- [x] No label
- [x] Password - label only
- [x] Password - label + helper text

**Gray 100** (all sizes)
- [x] Label only
- [x] Label + helper text
- [x] No label
- [x] Password - label only
- [x] Password - label + helper text

<img width="682" alt="image" src="https://user-images.githubusercontent.com/12408951/92991166-1fb58f00-f4e2-11ea-99b2-8ccab982288f.png">

**Comment by mariuszmickiewicz** [comment]
All types and sized for Gray 10 done.

**Comment by laurenmrice** [comment]
finished ! will be in the next kit update 🎉
