### ISSUE TITLE
[Tooltip] Sketch kit and code example vary in color for dark themes

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#363]
In Dark themes:
tooltip / interactive tooltip in Sketch kit 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/12408951/93115812-b178f400-f6bc-11ea-9d90-b2de157806b7.png">

interactive example / code on the site
<img width="353" alt="image" src="https://user-images.githubusercontent.com/12408951/93115872-c6558780-f6bc-11ea-96f0-bc5fde03a31f.png">

Which one is the correct?

ps. button in the code seems to be broken

**Comment by laurenmrice** [comment]
It should be the first one that is in the sketch kit. It needs to be a high contrast moment. I will make a bug issue in our carbon repo.

**Comment by laurenmrice** [comment]
I checked the code in the dark themes and it appears to be correct.
