### ISSUE TITLE
[Tab] Add "light" variant

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#366]
![image](https://user-images.githubusercontent.com/11670886/94292428-f279cf80-ff2a-11ea-9384-040dd8a99b89.png)

**Comment by laurenmrice** [comment]
- [x] White theme
- [ ] Gray 10 theme (in progress)
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Added! Will be available in the next update. 🎉
