### ISSUE TITLE
[multi-select] visual number's position inside the interactive tag

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#369]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/12408951/95077577-00da9f00-0714-11eb-9618-0f8470f0fcd3.png">

Mathematically everything is correct, but visually number inside the interactive tag seems to be lower than the X icon. 
I would ignore the math here and make it visually more pleasing (1 px higher). Yes, the base line with the "filters are selected" won't be the same, but this is much less visible alignment.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/12408951/95077844-75154280-0714-11eb-9b17-661a846da116.png">

**Comment by jillianhowarth** [comment]
@mariuszmickiewicz are you still seeing this bug in sketch? I took a look this morning and the number and icon are visually aligned for me.

**Comment by mariuszmickiewicz** [comment]
@jillianhowarth Seems fine now. Thanks
