### ISSUE TITLE
Space between inputs in form symbol should be layout-02

### ISSUE THREAD

**Issue by grahamharper** [carbon-design-system/carbon-design-kit#370]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?
10.20.0

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Form symbols e.g.
- form / on page / two column
- form / on page / single column
- form / modal / single button

> What did you expect to happen? What happened instead? What would you like to see changed?
Space between inputs should be `layout-02` but is currently `layout-03`

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
Yes.

According to the docs site the space between inputs in a form should be `layout-02`

https://www.carbondesignsystem.com/components/form/style#structure

![image](https://user-images.githubusercontent.com/2853295/95087202-506f9980-0719-11eb-889e-49f6dfff23f3.png)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Add one of the theme design kits
2. Insert a form symbol such as `form / on page / single column`

## Additional information

Screenshot of symbol in a Sketch doc:
![Screenshot 2020-10-05 at 14 39 14](https://user-images.githubusercontent.com/2853295/95087657-e1df0b80-0719-11eb-928a-f34708652834.png)

**Comment by mariuszmickiewicz** [comment]
This section should clarify in more details form layouts:
https://www.carbondesignsystem.com/patterns/forms-pattern#spacing

**Comment by laurenmrice** [comment]
By default vertical space between form inputs should be 32px `layout-03`. We need to update this to be reflected in that image on the style page. 24px is fine too if you are tight on space, but we recommend using 32px when possible.

**Comment by grahamharper** [comment]
Thanks for the clarification.
