### ISSUE TITLE
[link] add size variations

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#373]
Add sizes variations:
- 12px
- 16px

(add to symbol and text style)

**Comment by laurenmrice** [comment]
- [x] Text styles
- [ ] Symbols

**Comment by laurenmrice** [comment]
Symbols
- [x] White theme
- [x] Gray 10 theme (in progress)
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Added ! Will be available in the next update 🎉
