### ISSUE TITLE
[type styles] update heading-03 line height

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#375]
Update `heading-03` line height to have 28px instead of 26px. 

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme
- [x] IDL kit

**Comment by mariuszmickiewicz** [comment]
Done in IDL v2 for productive and all expressive styles.

**Comment by laurenmrice** [comment]
Updated! Will be in next update 🎉
