### ISSUE TITLE
[button] update hover/active text color for ghost buttons in dark themes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#378]
The hover and active state text color in the dark themes for ghost button are the wrong value.

They currently show up as the link color (Blue 40) but they should be `hover-primary-text` (Blue 30, #a6c8ff)
![Artboard](https://user-images.githubusercontent.com/43969356/96626302-5189f480-12dd-11eb-83d1-a5be59024c79.png)

**Comment by mariuszmickiewicz** [comment]
- [ ] Gray 90
- [ ] Gray 100
