### ISSUE TITLE
Detail Header - breadcrumb

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon-design-kit#38]
version 8.1.0

Can't switch out the truncated option for a normal row item without breaking from the library. 

In our situation we are only 2 deep currently residing on a Production Cluster page: Clusters / Production Cluster

I broke everything in order to accomplish the mock up below:
<img width="965" alt="screen shot 2018-03-13 at 4 59 04 pm" src="https://user-images.githubusercontent.com/19826147/37372190-ed69c3b8-26df-11e8-8b44-494553363de1.png">

Also, our understanding is that the current page would be repeated in the breadcrumb in grey and not followed by a slash to show the current location - might be a conversation to have with Platform, but I think that is where they landed with their recent updates for the interior left nav and breadcrumb work.

**Comment by tay-aitken** [comment]
@SpencerReynolds18 did you try building the breadcrumb with the 'pieces' section as opposed to the enabled symbol?

**Comment by tay-aitken** [comment]
@SpencerReynolds18 following up on this to close—on closer inspection I am going to recommend you set breadcrumbs (or tabs) to none in the overrides panel. Then use the insert symbol menu to access the pieces fly-out under the respective components to add in customization. Hope this helps. Thanks for making an issue :)

![screen shot 2018-05-07 at 11 42 32 am](https://user-images.githubusercontent.com/29312997/39713258-caed622c-51eb-11e8-939c-c86f3b56656a.png)

Mobile breadcrumb set to 'none' in the overrides panel.
![screen shot 2018-05-07 at 11 42 41 am](https://user-images.githubusercontent.com/29312997/39713265-cf84292e-51eb-11e8-9a92-e261e508309c.png)

![screen shot 2018-05-07 at 11 42 49 am](https://user-images.githubusercontent.com/29312997/39713283-dcede212-51eb-11e8-8fc9-4c972a2c81de.png)

**Comment by tay-aitken** [comment]
@SpencerReynolds18 following up on this to close—on closer inspection I am going to recommend you set breadcrumbs (or tabs) to none in the overrides panel. Then use the insert symbol menu to access the pieces fly-out under the respective components to add in customization. Hope this helps. Thanks for making an issue :)

![screen shot 2018-05-07 at 11 42 32 am](https://user-images.githubusercontent.com/29312997/39713258-caed622c-51eb-11e8-939c-c86f3b56656a.png)

Mobile breadcrumb set to 'none' in the overrides panel.
![screen shot 2018-05-07 at 11 42 41 am](https://user-images.githubusercontent.com/29312997/39713265-cf84292e-51eb-11e8-9a92-e261e508309c.png)

![screen shot 2018-05-07 at 11 42 49 am](https://user-images.githubusercontent.com/29312997/39713283-dcede212-51eb-11e8-8fc9-4c972a2c81de.png)
