### ISSUE TITLE
[checkbox] update icon background/border color to icon-01

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#381]
The checkbox background and border colors should be `icon-01` not ui-05.

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

**Comment by mariuszmickiewicz** [comment]
* Fixed Gray 10
* Updated some base icons to come from Icon library, not IDL.
* Updated check boxes in "item" symbols to use local states, instead of IDL icons.
