### ISSUE TITLE
[modal] 3 button modal footer (alt version)

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#382]
Could we add this modal footer to the kits?
This would require adding ghost buttons too.

![image](https://user-images.githubusercontent.com/12408951/97179857-9d371500-1799-11eb-9883-0d2b815fac86.png)

**Comment by laurenmrice** [comment]
Yes! We can add this in the kits once it is in code. Modal button issue: https://github.com/carbon-design-system/carbon/issues/4607

- [ ] In code

--------

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by aagonzales** [comment]
Sketch is no longer a priority design tool for IBM and we are closing all feature updates as not planned.
