### ISSUE TITLE
[content switcher] audit bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#385]
- [x] Missing a `selected + focus` state
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
![image](https://user-images.githubusercontent.com/11670886/97922844-b6543e80-1d22-11eb-8108-b258ea8e488a.png)
- [x] Missing `light` variant, ie override to change the background color.
    - [x] White theme 
    - [x] Gray 10 theme 
    - [x] Gray 90 theme 
    - [x] Gray 100 theme (in progress)

**Comment by laurenmrice** [comment]
Added! Will be in the next update 🎉
