### ISSUE TITLE
No background color for tile / clickable / 01 enabled

### ISSUE THREAD

**Issue by jan-christensen1** [carbon-design-system/carbon-design-kit#387]
## Brief description

The background color of the Sketch symbol for clickable tiles is wrong. It's transparent even though "field-01" is selected as default background color. When I select "field-01" again, the correct background color is displayed

## Detailed description

The Sketch symbol is part of the Carbon Design System (Gray 10 Theme) library. When I drop the symbol to the artboard it doesn't have any background color, it's totally transparent. But in the Overrides panel the default is set at "field-01". When I expand the dropdown and select this layer-stile again, the correct background-color is displayed
![image](https://user-images.githubusercontent.com/65981991/98220911-47a7f880-1f4f-11eb-88a0-487b7a6afa2f.png)

![image](https://user-images.githubusercontent.com/65981991/98220642-e1bb7100-1f4e-11eb-9032-dfc338ab04cf.png)

> What version of the Carbon Design System Kit are you using?

I believe I have the latest version, updated 2. October 2020

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

tile / clickable / 01 enabled

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the symbol to have a background color when I drop it on the artboard. The default is "field-01" and I would like the symbol to actually have that background-color, without needing to select it again. I have many instances of this symbol in my screens and this would mean a  lot of manual labor to change all of them by hand.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I'm working on HPCS on IBM Cloud

## Steps to reproduce the issue

1. Insert tile / clickable / 01 enabled to any artboard with a background color
2. Observe how the symbol doesn't have any background-color
3. Select "field-01" in the Overrides panel again
4. Observe how the symbol shows the correct background-color now.

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by jan-christensen1** [comment]
Sorry, couldn't figure out how to add labels here.

**Comment by mariuszmickiewicz** [comment]
@jan-christensen1 
I can't reproduce this issue, what version of Sketch do you have?

What worries me a bit that on your screenshot this symbol has a "choose image" override available, no idea where this comes from.

**Comment by jan-christensen1** [comment]
@mariuszmickiewicz Thx for looking into it. I just updated to the latest Sketch version. I've been on 69, now I'm on 69.2. After the update I was prompted with a Shared Library update and that resolved the issue. Maybe this had to do with the update to Color variables? The issue can be closed.
