### ISSUE TITLE
Categories for the component page of the Kit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#39]
### 01 Controls:
- Button
- Checkbox
- Content switcher?
- Overflow menu
- Radio Buttons
- Slider
- Toggle

### 02 Inputs:
show both field-01 and field-02?
- Date Picker
- Dropdown 
- File uploader
- Forms
- Number input
- Search
- Select
- Text input

### 03 Content:
- Accordion
- Code snipper
- Data table?
- List
- Loading?
- Modal
- Notification
- Structured List
- Tags
- Tile
- Tooltip

### 04 Navigation:
- Breadcrumb
- Links
- Pagination
- Progress Indicator
- Tabs

### 05 Data table 
(as its own category)

**Comment by aagonzales** [comment]
**To do:** let's check and see how Peretz divides there components up before we start to see if we can get some symmetry going.

**Comment by mediengestalter2** [comment]
Guten Tag,

ich bin bis 04. Juni nicht erreichbar. Ihre Nachricht wird danach schnellstmöglich beantwortet.


	
		
      
	      Beste Grüße,Moritz Graf
	    
      
	      
		      
					Moritz Graf
          Mediengestalter 	— schwäbische Art
        
        Dorfstraße 789150 Laichingen
				
					
						
							T
              +49 7333 2038870
            
            
              F
              +49 7333 2038879
            
            
               
              www.moritz-graf.de
						
						
							 
              Ust-IdNr: DE280427588
            
          
        
      
    
    
      
        
          
            
              Diese Nachricht muss vertraulich behandelt werden. Falls Sie diese Nachricht irrtümlicherweise erhalten haben, benachrichtigen Sie uns bitte und löschen Sie diese Nachricht.
            
            
              Diese Nachricht wird wenn möglich durch ein Sicherheitszertifikat signiert. Nach Möglichkeit werden Nachrichten verschlüsselt versandt. Für weitere Informationen kontaktieren Sie mich bitte.

**Comment by aagonzales** [comment]
Done! Changes made to V9 WIP kit file.
