### ISSUE TITLE
[Data table] protect icon in action bar buttons from color switching

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#390]
Add a tint (which links to IDL2 library color variable) to protect icons from switching back to black on icon change.

White

- [x] Enabled states 
- [x] Disabled state

Gray 10

- [x] Enabled states
- [x] Disabled state

Gray 90

- [x] Enabled states
- [x] Disabled state

Gray 100

- [x] Enabled states
- [x] Disabled state

**Comment by laurenmrice** [comment]
Fixed! Will be available in the next update. 🎉
