### ISSUE TITLE
[Multi select] Inconsistent spacing between closed multi-select and open multi-select dropdown in White theme

### ISSUE THREAD

**Issue by nathaniel-qin** [carbon-design-system/carbon-design-kit#391]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

### What version of the Carbon Design System Kit are you using? 
Last updated 1 minute ago.

### Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Carbon Design System (White theme) / dropdown / 03 multi-select / medium / 01 label / regular / closed
Carbon Design System (White theme) / dropdown / 03 multi-select / medium / 01 label / regular / open

Carbon Design System (White theme) / dropdown / 03 multi-select / medium / 01 label / filterable / closed
Carbon Design System (White theme) / dropdown / 03 multi-select / medium / 01 label / filterable / open

### What did you expect to happen? What happened instead? What would you like to see changed?
I expected both components to have the same spacing between the label and the dropdown, but it's 8px when closed and 5px when opened.

### Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?
No

### What offering/product do you work on? Any pressing ship or release dates we should be aware of?
HDM > Db2. No 

## Steps to reproduce the issue

1. Find the components in the Carbon Design System (White theme) sketch kit.
2. Observe the inconsistent spacing

## Additional information
![image](https://user-images.githubusercontent.com/33332345/99709001-7647c800-2a53-11eb-8d3b-e14055f5ce9f.png)
![image](https://user-images.githubusercontent.com/33332345/99712764-5a92f080-2a58-11eb-8cad-2da6f321a646.png)

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
I checked all themes and fixed the label spacing bugs 👍🏻. Will be in the next update.
