### ISSUE TITLE
[date picker] audit bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#393]
Bugs
- [x] updated placeholder text from `text-03` to `text-05` in all pickers. [PR](https://github.com/carbon-design-system/carbon/pull/4799)
- [x]  Duplicate "placeholder" layers
![image](https://user-images.githubusercontent.com/11670886/100018623-5e997800-2da2-11eb-87d5-85dcff881529.png)
- [x] Capital `Year` should be lower case
![image](https://user-images.githubusercontent.com/11670886/100024057-b5577f80-2dab-11eb-925e-aa6e5314050b.png)

**Comment by laurenmrice** [comment]
Fixed! Will be available in the next update 🎉
