### ISSUE TITLE
Include a data table 'column' component for selectable cells

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-design-kit#397]
The "column" component is very useful when mocking up large data tables since it removes the need to drag out many data cells.

![image](https://user-images.githubusercontent.com/51379566/102276459-d1ef5f00-3ef4-11eb-80a9-7f8733a8a030.png)

However where this falls alittle short is a version that includes 'Selectable' cells (and/or possibly collapsible).  In the past I've used one of these and converted each cell to selectable, which was ok, but today when I had to switch themes I had to again adjust each cell 1 by 1. Doable, but not fun.

![image](https://user-images.githubusercontent.com/51379566/102277011-ad47b700-3ef5-11eb-9ecf-bf4b2d5bf0de.png)

**Comment by kylearichard** [comment]
I'd like to second this, and also add that it would be helpful to have columns for expandable rows as well!

**Comment by laurenmrice** [comment]
- [x] White theme
- [x] Gray 10 theme (in progress)
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Added! Will be available in the next update. 🎉
