### ISSUE TITLE
[modal] resize height / overrides bug 

### ISSUE THREAD

**Issue by kylearichard** [carbon-design-system/carbon-design-kit#398]
## Detailed description

In the latest version of the Sketch kit, the modal components don't honor the height that is set by the designer when any one of the overrides are edited. This bug is present on all 4 theme kits, in all modal widths. See below:

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/59894790/102277607-6221aa00-3edd-11eb-8012-fb342e590b16.gif)

My expectation is that the height value would be persisted (or, if needed, would bump out to accommodate additional lines of text) whenever overrides are changed. The bug adds a bit of extra design time, as I need to re-input the height for the modal component on any instance where the overrides need to change.

## Steps to reproduce the issue

1. Configure the overrides for title, description, and button labels on a modal component
2. Resize the height of the modal
3. Edit one of the overrides

The height will snap back to the default value from when it was dropped onto the artboard.

**Comment by aagonzales** [comment]
Sketch is no longer a priority design tool for IBM and we are closing all feature updates as not planned.
