### ISSUE TITLE
[Select] - small version label text resize

### ISSUE THREAD

**Issue by Ivan-Bachev** [carbon-design-system/carbon-design-kit#399]
**Description**

The small version of the "Select" component (Gray 10 theme - "select / default / small /  01 enabled") doesn't scale the label properly when an override is used.
 
<img width="688" alt="Screen Shot 2020-12-16 at 10 54 08" src="https://user-images.githubusercontent.com/70877374/102326787-850b9700-3f8d-11eb-9553-b01d8a0c91e3.png">

The issue is most probably due to the "Auto Height" setting assigned to the label, which sets a fixed width to the text layer.

<img width="961" alt="Screen Shot 2020-12-16 at 10 53 59" src="https://user-images.githubusercontent.com/70877374/102326794-889f1e00-3f8d-11eb-9f30-9213730841ba.png">

**Comment by laurenmrice** [comment]
Fixed! Will be in the next update 🎉
