### ISSUE TITLE
No Global Header for Catalog

### ISSUE THREAD

**Issue by rossfenrick** [carbon-design-system/carbon-design-kit#4]
Catalog has it's own color and should have it's own header in the design kit

<img width="699" alt="screen shot 2017-05-03 at 3 06 48 pm" src="https://cloud.githubusercontent.com/assets/7506366/25679378/be1c3268-3012-11e7-9627-d6e6c64ec0be.png">

**Comment by rossfenrick** [comment]
Also if you notice, in the very top header, the hamburger menu is missing

**Comment by aagonzales** [comment]
Thanks @rossfenrick ! I'll add the catalog header to the header page. And the top one is a base symbol for the rest of the headers, its not a state. Though I guess we don't have to surface it, since it lives on the symbols page 🤔

**Comment by aagonzales** [comment]
Updated with 7.1.0 Release
