### ISSUE TITLE
Validation symbol still uses Helvetica instead of Plex

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-design-kit#40]
@werdnanoslen commented on [Thu May 10 2018](https://github.com/carbon-design-system/carbon-components/issues/760)

The `Component/Select/Select/States/Validation` symbol still uses Helvetica instead of Plex.

![image](https://user-images.githubusercontent.com/764090/39884593-5abf5b94-5458-11e8-936b-04b9fc220e79.png)

---

@werdnanoslen commented on [Thu May 10 2018](https://github.com/carbon-design-system/carbon-components/issues/760#issuecomment-388130027)

Also I think the character spacing should not be 0.5 in Plex? Looks weird with it

**Comment by tay-aitken** [comment]
This has been fixed in the latest version of the kit (will be released by the end of this month). Thanks for making an issue and bringing it to our attention.
