### ISSUE TITLE
[Text style] Add link color variant to the label text style 

### ISSUE THREAD

**Issue by dianatran18** [carbon-design-system/carbon-design-kit#400]
Within the Carbon for Cloud & Cognitive PAL and the AI Applications PAL, we're aligning on using a smaller breadcrumb size (12px) than the default one in Carbon today (14px). The way we're achieving this is by using the label text style and changing the color to Blue 60.

<img width="1056" alt="Screen Shot 2020-12-16 at 12 09 41 PM" src="https://user-images.githubusercontent.com/43549567/102381739-9659a100-3f97-11eb-8ce5-90e095baf233.png">

Would it be possible to add in a link text style variant to `label01`?

<img width="609" alt="Screen Shot 2020-12-16 at 12 13 52 PM" src="https://user-images.githubusercontent.com/43549567/102382201-2c8dc700-3f98-11eb-92a5-761c3a294d0b.png">

**Comment by dianatran18** [comment]
The 12px link text option would also be valuable for situations such as Forgot ID on the login pattern

<img width="474" alt="Screen Shot 2020-12-16 at 3 17 01 PM" src="https://user-images.githubusercontent.com/43549567/102401750-ca41c000-3fb1-11eb-90f8-7064c9da553c.png">

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by mariuszmickiewicz** [comment]
@laurenmrice Whn you create this text style please use a color variable from IDL v2 library at its base.

**Comment by laurenmrice** [comment]
-Added with color variables from IDL v2 library. Will be in the next update. 🎉
-Also added a link color to body-short-02 since we offer that in code.
