### ISSUE TITLE
[Date picker] - Error state

### ISSUE THREAD

**Issue by Ivan-Bachev** [carbon-design-system/carbon-design-kit#401]
On the error state of the Date picker component symbol the "calendar" icon is not shown -  is this intentional?

Here is a side by side comparison of error state symbols for the Date picker and the Dropdown components 

![Carbon - error state comparison@2x](https://user-images.githubusercontent.com/70877374/102601286-9dfc7f80-4128-11eb-94f3-69c4d693fa25.png)

Given that the behavior of both components is similar _(in terms of opening a "menu" where a selection is made)_, shouldn't we show the calendar icon in the Date picker error state?

![Carbon - Date picker - error state with calendar icon@2x](https://user-images.githubusercontent.com/70877374/102601861-65a97100-4129-11eb-8de2-b3a106684fb8.png)

**Comment by aagonzales** [comment]
This is intentional and to spec.
