### ISSUE TITLE
Medium no label dropdown - enabled state missing in the Sketch kit

### ISSUE THREAD

**Issue by assiroud** [carbon-design-system/carbon-design-kit#402]
## Detailed description

The enabled state doesn't appear on the pattern list

> The kit was last updated on Updated on Dec 17

## Additional information

* Screenshots or Sketch file links
* Notes
![image](https://user-images.githubusercontent.com/24441071/102817981-c097ce00-439e-11eb-8435-a696266b8966.png)

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by laurenmrice** [comment]
I checked all of the theme master files and they all have the enabled state for this dropdown. I would make sure your sketch version is up to date. This could possibly be a sketch bug.

<img width="1221" alt="Screen Shot 2021-01-04 at 9 32 12 AM" src="https://user-images.githubusercontent.com/43969356/103551276-bc27e680-4e6f-11eb-8cf4-2ae02fc87e62.png">

**Comment by assiroud** [comment]
Hi Lauren,

Thanks for following up. It's really a bizarre case of a bug (sounds like the new version of Sketch is ridden with them). In the updated version of the Gray 10 theme the enabled state for the medium dropdown now appears outside of the states list
![image](https://user-images.githubusercontent.com/24441071/103555448-4e36eb80-4e7e-11eb-9c85-5e7e43ee5cd3.png)

**Comment by assiroud** [comment]
Hi Lauren,
It's perfect now. Thank you for fixing it! 💯 
![image](https://user-images.githubusercontent.com/24441071/104933403-dcc76480-5976-11eb-80dd-195af968defb.png)
