### ISSUE TITLE
[inline loading] spinner color incorrect

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#403]
The background of the spinner should be `ui-03`. It currently is `#D8DCE3`

**Comment by laurenmrice** [comment]
- [x] White theme (in progress)
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Will be in the next update 🎉
