### ISSUE TITLE
[Button groups] ordering

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon-design-kit#407]
In TRIRIGA we have cases where there are multiple button groups shown on a screen and we are trying to achieve consistency in the button ordering for these groups.

We follow the guidelines from Carbon and AI Apps PAL 
https://www.carbondesignsystem.com/components/button/usage/
https://pages.github.ibm.com/ai-applications/design/components/fixedbuttonbar/usage/

In the following example you can see the discrepancies in ordering of the primary/secondary buttons:

- Page header buttons: secondary button first, primary button second
- Master/Detail fixed button bar: primary button first, secondary button second
- Modal: secondary button first, primary button second

![Example - Data modeler - Business object - Field properties - Browser Window XL Size@2x](https://user-images.githubusercontent.com/1560160/105957917-919e0780-6082-11eb-9618-2e6cc046302f.png)

We would like to ask for a guideline how to approach such cases.

**Comment by aagonzales** [comment]
Closing as this is not a kit issue and is redundant in the website repo.
See related issue: https://github.com/carbon-design-system/carbon-website/issues/2672
