### ISSUE TITLE
[modal] audit bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#409]
- [ ] Close should be a button icon. Currently missing ability to turn on hover for close.
![image](https://user-images.githubusercontent.com/11670886/106655074-e354ff00-6566-11eb-8a17-38af1cecd878.png)

- [ ] Missing fade feature for scrolling content.
![image](https://user-images.githubusercontent.com/11670886/106659281-83615700-656c-11eb-9dd0-ac3643124445.png)

**Comment by jillianhowarth** [comment]
- [ ] White (in progress)
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by jillianhowarth** [comment]
The modal updates will be available in the next kit update 🎉
