### ISSUE TITLE
[overflow menu] add smart layout to the group symbol

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#411]
Currently symbol needs to be detached in order to use less than 4 options for the menu. 

It would be more flexible to allow for some items to be removed. Other option would be to provide separate symbols (1, 2, 3, 4 etc.) as it is a case with some other components.

**Comment by aagonzales** [comment]
I was working on adding in the sizes for overflow menu and went added the auto layout feature and a groups for 4, 8, and 12 items. 

- [ ] White
- [ ] G10
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Updates made to the version saved on box. Will be pushed live with v11 release
