### ISSUE TITLE
[content switcher] update design for 3:1 contrast

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#412]
- [x] In code

----

- Unselected sections and unselected-disabled sections now have a `transparent` background.
- Whole content switcher container receives a 1px, `ui-05` border.
- Divider rule is 16px high and stays `ui-03`. 
- Add `disabled + selected` state to content switcher.

Ref: https://github.com/carbon-design-system/carbon/issues/6745#

----

![lg-1056px-16 column](https://user-images.githubusercontent.com/43969356/114411911-3d2f0200-9b72-11eb-8c61-e627ba64aa4a.png)

**Comment by jillianhowarth** [comment]
- [ ] White (in progress)
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by jillianhowarth** [comment]
The content switcher changes will be available in the next kit update 🎉
