### ISSUE TITLE
Inline notification Layout bug

### ISSUE THREAD

**Issue by yumeforever** [carbon-design-system/carbon-design-kit#413]
## Detailed description

The default inline notifications in Gray100 and Gray 90 are having problems have problems with layout when overwriting the title text:

<img width="1305" alt="CleanShot 2021-03-19 at 14 43 03@2x" src="https://user-images.githubusercontent.com/3612533/111789865-e5c6aa80-88c1-11eb-8259-58bfb50cf8d7.png">

![image](https://user-images.githubusercontent.com/3612533/111793038-24aa2f80-88c5-11eb-906d-2c5193fb0efb.png)

![image](https://user-images.githubusercontent.com/3612533/111793115-3986c300-88c5-11eb-97c8-d84ff7263d16.png)

I believe the fix is to create the same group for the title and description adding as horizontal layout as in the Gray10 notification:

<img width="1050" alt="CleanShot 2021-03-19 at 14 44 53@2x" src="https://user-images.githubusercontent.com/3612533/111789979-03940f80-88c2-11eb-830a-54371bdbac30.png">

## Steps to reproduce the issue

1. add default inline notification from Gray100 or 90 to artboard
2. overwrite the title text

**Comment by laurenmrice** [comment]
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by jillianhowarth** [comment]
Fixed the inline notification bug in the Gray 90 and Gray 100 themes. The fix will be available in the next kit update 🎉
