### ISSUE TITLE
[pagination] add smart layout

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#414]
Add smart layout for pagination to display various numbers correctly.
Currently, two and three digits numbers are used and when replaced with smaller ones it produces too much unnecessary spacing.

**Current state**

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/12408951/112023070-2e38cf00-8b33-11eb-889a-d3fb7ea32cc0.png">

**Progress**
- [ ] White
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100

**Comment by aagonzales** [comment]
Sketch is no longer a priority design tool for IBM and we are closing all feature updates as not planned.
