### ISSUE TITLE
[data table] skeleton needs some visual adjustments

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#415]
1. button in the skeleton tool bar is 46px high, instead of 48.
2. "text's" height (gray rectangle) in skeleton's row is not matching what's implemented - no sure which one is the correct one. Personally I like the kit's version, it is much more subtle. Code's one combined with everything animation can be a bit overpowering for a skeleton state. At first, I thought the code is keeping the same height as the text's line-height, but this doesn't seem to be the case.
3. Code shows the labels in the table header, Sketch kit doesn't.
4. Table cell symbols could have the skeleton state added and then these could be used here in the big skeleton component.

1
<img width="320" alt="image" src="https://user-images.githubusercontent.com/12408951/112290252-55a4ae80-8c8f-11eb-9caa-1e44946d2b31.png">

2 and 3

Code
<img width="417" alt="image" src="https://user-images.githubusercontent.com/12408951/112290418-7ff66c00-8c8f-11eb-95ab-c8f448721d6d.png">

Sketch kit
<img width="314" alt="image" src="https://user-images.githubusercontent.com/12408951/112290480-8e448800-8c8f-11eb-8176-c67d57c288e3.png">

**Comment by aagonzales** [comment]
Sketch is no longer a priority design tool for IBM and we are closing all feature updates as not planned.
