### ISSUE TITLE
[toggle] needs a bit better resize handling

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#416]
Toggles would need a bit better resize handling. When those are embedded inside symbols using smart layout it might lead to undesired effects.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/12408951/112640500-aeb44400-8e41-11eb-98c0-d5e1b9f31b52.png">

**Comment by laurenmrice** [comment]
- [x] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Fixed! Will be available in the next update. 🎉
