### ISSUE TITLE
[date picker] 1px space between data range picker inputs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#417]
- Need to have `1px space` between data range picker inputs. Right now it is 2px and is inconsistent with time picker. This also follows the spacing of the condensed grid gutter

<img width="599" alt="Screen Shot 2021-04-01 at 3 52 06 PM" src="https://user-images.githubusercontent.com/43969356/113357197-33eb9d00-9309-11eb-9c87-aa65fd19bbe7.png">

-----

Ref [8234](https://github.com/carbon-design-system/carbon/issues/8234)

**Comment by aagonzales** [comment]
Sketch is no longer a priority design tool for IBM and we are closing all bug updates as not planned.
