### ISSUE TITLE
Adobe XD Icon kit 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#419]
Thy and Lauren are working on updating the icon kit for Adobe Xd before announcing the release for 4 themes.

**Comment by laurenmrice** [comment]
- [ ] Make list of all icons added to the system since December 2019 (in progress)
- [ ] Add in all icons to XD from list^
- [ ] Remove duplicate icons in XD
- [ ] Make all icon sizes into states. 16px will be the default component
- [ ] Organize icons into sub category artboards

**Comment by laurenmrice** [comment]
Oh hold until v11 release is done.
