### ISSUE TITLE
[Date picker] - Background overrides

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon-design-kit#423]
## Detailed description

The Date picker open state component in the Sketch library is not constructed in a way to allow overriding the “Previous month” and “Next month” buttons backgrounds. As a result there is no way to properly set the open state with a grey background to match the input background.

<img width="2672" alt="Screen Shot 2021-04-16 at 9 07 43" src="https://user-images.githubusercontent.com/1560160/115185596-cf8e5300-a0e8-11eb-9d60-876751ebc5db.png">

> What version of the Carbon Design System Kit are you using?

Gray 10 theme

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

component: Date picker
symbol: _"date picker / 02 single date calendar / medium / open"_

> What did you expect to happen? What happened instead? What would you like to see changed?

The following symbols should either have their background available as overrides:
_"date picker / pieces / previous month / 01 enabled"_
_"date picker / pieces / next month / 01 enabled"_

or set with a transparent background to match the "date picker / pieces / calendar" background.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

The website live demo is incorrectly showing the Date picker open state with a white background when the input is grey
https://www.carbondesignsystem.com/components/date-picker/usage/

<img width="1635" alt="Screen Shot 2021-04-16 at 9 03 53" src="https://user-images.githubusercontent.com/1560160/115186056-af12c880-a0e9-11eb-8352-99c32ee94237.png">

It should match the React Storybook correct example where both the input and the open calendar are using the same background color.
https://react.carbondesignsystem.com/?path=/story/components-datepicker--single

<img width="1185" alt="Screen Shot 2021-04-19 at 8 31 30" src="https://user-images.githubusercontent.com/1560160/115186095-bdf97b00-a0e9-11eb-9977-be3fd8d2ab86.png">

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

IBM TRIRIGA

**Comment by laurenmrice** [comment]
This has been resolved, going to close.
