### ISSUE TITLE
v11: [button] change sizes to reflect new size prop naming

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#427]
Sizes should be as follows:

![Artboard](https://user-images.githubusercontent.com/43969356/115468001-04d59680-a1f8-11eb-8dd9-31424ff9519b.png)

**Comment by mariuszmickiewicz** [comment]
These seem to be added to all libraries already (not published).

**Comment by laurenmrice** [comment]
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Updated! Will be available in the v11 release 🎉
