### ISSUE TITLE
[toggle] update disabled state

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#428]
- Update latest design spec for toggle. 

-----

<img width="804" alt="Screen Shot 2021-04-28 at 11 26 31 AM" src="https://user-images.githubusercontent.com/43969356/116430163-365bec80-a80c-11eb-9d39-bbf9c0900d67.png">

**Comment by jillianhowarth** [comment]
The toggle disabled states have been updated and will be in the next available in the next kit update 🎉
