### ISSUE TITLE
v11: update Adobe XD kit with new color tokens

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#430]
Update the XD kit to use the [new color tokens](https://www.notion.so/carbondesignsystem/Final-List-of-new-tokens-fc5985c7331341baa6546064399d36da).

**Do not push update until the v11 release.**

**Comment by laurenmrice** [comment]
- White theme
  - [ ] Update tokens
  - [ ] Update Elements artboard

- Gray 10 theme
  - [ ] Update tokens
  - [ ] Update Elements artboard  

- Gray 90 theme
  - [ ] Update tokens
  - [ ] Update Elements artboard  

- Gray 100 theme
  - [ ] Update tokens
  - [ ] Update Elements artboard

**Comment by laurenmrice** [comment]
Updated! Will be available in the next kit update for v11. 🎉
