### ISSUE TITLE
[overflow menu] add md and lg sizes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#436]
- Add md (40px) and lg (48px) sizes to the overflow menu component

----

![Artboard](https://user-images.githubusercontent.com/43969356/119184088-89efdd80-ba3a-11eb-80c7-1b000e7b2033.png)

**Comment by aagonzales** [comment]
- [ ] White 
- [ ] G10
- [ ] G90
- [ ] G100

**Comment by aagonzales** [comment]
Updates made to the version saved on box. Will be pushed live with v11 release
