### ISSUE TITLE
[type styles] add the expressive type styles

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#437]
## Detailed description

The Carbon for IBM.com team and all dotcom designers will be transitioning to use the Carbon design kits as we integrate the Expressive variants needed into Carbon.The designers will need access to the expressive type styles, which were previously provided through the [Carbon Expressive kits](https://ibm.ent.box.com/folder/124296984436?s=5d7h6abf3zpsbx1jb274lxz29edghnzl) maintained by Carbon for IBM.com team. 

DDS and Carbon team discussed adding the expressive type styles, possibly through copy/paste from the Carbon Expressive kits. 

Add all fluid expressive type styles to the Carbon design kits in `text-01` and `text-02` color tokens.
Expected hierarchy: expressive / breakpoint / type token / type token color

- [x] white
- [x] gray 10
- [x] gray 90
- [x] gray 100

## Additional information

<img width="1030" alt="Screen Shot 2021-05-24 at 4 30 18 PM" src="https://user-images.githubusercontent.com/45692622/119404124-5ff22180-bcad-11eb-9d91-6dc781ef3c8b.png">

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by mariuszmickiewicz** [comment]
@oliviaflory @laurenmrice 
In the Carbon Expressive Kits `text-02` uses #393939 (if I remember well, this was the previous value), instead of #525252 `Gray70`. I'm going to use the latter.

**Comment by mariuszmickiewicz** [comment]
1. I added the styles to Gray10 for now, will continue when we iron out the details below.
2. All styles have both `text-01` and `text-02` versions
3. Text colors are linked to IBM Design Language V2's color variables. Changes in color values in V2 will affect text styles in Carbon library.
4. `text-02` is `Gray70` (see the note in the thread above)
5. I noticed that SM breakpoint doesn't have `quotation-02` style, is that an error?

**Comment by oliviaflory** [comment]
thanks for the update @mariuszmickiewicz, everything sounds good.

>5. I noticed that SM breakpoint doesn't have quotation-02 style, is that an error?

Yes, this must be an error, there should be a quotation-02 for the small breakpoint 👍

**Comment by mariuszmickiewicz** [comment]
Thanks @oliviaflory 
I added `quotation-02` to SM breakpoint.
Another thing I noticed: `quotation-` styles from Carbon for IBM.com are using Plex Serif, while Carbon site is showing Plex Sans. Which one should it be?

I will update dark themes tomorrow and it will be live with next push to the cloud (@laurenmrice).

**Comment by oliviaflory** [comment]
I believe the quote is intended to be Plex Serif, and it might be an error that they're displaying as Plex Sans on the Carbon site. It's listed as Plex Serif. There's an [issue open](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1125) to fix it.

<img width="901" alt="Screen Shot 2021-05-26 at 10 03 50 AM" src="https://user-images.githubusercontent.com/45692622/119673956-cd1ac980-be09-11eb-8ec3-bc27e77e5ae1.png">

**Comment by laurenmrice** [comment]
Thanks so much for helping with this @mariuszmickiewicz 🚀 👏
