### ISSUE TITLE
v11: add tab enhancements

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-design-kit#438]
### Update tabs component for v11

**Update:**
Default to auto-width for line and contained

**Add:**
Icon-only md (line)
Icon-only lg (Line and contained)
Label + Icon (contained and line)
Label + icon + secondary label (contained only)

**Comment by kingtraceyj** [comment]
tab specs: https://ibm.box.com/s/sgb13zjehqbjat5d5b1b4090fs0o48qn

@laurenmrice if you want to do a working session together on this i can help out. i need to get going on doing kit work and i'm happy to help out. this might be a good place for me to start learning.

**Comment by laurenmrice** [comment]
**White theme** 
- [ ] Contained tabs
- [ ] Line tabs

**Gray 10 theme**
- [ ] Contained tabs
- [ ] Line tabs

**Gray 90 theme**
- [ ] Contained tabs
- [ ] Line tabs

**Gray 100 theme**
- [ ] Contained tabs
- [ ] Line tabs

**Comment by laurenmrice** [comment]
Added! Will be available with the v11 kit release 🎉
