### ISSUE TITLE
[button] carbon figma kit 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#441]
# Button
Carbon guidance: https://www.carbondesignsystem.com/components/button/usage/
Figma link:

## Requirements

**Themes**
- [x] White theme

**Types**
- [x] Primary
- [x] Secondary
- [x] Tertiary
- [x] Ghost
- [x] Danger
  - [x] Primary
  - [x] Tertiary
  - [x] Ghost

**Content types**
- [x] Text
- [x] Text and icon
- [x] Icon (*no danger variant)

**Sizes**
- [x] Large (48px height)
- [x] Medium (40px height)
- [x] Small (32px height)

**States**
- [x] Enabled
- [x] Hover
- [x] Focus
- [x] Active
- [x] Disabled
- [x] Skeleton

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: @JulesMurphy1 
- [x] Carbon compliance mm/dd/yyyy by: @laurenmrice

**Comment by JulesMurphy1** [comment]
Reviewed and looking good! Great job @juanencalada !!!
