### ISSUE TITLE
[accordion] carbon figma kit

### ISSUE THREAD

**Issue by JulesMurphy1** [carbon-design-system/carbon-design-kit#449]
# Accordion
Carbon guidance: https://www.carbondesignsystem.com/components/accordion/usage/

## Requirements

**Themes**
- [x] White theme

**Variants**
- [x] start (chevron to the left of text)
- [x] end (chevron on the right of box)

**Individual Pieces**
- [x] Header (where title, chevron/icon are)
- [x] Panel (where the body text is)

**Sizes**
- [x] Small (32px height)
- [x] Medium (40px height)
- [x] Large (48px height)

**States**
- [x] Enabled
- [x] Hover
- [x] Focus
- [x] Disabled
- [x] Expanded (open)
- [x] Collapsed (closed)

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: 
- [x] Carbon compliance mm/dd/yyyy by:

**Comment by msperli** [comment]
Interaction for my reference

https://user-images.githubusercontent.com/71150828/133483849-fb701d3f-e842-46e6-861a-e37bcbe37072.mov
