### ISSUE TITLE
[overflow menu] carbon figma kit

### ISSUE THREAD

**Issue by JulesMurphy1** [carbon-design-system/carbon-design-kit#451]
# Overflow menu
Carbon guidance: https://www.carbondesignsystem.com/components/overflow-menu/usage/

## Requirements

**Themes**
- [ ] White theme

**Variants**
- [ ] Open
- [ ] Closed

**# of Options**
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5

**Individual Pieces**
- [ ] Icon
- [ ] Option (default & divider)
- [ ] Drop shadow

**States**
- [ ] Enabled
- [ ] Hover
- [ ] Focus
- [ ] Active
- [ ] Disabled
- [ ] Danger hover (for options only)

**Figma features**
- [ ] Auto layout?
- [ ] Implement Variant panel

## Reviews
- [ ] Figma usability mm/dd/yyyy by: 
- [ ] Carbon compliance mm/dd/yyyy by:

**Comment by aagonzales** [comment]
![Overflow menu - White theme](https://user-images.githubusercontent.com/11670886/134700965-3b4fe9cf-ab89-4234-9e64-9bbd3fef1398.png)
