### ISSUE TITLE
[tile] carbon figma kit

### ISSUE THREAD

**Issue by JulesMurphy1** [carbon-design-system/carbon-design-kit#457]
# Tile
Carbon guidance: https://www.carbondesignsystem.com/components/tile/usage/

## Requirements

**Themes**
- [x] White theme

**Variants**
- [x] Base
- [x] Clickable
- [x] Selectable
  - [x] Single select
  - [x] Multiselect
- [x] Expandable

**States**
- [x] (base) Enabled, Hover, Focus, On-click
- [x] (clickable) Focus, Hover, On-click
- [x] (selectable: single select & multiselect) Enabled, hover, focus, selected
- [x] (expandable) Collapsed, hover, focus, expanded

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: 
- [x] Carbon compliance mm/dd/yyyy by:

**Comment by undair** [comment]
@laurenmrice Is 'white' variant necessary for this or are we removing it similar to code snippet?

**Comment by laurenmrice** [comment]
@undair You do not need the white variant for Tile as long as overrides are available so the designer can change the color tokens. 👍

**Comment by undair** [comment]
@laurenmrice I noticed there is guidance on the Carbon site for **.bx--tile__checkmark:hover** to be $icon-02 rather than its default $icon-01. Should I make a state where the card AND the check are being hovered over (so Tile would be $hover-ui and checkmark icon would be $icon-02)? Or would hovering over the checkmark "unhover" over the tile, keeping the Tile $ui-01? Thanks!

**Comment by undair** [comment]
As a note, the coded examples on the site maintain the $icon-01 color regardless of if you are hover on the checkmark or not.

**Comment by laurenmrice** [comment]
@undair 

For the Selectable tile (single select), there should be no icon on the hover state. Only the background color of the tile changes to `$hover-ui`.

When the Selectable tile (single select or multiselect) is selected and has the icon (checkmark or checkbox), the icon should always be `$icon-01`regardless if you are hovering on or off the tile or selecting a different tile.
