### ISSUE TITLE
[UI shell right panel] carbon figma kit

### ISSUE THREAD

**Issue by juanencalada** [carbon-design-system/carbon-design-kit#460]
# Right panel
Carbon guidance: https://www.carbondesignsystem.com/components/UI-shell-right-panel/usage/
Figma link:

## Requirements

**Themes**
- [x] White theme

**Variants**
- [x] Open
- [x] Closed

**List item types**
- [x] Text
- [x] Text and icon
- [x] Label and divider
- [ ] Divider only

**States**
- [x] Enabled
- [x] Hover
- [x] Focus
- [x] Active
- [x] Disabled
- [x] Skeleton

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: 
- [x] Carbon compliance mm/dd/yyyy by:

**Comment by clough12** [comment]
Link to component in figma:
https://www.figma.com/file/Vzz8k68Pqk5HfaTdQOQrGu/White-Theme-Carbon-Design-System?node-id=2258%3A15341

**Note:**
Right now this component does not incorporate the icon or label variants. The component is built to where we can easily incorporate these features, but I could not find them as a part of the core carbon system. I see them as part of the Gatsby theme and kit, but was not sure if we wanted to inherit them here into this component or not.

**Comment by JulesMurphy1** [comment]
Review happened yesterday and things look great!
