### ISSUE TITLE
[UI shell header] carbon figma kit

### ISSUE THREAD

**Issue by juanencalada** [carbon-design-system/carbon-design-kit#462]
# UI shell header
Carbon guidance: https://www.carbondesignsystem.com/components/UI-shell-header/usage/
Figma link:

## Requirements

**Themes**
- [x] White theme

**Variants**
- [x] Open
- [x] Closed
- [x] With nav
- [x] With switcher
- [x] With search

**Nav item types**
- [x] Header links
- [x] Header links expandable
- [x] Sub menus
- [x] Header utilities
- [x] Switcher

**States**
- [x] Enabled
- [x] Hover
- [x] Focus
- [x] Active
- [x] Disabled
- [x] Skeleton

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: 
- [x] Carbon compliance mm/dd/yyyy by:

**Comment by clough12** [comment]
Link to UI shell header component: 
https://www.figma.com/file/Vzz8k68Pqk5HfaTdQOQrGu/White-Theme-Carbon-Design-System?node-id=1880%3A7511

**Comment by JulesMurphy1** [comment]
Review happened yesterday and things look great!
