### ISSUE TITLE
[search] carbon figma kit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#471]
# Search
Carbon guidance: https://carbondesignsystem.com/components/search/usage/

## Requirements

**Themes**
- [x] White theme

**Variants**
- [x] [Default](https://react.carbondesignsystem.com/?path=/story/components-search--default)
- [x] [Expandable](https://react.carbondesignsystem.com/?path=/story/components-search--expandable)

**Sizes**
- [x] Small
- [x] Medium
- [x] Large

**States**
- [x] Enabled
- [x] Focus with placeholder text
- [x] Focus, begin typing
- [x] User input text, focused away
- [x] Disabled
- [x] Skeleton 

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: 
- [x] Carbon compliance mm/dd/yyyy by:

**Comment by J-Lynch** [comment]
Hi, let me know what you think. I only have expandable search as large. Let me know if we want medium and small as well. Thanks!

**Comment by J-Lynch** [comment]
Hi @laurenmrice @juanencalada I think I cover the revisions from last week. Let me know if it looks good to you!
