### ISSUE TITLE
[slider] carbon figma kit

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#473]
# Slider
Carbon guidance: https://carbondesignsystem.com/components/slider/usage/

## Requirements

**Themes**
- [x] White theme

**Individual Pieces**
- [x] Label
- [x] Slider bar (unfilled)
- [x] Slider bar and handle (filled)
- [x] Text input

**States**
- [x] Enabled
- [x] Hover
- [x] Focus
- [x] Selected
- [x] Disabled
- [x] Skeleton

**Figma features**
- [x] Auto layout?
- [x] Implement Variant panel

## Reviews
- [x] Figma usability mm/dd/yyyy by: 
- [x] Carbon compliance mm/dd/yyyy by:

**Comment by cynthia-yue-design** [comment]
The slider has been updated so that the track input is adjustable as discussed in our last review on 11/9.
