### ISSUE TITLE
[modal] Positioning of the close button differs between the code and Sketch kit

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#477]
Left - code
Close icon is within 48x48 square and the hover state looks good this way.

Right - Sketch kit
Close icon is 20x20 and positioned 16px away from top and right edge. 

Which one is the correct one? 

<img width="682" alt="image" src="https://user-images.githubusercontent.com/12408951/132496255-26c03952-78b9-40a9-af32-4040e555a3c2.png">

**Comment by laurenmrice** [comment]
We are no longer maintaining our Sketch libraries in favor of our [Figma libraries](https://carbondesignsystem.com/designing/kits/figma/), so we will be closing this issue.
