### ISSUE TITLE
[data table] 48 default Overrides panel out of order

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-design-kit#480]
## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

Gray 10

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Data table / column / 48 default

> What did you expect to happen? What happened instead? What would you like to see changed?

The Column header override is at the bottom of the Overrides panel. I expected it to be at the top of the overrides panel like the other data table / column symbols. Initially, I thought it was missing, but found it below the Row 10 override.

<img width="130" alt="Screen Shot 2021-09-30 at 2 01 13 PM" src="https://user-images.githubusercontent.com/45692622/135507676-d4d439d4-3a52-479d-b804-75940bcc9770.png">

<img width="142" alt="Screen Shot 2021-09-30 at 2 01 22 PM" src="https://user-images.githubusercontent.com/45692622/135507696-5d0d4d53-a255-4a64-a87f-46f4d87fbdf9.png">

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step tw

o
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by laurenmrice** [comment]
Fixed! Will be in the next kit update 🎉
