### ISSUE TITLE
v11 [toggle tip] add new toggle component

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-design-kit#482]
Toggle tip component additions

- Move over interactive tooltip to toggletip

**Comment by laurenmrice** [comment]
### Interactive toggletip
- [ ] Renamed "Interactive tooltip" group and item symbols to "Toggletip" and moved to the Toggletip component.

----

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

**Comment by laurenmrice** [comment]
Added! Will be available in the next Sketch kit update. 🎉
