### ISSUE TITLE
[button] carbon figma kit

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#485]
I see some differences between the Sketch/website specs and the Figma kit for _Large_ button (_Default_ in Sketch). Figma's version seems to be shorter (less space between the text and the icon).

<img width="328" alt="image" src="https://user-images.githubusercontent.com/12408951/149301343-6b09a7d9-25b4-4eab-b4f1-a44f4c9b8ed0.png">

<img width="179" alt="image" src="https://user-images.githubusercontent.com/12408951/149303242-3fb4acef-bdc2-425b-84b7-e72793a08b42.png">

@laurenmrice 
Btw. it seems that Sketch version (gray10) of ghost button has 8px spacing between the text and the icon and website shows 4px on the [example picture](https://carbondesignsystem.com/components/button/style#structure).

**Comment by laurenmrice** [comment]
Yes, the Large size for the primary style button for `Text + icon` has incorrect padding. It should be these specs below:
![Artboard](https://user-images.githubusercontent.com/43969356/149380839-af2baa21-f746-406b-b6d4-746172ecac55.png)

**Comment by laurenmrice** [comment]
@mariuszmickiewicz For the ghost button padding, there should be `8px padding` between the text and icon, not 4px padding. The website image needs to be updated and I made a note of that. 👍

**Comment by juanencalada** [comment]
Thanks @mariuszmickiewicz for bringing this to our attention! I went ahead and fixed in Figma and @laurenmrice will create a separate ticket for fixing the ghost button image example on the doc site.
