### ISSUE TITLE
[button] carbon figma kit

### ISSUE THREAD

**Issue by silvio-hajdin** [carbon-design-system/carbon-design-kit#488]
## Detailed description

Expressive button's hover+click states are partially cut off in the present/preview mode (while using the [NEW] Dec. 21/Jan. 22 White Theme - Carbon Design System). Button states are normal though, when cycled through in the design/work mode.  

## Steps to reproduce the issue

1. Create an expressive button
2. Launch preview
3. Hover/click

## Additional information

* Screen recording of the bug:

https://user-images.githubusercontent.com/98415805/151026965-83d4755b-5336-490d-b61a-04b81284a6b8.mov

**Comment by juanencalada** [comment]
@silvio-hajdin I believe I've resolved these interactions if you can confirm.

**Comment by silvio-hajdin** [comment]
thanks @juanencalada for the quick update - looks great, we can close the issue ***** :)

**Comment by juanencalada** [comment]
Thanks, Silvio! Closing! :)
