### ISSUE TITLE
[button] primary has wrong focus state color in dark themes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#491]
The primary buttons in the dark themes have the wrong focus color.
- [x] Ensure the focus border is using `$focus` color token
- [x] `$focus` token in the dark themes should have the value `#ffffff`

<img width="533" alt="Screen Shot 2022-02-18 at 8 38 40 AM" src="https://user-images.githubusercontent.com/43969356/154703623-86f64861-3b09-4d6c-b598-a7107878b6c1.png">

**Comment by undair** [comment]
@laurenmrice I just fixed this and published the updated Gray 90 and Gray 100 Themes :)
