### ISSUE TITLE
[Button, Figma kit, white theme]: Button expressive component not using 16px type

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#492]
Observed in Figma kit, white theme: 

The button type is labeled to be "Expressive", but expressive button should use 16px Plex regular. Currently this look more like a fluid button. 

https://user-images.githubusercontent.com/15144993/155741518-dcc59a82-f45c-47da-8dee-22ecf9d31419.mp4

----

- Change button text size to `body-compact-02`.
- Change button height to 48px (large).

- [x] White theme
- [x] Juan review
- [x] Add/remove correct variants for Expressive

**Comment by laurenmrice** [comment]
Fixed! Will be available in the next library update. 🎉
