### ISSUE TITLE
[Sketch] Fonts Missing

### ISSUE THREAD

**Issue by gregorw** [carbon-design-system/carbon-design-kit#495]
## Detailed description

Fonts are missing in Sketch.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/988276/159300153-afa6c776-0382-4f07-a7d3-9b9e49c8c153.png">

## Steps to reproduce the issue

1. Download IBMPlex from https://github.com/IBM/plex/releases/tag/v6.0.0
2. Install fonts in Mac OS X using Font Book
3. Download and install Carbon Design Kit from https://www.carbondesignsystem.com/designing/kits/sketch/#get-the-kit
4. Add symbol “ui shell / header / group / base + nav + actions”5. 

## Additional information

* Sketch Version 84 (140208)

**Comment by aagonzales** [comment]
Sketch is no longer a priority design tool for IBM and we are closing all feature updates as not planned.
