### ISSUE TITLE
Recommend Sketch viewer for Windows

### ISSUE THREAD

**Issue by hellobrian** [carbon-design-system/carbon-design-kit#5]
https://icons8.com/lunacy

Might be helpful for Windows users who need to view Sketch files.

You can zoom in using UI controls
![image](https://cloud.githubusercontent.com/assets/4185382/26757635/18b537be-4888-11e7-9353-d0773b313a66.png)

And view parts of the artboard off canvas by holding down mouse wheel and dragging.

**Comment by aagonzales** [comment]
> Regarding lunacy. I have it on my machine but it's not so usable as it only supports previewing and exporting as PNG. But it can be helpful in some situations.

From an IBMer I recommend using lunacy and this was their feedback. I exported the sketch file as a pdf and they said that worked better with Illustrator (its preserver vectors) than what Lunacy could provided.
