### ISSUE TITLE
[Adobe XD] Add progress bar component

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#504]
Add [progress bar](https://carbondesignsystem.com/components/progress-bar/usage/) component to all 4 XD theme files 
https://ibm.box.com/s/2wpgdc1opraul009xg8gc0d5n7r8z969
- [x] White
- [x] Gray 10
- [x] Gray 90
- [x] Gray 100

**Comment by thyhmdo** [comment]
@aagonzales  Close for now, let me know if there's any issue
