### ISSUE TITLE
[Figma] New: Progress Bar component

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#512]
Add [progress bar](https://carbondesignsystem.com/components/progress-bar/usage/) component to all 4 Figma theme files. **Use the "v11" branch in Figma.**
https://ibm.box.com/s/2wpgdc1opraul009xg8gc0d5n7r8z969

- [x] White
- [x]  Gray 10
- [x]  Gray 90
- [x]  Gray 100
- [x] Review by Juan 
- [x] Review by Anna or Lauren

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/512?planning-poker) with ZenHub @laurenmrice @thyhmdo

**Comment by thyhmdo** [comment]
Will have Juan review all themes when he's back from vacation

**Comment by thyhmdo** [comment]
@aagonzales @laurenmrice Already checked with Juan. It's ready for your review. I couldn't find a few tokens in Gray 90 but you'll see.
