### ISSUE TITLE
[Figma] v11: Tooltip component

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#516]
V11 updates to the [tooltip](https://www.carbondesignsystem.com/components/tooltip/style/) component
See Sketch kit for more details.
- [x] Rename the tooltip variants to be standard, icon button, and definition.
- [x] Add Standard variant.
- [x] Double check the spacing of the component variants to make sure they follow our specs.

-------

- [x] White
- [x] Review

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/516?planning-poker) with ZenHub @laurenmrice @thyhmdo

**Comment by laurenmrice** [comment]
Done! Will be available in the v11 libraries. 🎉
