### ISSUE TITLE
[Figma] New: Add icon to input fields

### ISSUE THREAD

**Issue by lizhatfi** [carbon-design-system/carbon-design-kit#523]
## Detailed description

New feature request

Would like to see the info icon added to the input fields, like this:
<img width="291" alt="Screen Shot 2022-04-28 at 9 16 58 AM" src="https://user-images.githubusercontent.com/16139300/165773174-31b6b43b-1fb6-44ab-bbf7-18fd0fc36222.png">

> What version of the Carbon Design System Kit are you using?

Light - CloudPAL

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

text field, area, drop down, radio, checkbox, etc.

## Add labels
kit:figma
type:enhancement

**Comment by aagonzales** [comment]
Hello, the tooltip icon is not a native feature in the coded component and therefor we will not be adding it to the figma version. Both tooltip and text input are available in the library and the user can add them both to create this effect. 

II also noticed you mentioned you use the CloudPAL kit, this repo is for the carbon core component.
