### ISSUE TITLE
[Docs]: Broken getting started link in README.md

### ISSUE THREAD

**Issue by nSedrickm** [carbon-design-system/carbon-design-kit#525]
## Detailed description

The getting started link in the README.md file leads to a [missing page](https://carbondesignsystem.com/get-started/develop/react/) on the website

> What did you expect to happen? What happened instead? What would you like to see changed?

The link should point to the [getting started](https://carbondesignsystem.com/developing/get-started/) page on the website

## Steps to reproduce the issue

1. In the README.md file, click on the getting started link under developers

**Comment by laurenmrice** [comment]
This seems to have been resolved. Going to close.
