### ISSUE TITLE
[Figma] v10: Multi-select changes its height when state is changed to Selected

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#527]
It seems that the height of the base of **Multi-select** component in _open_ state changes size when in _Selected_ state.
_Enabled_ state (the input part) is 40px high, while _Selected_ is 46px. I only checked _Gray10_ theme. 

This happens because Tag component is inserted (which is higher than line-height of default text) without adjusting padding.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/12408951/167216899-473dc7d0-c666-4d7b-8507-4f87d8e3a0cb.png">

--------
_Planning content from carbon team_

## Tasks

**V10** 
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 them

**v11** 
- [x] White theme

**Comment by laurenmrice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/527?planning-poker) with ZenHub @aagonzales @thyhmdo

**Comment by mariuszmickiewicz** [comment]
It looks good now, thanks!
