### ISSUE TITLE
[Figma] Migration announcement 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#530]
Create and distribute announcement for v10 - v11 Figma kit migration.
- Include key dates
- Precise directions on what users need to do

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/530?planning-poker) with ZenHub @laurenmrice @thyhmdo

**Comment by matheusagcosta** [comment]
hey @aagonzales , should I wait for v11 to start creating my tokens on Figma or that will be an easy thing to update?

**Comment by aagonzales** [comment]
Message has been sent on Slack. New expected release of late June. 

![Image](https://user-images.githubusercontent.com/11670886/171294772-92968437-d78c-437b-95fb-626288d862b8.png)
