### ISSUE TITLE
[Figma] v10: Notification - when close button removed layout issues are occuring

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#533]
No side margin for _Toast_
<img width="689" alt="image" src="https://user-images.githubusercontent.com/12408951/168687006-58caa65f-07dd-42d0-b087-2feac3c57d40.png">

_Inline short_
<img width="699" alt="image" src="https://user-images.githubusercontent.com/12408951/168687072-6acde79f-ca36-423e-890f-bbd1e952a85d.png">

_Inline long_
<img width="363" alt="image" src="https://user-images.githubusercontent.com/12408951/168687135-389ebf6a-e3d9-4a10-98a0-f52d7f7d7627.png">

**Comment by laurenmrice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/533?planning-poker) with ZenHub @aagonzales @thyhmdo
