### ISSUE TITLE
[Figma] Content switcher, Gray10 theme, small bug

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-design-kit#534]
## Small bug in Content switcher, Gray10 theme, Figma kit

`sm` and `md` size content switcher is taller than expected. `lg` seems okay.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/15144993/169088638-7727a5a0-4af6-45f1-bd5e-e7a7d0669c11.png">

**Comment by thyhmdo** [comment]
Related: https://github.com/carbon-design-system/carbon-design-kit/issues/520

White theme also had this problem. I fixed the components on both themes, both v10 and v11. I'm just not sure how updates will work.

**Comment by aagonzales** [comment]
Duplicate issue: https://github.com/carbon-design-system/carbon-design-kit/issues/520

**Comment by aagonzales** [comment]
@thyhmdo did you check gray 100 and gray 90 themes as well?

For the branches, I think if we fix it in the main branch we can then import it into any other branches like v11 (for now).

**Comment by thyhmdo** [comment]
@aagonzales just checked. They do have the same problem.

**Comment by laurenmrice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/534?planning-poker) with ZenHub @aagonzales @thyhmdo
