### ISSUE TITLE
[tag] add outline style - sketch

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#536]
Add Outline tag style for both sizes of the default and filterable tags.
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

----

## Default tag spec
![default](https://user-images.githubusercontent.com/43969356/162792702-ec067c38-f6c5-420a-a32e-0b63880f860c.png)

## Filterable tag spec
![filterable](https://user-images.githubusercontent.com/43969356/162792712-393681f0-fc6e-43e0-9c65-b54414df0c7a.png)

## Detailed description

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

> What did you expect to happen? What happened instead? What would you like to see changed?

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or Sketch file links
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized (i.e.use the `libraries` label for any issue relating to the Carbon Sketch Library). This will help us to better understand and address your issue.

**Comment by laurenmrice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/536?planning-poker) with ZenHub @aagonzales @thyhmdo

**Comment by laurenmrice** [comment]
Added. Will be available in the next kit update. 🎉
