### ISSUE TITLE
[Figma] v11: Structured list update 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#544]
**V11 updates to the [Structured list](https://carbondesignsystem.com/components/structured-list/style) component**
See Sketch kit for more details. 

**Problem:** There's only one spacing with the Header size of 42px and the Row size of 48px.

--------------

**Change:**
  - [x] Add a property for Spacing (maybe named "Spacing") `Default` and `Condensed`.
  - [x] Add a property for Alignment (maybe named "Alignment") `Hang` and `Flush`.
  - [x] Change the Row item to 60px (currently 48px)
  
--------------
**New theme strategy**
 - [x] Updates should be made only in the v11 white theme file
--------------
**Reviews**
- [x] Figma review
- [x] Carbon review

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/544?planning-poker) with ZenHub @laurenmrice @thyhmdo

**Comment by thyhmdo** [comment]
Being reviewed by Juan
