### ISSUE TITLE
[Figma]: update content for labels for the checkbox and radio button component

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#546]
- The content for the labels for these components should be updated to the following images below. We are trying to keep this labeling consistent throughout code, our website images, and our design tooling examples.

----

**Checkbox**
![checkbox](https://user-images.githubusercontent.com/43969356/178575336-1968ecda-6719-4129-95eb-01a839bb3be3.png)

**Radio button**
![radio button](https://user-images.githubusercontent.com/43969356/178575352-21d44d3a-f278-4ca1-a431-be203fa73dab.png)

**Comment by thyhmdo** [comment]
- [ ] V10
- [X] V11

**Comment by laurenmrice** [comment]
Added ✅
