### ISSUE TITLE
[Sketch] New: Tree view component

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#549]
Add to v11 library
Spec: https://ibm.box.com/s/r5wi7wkt4f50bo1kw6zamurl3kbbwst0

#### Variants:
- [x] Single select
- ~Multi-select~ _Has been deferred until development is done._

#### Sizes:
- [x] Small
- [x] Extra small

#### Modifiers:
- [x] With icon

#### Themes: 
- [x] White theme 
- [x] Gray 10 theme 
- [x] Gray 90 theme  
- [x] Gray 100 theme

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-design-kit/549?planning-poker) with ZenHub @laurenmrice @thyhmdo

**Comment by laurenmrice** [comment]
WIP White and Gray 10 theme symbols: https://ibm.ent.box.com/file/985024025883

**Comment by laurenmrice** [comment]
Added! Will be available in the next update 🎉
