### ISSUE TITLE
[Figma] add dropshadow to toast notification

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#556]
- The Toast notification should have a dropshadow in the themed Figma libraries.

----

![Artboard](https://user-images.githubusercontent.com/43969356/183919760-72dcc58e-fe97-4736-bc3d-945d3fe2d6f7.png)

**Comment by thyhmdo** [comment]
Updated and needs review 
- [x] V10
- [x] V11
