### ISSUE TITLE
[Figma] Add "Fluid inputs: TextInput" 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#557]
Fluid inputs: Provide design tooling updates for TextInput to `v11` Figma kit

- [x] Create a branch for all Fluid input work in each theme file (do not merge until all fluid inputs have been completed)
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec

[Figma file](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=0%3A1) | [Sketch file](https://ibm.box.com/s/4zcxjq750pbk0e0odl8vas0ff77fbko7)

![Text-input - White](https://user-images.githubusercontent.com/11670886/178830463-84cfe1bf-f777-4c2f-b30e-c8c9d03e6736.png)

**Comment by thyhmdo** [comment]
Except for skeleton state, this is ready for review
