### ISSUE TITLE
[Figma] Add new Pictograms to library

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#560]
- [ ] Add new Pictograms to Figma library (1-3?)

**Comment by laurenmrice** [comment]
- [ ] **PR 1**: https://github.com/carbon-design-system/carbon/pull/11959

- [ ] **PR 2**: https://github.com/carbon-design-system/carbon/pull/11959

- [ ] **PR 3**: https://github.com/carbon-design-system/carbon/pull/11976

- [ ] **PR 4**: https://github.com/carbon-design-system/carbon/pull/11942

- [ ] **PR 5**: https://github.com/carbon-design-system/carbon/pull/11973

**Comment by laurenmrice** [comment]
Published in Figma. Everyone has access to the newest update. 🎉
