### ISSUE TITLE
[Figma] Date picker: add helper text option

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#561]
Related issue: https://github.com/carbon-design-system/carbon-website/issues/3045

Date picker is missing the option to turn on helper text like in other inputs (ie text input). The helper text is required for date picker as it is one of two places the user can put the date format.

Helper text style:
Type token: $helper-text-01
Color token: $text-helper

<img width="794" alt="image" src="https://user-images.githubusercontent.com/11670886/185159760-b8d1dd2e-a1b1-4f29-ba3d-00e474d13c80.png">

**Comment by thyhmdo** [comment]
- [ ] All themes
   - [ ] White (in progress)
      - [x] Add helper text (month/date/year) to Simple date + Calendar picker
      - [ ] Add helper text to Date picker skeleton
      - [ ] Hide helper text when the calendar is opened
   - [ ] Gray 10
   - [ ] Gray 90
   - [ ] Gray 100

**Comment by thyhmdo** [comment]
Needs design review
