### ISSUE TITLE
[Figma] Add "Fluid-input: TextArea"

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#564]
Fluid inputs: Provide design tooling updates for TextInput to `v11` Figma kit

- [x] Add to branch for all Fluid input work in each theme file (do not merge until all fluid inputs have been completed)
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec

[Sketch file](https://ibm.box.com/s/xw86gmwu43rr5gjt7idlco8u2466lv9b) | [Figma file](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=119%3A3281)

![Text area - White](https://user-images.githubusercontent.com/11670886/187252880-9d04cc45-9ef2-4d94-a6bb-3fd0d0ae8c82.png)

**Comment by thyhmdo** [comment]
Ready for review
