### ISSUE TITLE
[Figma] New illustration covers 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#573]
Creating new illustration covers for Figma (published in September)
Related issue: https://github.com/carbon-design-system/carbon-design-kit/issues/566
Here is the **[Figma file ](https://www.figma.com/file/fhPCX97S2WhyRwUAmWN2ex/Cover-templates?node-id=315%3A384)**

![image](https://user-images.githubusercontent.com/77697351/190258185-8f0255b8-66be-423e-aa8a-2700f33b2e52.png)

**Comment by laurenmrice** [comment]
Done ✅
