### ISSUE TITLE
[Figma] Add "Fluid-input: Dropdown"

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#575]
Fluid inputs: Provide design tooling updates for TextInput to `v11` Figma kit

- [x] Add to branch for all Fluid input work in each theme file (do not merge until all fluid inputs have been completed)
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec

[Sketch file](https://ibm.box.com/s/bbv5gk3tipw741ktc0yrg1q2bxowtg3k) | [Figma file](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=232%3A865)

![Dropdown - White2x](https://user-images.githubusercontent.com/11670886/192299281-7df035b0-481b-4f80-9776-dc1dc81fa702.png)

**Comment by thyhmdo** [comment]
Branches:
- [White](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/mrhNyQPIfXbi6Ok4vBwC3L/(v11)-White-Theme---Carbon-Design-System?node-id=14032%3A290630) 
- [Gray 10](https://www.figma.com/file/0sd447WTcazDI6Dq9tjXOe/branch/CeWIj3XOpPTtfWSKPs7MhK/(v11)-Gray-10-Theme---Carbon-Design-System?node-id=60%3A0) 
- [Gray 90](https://www.figma.com/file/fH8rkv1VUTw5pvFDvO1kPO/branch/8OWGiWG365YDkU62tHRZBI/(v11)-Gray-90-Theme---Carbon-Design-System?node-id=182%3A0)
- [Gray 100 ](https://www.figma.com/file/XhRIHF6qGiJQaJ5eOSSBRm/branch/baZY6H2sLSrrv1mPMOoXoL/(v11)-Gray-100-Theme---Carbon-Design-System?node-id=60%3A0)
