### ISSUE TITLE
[Figma] Add "Fluid-input: ComboBox"

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#576]
Fluid inputs: Provide design tooling updates for TextInput to `v11` Figma kit

- [x] Add to branch for all Fluid input work in each theme file (do not merge until all fluid inputs have been completed)
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec

[Sketch file](https://ibm.box.com/s/x5dlvehz661vhqa75gwr6yqhfz0odoj5) | [Figma file](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=243%3A1914)

![ComboBox - White](https://user-images.githubusercontent.com/11670886/191582337-8424acbf-2833-4d16-a71f-7d916cbb911d.png)

**Comment by thyhmdo** [comment]
See branches here https://github.com/carbon-design-system/carbon-design-kit/issues/575
