### ISSUE TITLE
[Figma] Add "Fluid-input: MultiSelect"

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#577]
Fluid inputs: Provide design tooling updates for MultiSelect to `v11` Figma kit

- [x] Add to branch for all Fluid input work in each theme file (do not merge until all fluid inputs have been completed)
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec

[Sketch file](https://ibm.box.com/s/8719xg9er6irbwp2wds02xlde1ogw25p) | [Figma file](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=242%3A1052)

![MultiSelect - White](https://user-images.githubusercontent.com/11670886/191572599-ce728264-59ec-45c6-baa1-c2101b8d46ff.png)

**Comment by thyhmdo** [comment]
See branches here https://github.com/carbon-design-system/carbon-design-kit/issues/575
