### ISSUE TITLE
[Figma] Add "Fluid-input: DatePicker" 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#579]
Fluid inputs: Provide design tooling updates for DatePicker to `v11` Figma kit

- [x] Add to branch for all Fluid input work in each theme file (do not merge until all fluid inputs have been completed)
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec
![DatePicker - White](https://user-images.githubusercontent.com/11670886/194886354-56a0f704-d782-42d2-b6db-1f5a74323778.png)

**Comment by thyhmdo** [comment]
Branches: 
- [White theme ](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/doWK4ztmrQCLh63h1dXCo0/(v11)-White-Theme---Carbon-Design-System?node-id=60%3A0)
- [Gray 10](https://www.figma.com/file/0sd447WTcazDI6Dq9tjXOe/branch/CeWIj3XOpPTtfWSKPs7MhK/(v11)-Gray-10-Theme---Carbon-Design-System?node-id=60%3A0) 
- [Gray 90](https://www.figma.com/file/fH8rkv1VUTw5pvFDvO1kPO/branch/8OWGiWG365YDkU62tHRZBI/(v11)-Gray-90-Theme---Carbon-Design-System?node-id=182%3A0) 
- [Gray 100](https://www.figma.com/file/XhRIHF6qGiJQaJ5eOSSBRm/branch/baZY6H2sLSrrv1mPMOoXoL/(v11)-Gray-100-Theme---Carbon-Design-System?node-id=60%3A0)
