### ISSUE TITLE
Fluid inputs: provide Figma updates for FluidSelect

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#586]
Fluid inputs: Provide design tooling updates for Select to v11 Figma kit

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

## Spec

[Sketch file](https://ibm.box.com/s/q2jrlbduar30z70ix4dwgm7xld1a5mg9) | [Figma file](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=320%3A1673)

![Select - White](https://user-images.githubusercontent.com/11670886/198720449-ad55ae14-e267-4ae7-a80c-29a34df9db90.png)

**Comment by thyhmdo** [comment]
Reviewed with Anna and Juan
