### ISSUE TITLE
Fluid inputs: Provide Figma updates for FluidTimePicker

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-design-kit#588]
[Sketch](https://ibm.box.com/s/658frh5yaeyzh6ymrplqtbrllwp7vbdw) | [Figma](https://www.figma.com/file/9oQamCzUmVPw2jTiFkJ3Qw/Fluid-inputs_v11?node-id=329%3A1710)

![Time-picker - White](https://user-images.githubusercontent.com/11670886/200693481-f3248aa0-e5fb-4ce0-87bc-3a107da7f6c6.png)

**Comment by aagonzales** [comment]
@thyhmdo FYI we're only doing the group validation not the individual item validation atm. Reference [thread](https://github.com/carbon-design-system/carbon/pull/12603#issuecomment-1315869026).

<img width="992" alt="image" src="https://user-images.githubusercontent.com/11670886/202215749-07d35540-3cd3-4e61-afc9-b06d7cb876a9.png">
