### ISSUE TITLE
[Feature Request]: unavailable icons, Telegram and WhatsApp, programming languages, payment icons

### ISSUE THREAD

**Issue by a1y-ir** [carbon-design-system/carbon-design-kit#599]
## Detailed description

hi, in the website of [carbon-design-system/carbon-icons-svelte](https://github.com/carbon-design-system/carbon-icons-svelte) repository, which is [this](https://carbon-icons-svelte.onrender.com) I can't find Telegram and WhatsApp logo icons. is it something about svelte repository or its not included in carbon design system icons? also there is Python icon, but other programming languages icon are not available (go, C++, rust, php, Js, Ts, dart, etc...). payment icons (money, bill, wallet, gateway, bank, shop, etc...) are also unavailable.

> What did you expect to happen? What happened instead? What would you like to see changed?

it will be nice if we have these on next versions.

**Comment by laurenmrice** [comment]
Money, Wallet, and Gateway are icons we do currently have in the carbon-design-system icon package for React. I am unsure if these icons should be in Svelte but just have not been imported yet? Our team supports and maintains the React framework and we have contributors outside of our team that maintain the Svelte framework so it may not be 1:1 with what we have in React.

For the others icons you mentioned, we do not have actual icon assets that have been approved by our Brand team. If you would like to contribute these icons, you can follow our [Icon contribution guidelines](https://carbondesignsystem.com/guidelines/icons/contribute).

**Comment by metonym** [comment]
Commenting for future readers: Carbon Icons Svelte is directly built from the latest version of `@carbon/icons` (that is, the latest minor version that contains changes).
