### ISSUE TITLE
7.1.1 Release

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#6]
- [x] make sure new component states match with prod (lists, slider)
- [x] clean up symbols page with plug in - Symbol Organizer
- [x] small ghost btn on hover is wrong height

**Comment by tay-aitken** [comment]
- [ ] Date picker icons need to be updated
  - currently they look like this: 
<img width="517" alt="screen shot 2017-06-22 at 12 01 50 pm" src="https://user-images.githubusercontent.com/29312997/27443934-b08f469c-5742-11e7-88c3-16fe3766dcb3.png">

  - they should look like this:
<img width="283" alt="screen shot 2017-06-22 at 12 01 41 pm" src="https://user-images.githubusercontent.com/29312997/27443929-ada8bfb2-5742-11e7-8e84-fba8275faef7.png">

**Comment by aagonzales** [comment]
@tay-aitken I didn't realize the simple version was thing at first but I added them in the 7.1.1 Release I pushed on Tuesday. Is it still wrong in that version? 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11670886/27444481-1c88bc36-573c-11e7-8c00-d36c0aeeabe5.png">

**Comment by tay-aitken** [comment]
@aagonzales Sorry haven't had a chance to download the new one yet! The simple date pickers look good. It looks like the icons on the third column need to be updated. The rest look correct!
