### ISSUE TITLE
[Sketch]: Read-only inputs

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-design-kit#600]
Design file: https://ibm.box.com/s/1x7cd3p3pmx13wmcu46txgp3f83fxjot
Each of the following needs to be added to the `state` property across the four themes:

White theme
- [ ] Checkbox
- [ ] DatePicker
- [ ] TimePicker
- [ ] Dropdown
- [ ] Combo-Box
- [ ] Multi-select
- [ ] NumberInput
- [ ] RadioButton
- [ ] Slider
- [ ] TextInput
- [ ] TextArea
- [ ] Toggle 
- [ ] Select

Gray 10 theme
- [ ] Checkbox
- [ ] DatePicker
- [ ] TimePicker
- [ ] Dropdown
- [ ] Combo-Box
- [ ] Multi-select
- [ ] NumberInput
- [ ] RadioButton
- [ ] Slider
- [ ] TextInput
- [ ] TextArea
- [ ] Toggle 
- [ ] Select

Gray 90 theme
- [ ] Checkbox
- [ ] DatePicker
- [ ] TimePicker
- [ ] Dropdown
- [ ] Combo-Box
- [ ] Multi-select
- [ ] NumberInput
- [ ] RadioButton
- [ ] Slider
- [ ] TextInput
- [ ] TextArea
- [ ] Toggle 
- [ ] Select

Gray 100 theme
- [ ] Checkbox
- [ ] DatePicker
- [ ] TimePicker
- [ ] Dropdown
- [ ] Combo-Box
- [ ] Multi-select
- [ ] NumberInput
- [ ] RadioButton
- [ ] Slider
- [ ] TextInput
- [ ] TextArea
- [ ] Toggle 
- [ ] Select

**Comment by aagonzales** [comment]
Split up issue into separate theme issues - 20 points each

**Comment by sstrubberg** [comment]
Sketch support is now entering maintenance mode and will no longer have parity with Figma.

**Comment by laurenmrice** [comment]
We are no longer maintaining our Sketch libraries in favor of our [Figma libraries](https://carbondesignsystem.com/designing/kits/figma/), so we will be closing this issue.
