### ISSUE TITLE
[Read-only inputs]: update figma design kit

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-design-kit#601]
Design file: https://ibm.box.com/s/1x7cd3p3pmx13wmcu46txgp3f83fxjot
Each of the following needs to be added to the `state` property across the four themes:

- [x] Checkbox
- [x] DatePicker
- [x] TimePicker
- [x] Dropdown
- [x] Combo-Box
- [x] Multi-select
- [x] NumberInput
- [x] RadioButton
- [x] Slider
- [x] TextInput
- [x] TextArea
- [x] Toggle 
- [x] Select

https://github.com/carbon-design-system/carbon-design-kit/issues/601

**Comment by thyhmdo** [comment]
Ready for review @laurenmrice 

Checkbox, radio, toggle, slider 
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/447x5nfXpppwK4OdvW7ps3/(v11)-White-Theme---Carbon-Design-System?node-id=467%3A0&t=fo8EZgKU8JgToop7-1

Date picker
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/doWK4ztmrQCLh63h1dXCo0/(v11)-White-Theme---Carbon-Design-System?node-id=60%3A0&t=FGINf4R9LokMJOQf-1

Select
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/6wWyvaq3NhMQiELE83FWtG/(v11)-White-Theme---Carbon-Design-System?node-id=443%3A23&t=tgbDuDIfbOacKiWb-1


Number input
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/piR5FeQM2RmmwQnLfNw1Rb/(v11)-White-Theme---Carbon-Design-System?node-id=351%3A58&t=duW9lDX0sofDO1zZ-1


Dropdown (Combo-box, Multi-select)
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/mrhNyQPIfXbi6Ok4vBwC3L/(v11)-White-Theme---Carbon-Design-System?node-id=14032%3A290630&t=cXv7tutCbb7qsa6t-1


Text area
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/6U9evQKs2JvWGezBR5EZOg/(v11)-White-Theme---Carbon-Design-System?node-id=5564%3A279849&t=ZFK41fcozR69WqPy-1


Text input
https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-White-Theme---Carbon-Design-System?node-id=395%3A4&t=eGp2EUu61WCQHKPq-1

**Comment by thyhmdo** [comment]
**Updated in these files**
- [ ] Change `border-strong` to `border-subtle `
- [ ] Add the toggle of Date/text filled for both Enabled and Read-only 
- [ ] Add "No option selected" when Read-only state doesn't have either the text input or selected option
- [ ] Text alignment center for text field in slider text field 
- [ ] Make sure the background is `transparent` for read-only state

------
**Next steps** 
- [ ] Review by the Figma team (Juan, or Pat, or Eugene) 
- [ ] Publish

**Comment by silvio-hajdin** [comment]
Thanks all for addressing the read-only inputs in the design kit. We came across the related Figma component needs in 4Q2022 (relating to Cloud Satellite, SatConfig GitOps rollout), and wanted to check if an early/beta version of these read-only component options might already exist somewhere in the Figma format. If so, please let me know if I can potentially grab these now, in anticipation of the public release later this quarter - thanks!

**Comment by thyhmdo** [comment]
Hi @silvio-hajdin, we're in the process of reviewing these components at the moment. However, we're also working on updating the doc and adding this state to the code. Hopefully, we'll be able to wrap things up by the end of Q1 and we'll push the Figma version by then.

**Comment by aagonzales** [comment]
Closing this issue as complete! I created a separate issue to track the guild review effort. If the guild recommends major changes we can open a new issue to track that effort.
