### ISSUE TITLE
Fluid inputs: Provide Figma updates for FluidForm

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#603]
Create a fluid form component in Figma across themes in v11.

Form components
- [x] Header
- [x] Body 
- [x] Footer

Themes
- [x] White Theme
- [x] Gray 10 Theme
- [x] Gray 90 Theme
- [x] Gray 100 Theme

## FluidForm Spec

![Form - White](https://user-images.githubusercontent.com/11670886/202301744-3f3ec130-77f6-4ab7-96ad-68dcce088bf1.png)

**Comment by thyhmdo** [comment]
Will update Dropdown and Number input once we publish Fluid Input components in the Figma kit
