### ISSUE TITLE
FIGMA_View documentation button behavior 

### ISSUE THREAD

**Issue by lsi117** [carbon-design-system/carbon-design-kit#607]
[Figma]: The 'View Documentation' button needs to link to the actual component. Not just to the top of the component page.

## Detailed description

With a component selected, for example, a 'Text Area', the Inspection panel provides a button that links to the component's documentation within Carbon.

However, when that 'View Documentation' button is clicked and I am re-directed to the documentation within Carbon, it is not the specific component. 

I am using the 'Text Area' as an example because the view documentation button links me to the top of the page, 'Text Input', which can be confusing. 

Could it instead link to the actual section of the page that has details regarding the selected component? Like, linking to the 'Text Area' section of the documentation. This was the behavior I expected.

This occurs with other components too. (For example, button.)

![Screen Shot 2022-11-30 at 12 50 33 PM](https://user-images.githubusercontent.com/23106233/204871378-600c69be-57f5-4732-b555-3d53dd7efdfc.png)
'View Documentation' button; specific for 'Text Area' component.

![Screen Shot 2022-11-30 at 12 51 28 PM](https://user-images.githubusercontent.com/23106233/204871805-606e476e-9fe8-4d2f-8780-dfa994e0f906.png)
The button re-directs me to this Carbon documentation. You can see, it links me to the text input (top of page)....it should link me to the specific component, 'Text Area', underlined here (in red).

**Comment by laurenmrice** [comment]
This has been fixed and published in all v11 themes.

- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme
