### ISSUE TITLE
[Figma] v11: inline dropdown update

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#608]
In the v11 kits the inline has incorrect styling. It is correct in v10 so appears to have been updated incorrectly at some point. We will update this in the same brand as [fluid dropdown](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/mrhNyQPIfXbi6Ok4vBwC3L/(v11)-White-Theme---Carbon-Design-System?node-id=14032%3A290630&t=qoUZ8nuPfuPMZ3re-1) so as not to cause merge conflicts.

V11 

<img width="388" alt="image" src="https://user-images.githubusercontent.com/11670886/205680442-c2abfc61-96c1-4b7b-b6c8-3ca2685e62c7.png">

v10
<img width="412" alt="image" src="https://user-images.githubusercontent.com/11670886/205684355-7dd4d2e2-23eb-45a9-bbee-ed4d1e48cefe.png">

**Comment by thyhmdo** [comment]
Updated the inline dropdown's background for all themes. Check the Dropdown branches (Fluid)
