### ISSUE TITLE
Figma: Migrate the React developer tutorial Sketch tutorial file

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#610]
#### Acceptance criteria

- [x] Recreate the React Developer tutorial file in Figma. Ask @aagonzales for the original Sketch file.

**Comment by laurenmrice** [comment]
@aagonzales  has this been competed?

**Comment by aagonzales** [comment]
@laurenmrice I vaguely remember doing this but I don't see it anywhere on the site or in Figma so maybe it wasn't ever picked-up and I'm just remembering making this issue.

**Comment by laurenmrice** [comment]
Dev is currently working on the Next JS version of this tutorial and they need the figma file version of it to update the documentation so it is accurate.
