### ISSUE TITLE
TextArea warning state: create design spec, kit updates sketch and figma

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-design-kit#611]
- [ ] Need final spec for dev
- [ ] Confirm that the state is already in Figma (make sure its published)

**Comment by aagonzales** [comment]
## Final spec
[Figma file](https://www.figma.com/file/LJUJE0T30u5et33qnGLKI6/Fluid-input_Text-area_v11?node-id=0%3A1&t=CPEXE9gCtTW5OPbn-1)

<img width="697" alt="image" src="https://user-images.githubusercontent.com/11670886/221995525-031260b5-4fac-4187-a520-cea39dbe272a.png">
