### ISSUE TITLE
Figma: component inconsistencies in themes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#612]
A community member asked a question about the Text area and Contained list components in v11:

---

**Text area**
- [x] The White theme is missing the Text Area component. This needs to be resolved and added back to the library.

**Contained list**
- [x] This component in only showing up in the White theme and does not show up in the other themes. This needs to be published to the other themed libraries.

**Comment by aagonzales** [comment]
Double-check to see if these are still a bug.

**Comment by laurenmrice** [comment]
Fixed in all Carbon theme Figma libraries ✅
