### ISSUE TITLE
Figma: 2XL button size in the Button component missing

### ISSUE THREAD

**Issue by silvio-hajdin** [carbon-design-system/carbon-design-kit#616]
## Detailed description

2XL button size is not included in the button component. While this is a minor issue as 2XL size can easily be made in Figma from the existing productive versions (and seems to be the approach used in some of derivative Cloud PAL components + patterns), we're coming across it being reported as the initial version that was used to style it all the way to 2XL size/look  in the component properties (when viewed in the Inspect mode). 

Our developers see that initial size property (e.g. Extra large, Large, Medium, but never 2XL), which creates a bit of a confusion for them as to designer's intent (i.e. developer asks “is it supposed to be set at the default size of what the component property is calling it, or the actual size used in the layout”). To remove any ambiguity, it would be great if we could add a proper 2XL productive style/size to the button component.

> What version of the Carbon Design System Kit are you using? 

**v11**

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

**Button** component in all Carbon v11 core Figma libs

> What did you expect to happen? What happened instead? What would you like to see changed?

See the detailed description above.

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

**The Storybook repo** seems to be implementing this correctly, ie 2XL is a discrete button sizing option.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

**IBM Cloud Satellite** – not a burning need but would be good to address in the near future.

## Steps to reproduce the issue

1. Create a button instance. 
2. Open the component property 'Size'.
3. 2XL size isn't an option, and a 2XL button needs to be created manually from one of the smaller options available. The Inspect mode will only show the original size chosen before tweaks to the 2XL geometry though (which makes sense, but can be misleading to developers).

## Additional information

* Component properties in Figma reporting incorrect button size:

![image](https://user-images.githubusercontent.com/98415805/211603175-d2840b61-d62f-4de0-90bd-ed282ea5e98f.png)

 
* Storybook implements it correctly:

![image (1)](https://user-images.githubusercontent.com/98415805/211603359-a7293646-0fb0-4a2b-9bc7-8feccd019b5a.png)

**Comment by laurenmrice** [comment]
- [x] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

- [ ] Review

**Comment by laurenmrice** [comment]
Added to the Carbon-themed Figma libraries 🎉
