### ISSUE TITLE
Figma: Add "optional" guidance for placeholder and helper text

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#619]
Parent issue: https://github.com/carbon-design-system/carbon-website/issues/2928

- [x] Placeholder and helper text needs to be labeled as optional.
- [x] Hide placeholder text by default to match guidance/code.

Text should read as "Optional placeholder text" and "Optional helper text"
<img width="810" alt="image" src="https://user-images.githubusercontent.com/11670886/214922993-2ac603e1-be82-4a1c-8390-0096509ec1ca.png">

**Comment by thyhmdo** [comment]
Updated in 4 themes 
White theme example: https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/o39Kqwk9MziXxqC2OHiJM5/(v11)-White-Theme---Carbon-Design-System?node-id=15784%3A271028&t=9DLFRWgmL4Oo7F4P-1
