### ISSUE TITLE
[Sketch] Fluid inputs: Search

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#622]
Provide Skecth tooling updates for [Fluid Search](https://github.com/carbon-design-system/carbon/issues/12440) across all four themes in v11.

```[tasklist]
### Themes
- [x] White theme
- [x] Gray 10 theme 
- [x] Gray 90 theme
- [x] Gray 100 theme
```

**Comment by laurenmrice** [comment]
Added to all themes in Sketch 🎉
