### ISSUE TITLE
[Sketch] Fluid inputs: Combo box

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#626]
Provide Skecth tooling updates for [Fluid Combo box](https://github.com/carbon-design-system/carbon/issues/12120) across all four themes in v11.

```[tasklist]
### Themes
- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme
```

**Comment by laurenmrice** [comment]
Added to all themes in Sketch 🎉
