### ISSUE TITLE
[Read-only inputs]: review with figma guild and publish

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#632]
Review read-only implementation strategy and components with members of the Figma Guild for approval and apply any necessary changes. Once complete, inputs can be published. 

*Note: if no one is available to review, then this is NOT a blocker for the Carbon team to publish against the release timeline. If needed, we can make corrections later if recommendations eventually come from the guild.

**Comment by laurenmrice** [comment]
Finished and added to libraries. This will be published with the Fluid input push.
