### ISSUE TITLE
[Figma] Image guidelines: Write "About" page

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#633]
#### Acceptance criteria 
[Things that need to get done to make this a finished piece of work]

As a designer, I will be able to open this library and be able to read and understand the purpose of this library.
- [x] Create a cover image
- [x] Write "Mission" statement
- [x] Create "contact list"
- [x] Create "project directory"

**Comment by laurenmrice** [comment]
**"About" page Figma template**
https://www.figma.com/file/xNvfboozFkEVVU5J0pdwhQ/IBM-Project-Template?node-id=2511%3A2877&t=vcLMHo8a3krQfBUJ-0
