### ISSUE TITLE
[Figma] Image guidelines: Write "Read me" page

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#634]
#### Acceptance criteria 
[Things that need to get done to make this a finished piece of work]

As a designer, I will be able to open this library and be able to read and understand its structure and organization.

**Comment by laurenmrice** [comment]
**"Read me" guidance Figma template**
https://www.figma.com/file/4UYvy6eey28bD3IvtNF8xP/IBM-Documentation-Library?node-id=2%3A90&t=0F7WsYfz3KRJfhZL-0
