### ISSUE TITLE
Figma Carbon (v11) - Missing Contained List

### ISSUE THREAD

**Issue by ttt30ga** [carbon-design-system/carbon-design-kit#646]
## Relevant information

Contained List is missing in the Figma file.

**Comment by laurenmrice** [comment]
Hi @ttt30ga, Contained list has now been published in the White theme to match the other themes. 👍

**Comment by kissge** [comment]
@laurenmrice Has it landed to public Figma file (for non-IBMers)? I can't find it.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/4177010/236729898-4ed78140-0157-4ade-87d9-bb1b726227e5.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/4177010/236729956-ac4d7721-837b-4d7d-9c9a-49269f0565f6.png">

**Comment by laurenmrice** [comment]
@kissge It is possible that the public library has not published this update yet, and only the internal library has. We will make sure to resolve this issue.
