### ISSUE TITLE
[Figma] add read-only states for fluid style

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#657]
Add read-only states for fluid style form inputs.

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme
- [x] Review

---

Specs:
<img width="1056" alt="Read-only Fluid style spec" src="https://user-images.githubusercontent.com/43969356/220419235-e46a0610-31ee-4b62-948c-32ca8a4c8820.png">

**Comment by thyhmdo** [comment]
Ready for review from the main branches. These are already merged.
