### ISSUE TITLE
Duplicate entry layer/$layer-01 in Sketch library "Grey 100 theme"

### ISSUE THREAD

**Issue by Landschaft** [carbon-design-system/carbon-design-kit#662]
## Detailed description

There are two layer styles having the exact same name but different background color in the Grey/100 Sketch library issued on 2023/02/22: https://www.sketch.com/s/9d47a4fd-70dd-44ff-bc57-22c79da8e477/layer-styles?g=layer#Inspect

**Comment by laurenmrice** [comment]
Hi @Landschaft 👋, this has recently been fixed and published! Thanks for submitting the bug.
