### ISSUE TITLE
Menu: Figma Kit

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-design-kit#674]
## Acceptance criteria

- [x] Have a main page in the Figma library nav for `Menu`.
- [x] Build out the Menu primitive.

-----

- Build the following `option` properties.
  - [x] option
  - [x] option + icons
  - [x] option + carets
  - [x] option + shortcuts
  - [x] option + icon + caret
  - [x] option + icon + shortcut

- [x] Build a `menu` group with options in it.

----

### Style spec
![Context menu - 32px row and 16px padding](https://user-images.githubusercontent.com/43969356/97744611-ed75e600-1abd-11eb-84b7-1fd75f1f04e4.png)

### Structure spec

![Context menu - 32px row and 16px padding - spec](https://user-images.githubusercontent.com/43969356/97743530-3167eb80-1abc-11eb-9ed5-f093c141b90e.png)

**Comment by thyhmdo** [comment]
Reviewed with Juan and Lauren
