### ISSUE TITLE
[Figma] UI shell template

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#675]
Create a Figma [UI shell template library](https://www.sketch.com/s/6a8e1d7b-f00a-4d8d-9d83-79ecf4dc12a0) that we have in Sketch

---

**Template includes**
- UI Shell header: with/without right side panel
- UI Shell non-grid influencers: with/without left panel 
- UI Shell grid influencers: with compact side-rail and with transitional left-nav

* Note: we are not adding any right-side influencers panels to core kits right now because they belong to C4IP and Cloud PAL.

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/678
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/679
```

**Comment by aagonzales** [comment]
Looks like C4IP may have some of these templates already set up that we can pull in.
https://pages.github.ibm.com/cdai-design/pal/patterns/grid-influencers/usage/

<img width="723" alt="image" src="https://user-images.githubusercontent.com/11670886/232888796-8b00d481-cf3e-432b-8725-5f5af352a133.png">

**Comment by mjpaulus** [comment]
Hello, curious if figma related updates are being pushed to the Figma community file or is there another place to download Figma related updates. Thanks for this amazing system!

**Comment by laurenmrice** [comment]
@mjpaulus Figma related updates are being pushed to the Figma community files. We are going to have a cadence of updating our community files once a month.

**Comment by laurenmrice** [comment]
Talk with Juan and team first about how they are implementing their templates, before starting this umbrella of work.
