### ISSUE TITLE
Slider validation: Add to Figma kit

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-design-kit#676]
### Design spec

- Add the error and warning states to the Figma libraries.

----

#### Error
<img width="696" alt="image" src="https://user-images.githubusercontent.com/20582179/232139312-13725f99-7ddc-40bd-9683-28ab500b25a9.png">

#### Warning
<img width="558" alt="image" src="https://user-images.githubusercontent.com/20582179/232647789-42083ee1-cd42-43d2-b006-603f8124ccbc.png">

- [x] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme
- [x] Review

**Comment by laurenmrice** [comment]
- [ ] Fix issues from Figma review
- [ ] Publish
