### ISSUE TITLE
[UI Shell template] Make a separate UI Shell template file

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#678]
### Acceptance criteria

- [ ] Create a separate UI Shell template file that includes all of the UI Shell configuration screens, similar to the existing UI Shell Sketch template.
- [ ] Reference new Figma Guild guidance on creating templates.

**Comment by laurenmrice** [comment]
Talk with Juan and team first about how they are implementing their templates, before starting this umbrella of work.

**Comment by aagonzales** [comment]
This work is no longer be needed. Juan is creating a much broader [Carbon Layout library](https://www.figma.com/file/Wy6rYGbG8kB3Q7DYphn25y/(Alpha)-Carbon-Layout-Library?type=design&node-id=3811%3A36370&mode=design&t=EAZF5v6tN40NIxp8-1) that will include templates and screens for the UI Shell.
