### ISSUE TITLE
[Figma] Button: XL size padding bug

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#681]
The XL button should have 16px padding on the top not 15px. I noticed this in the white theme (have not checked the other themes)

Or at least the left and top padding should be the same if its adjusting for the border (all sides would be off by one?)

- [x] White theme
- [x] Gray 10 theme
- [x] Gray 90 theme
- [x] Gray 100 theme

<img width="357" alt="Screen Shot 2023-05-09 at 12 12 28 PM" src="https://github.com/carbon-design-system/carbon-design-kit/assets/11670886/735ce927-9175-4840-90b7-93f7cb675cab">

**Comment by thyhmdo** [comment]
Updated 16px padding top for both XL and 2XL buttons
