### ISSUE TITLE
Fluid component styles not found in Figma library

### ISSUE THREAD

**Issue by desktopranger** [carbon-design-system/carbon-design-kit#698]
-->

Describe in detail the issue you're having. Please include whether or not this is part of Sketch Libraries or the larger Sketch Kit file.

> What version of the Carbon Design System Kit are you using?

**v11 - Figma**

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

**Dropdown component** 

> What did you expect to happen? What happened instead? What would you like to see changed?

**Unable to find fluid style dropdowns (or any fluid components)**

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

**Yes; documentation provides ample details about Fluid style components (dropdowns) but I cannot find them on any design asset files.**

**Comment by laurenmrice** [comment]
@desktopranger Hey there, the figma theme files should be updated now with the fluid styles for form components. We pushed updates to the public files yesterday. 🎉
