### ISSUE TITLE
7.2.0 Release - Updates

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#7]
- [x] Remove corner radius on checkboxes
- [ ] remove softlayer logo from folder on repo
- [x] Include PDF version with release
- [x] Toggle with label
- [x] Add in new icons
- [x] **New components**
     * Data Tables
     * Tiles
     * Pagination
- [x] Add Data Vis page
    * Color palette
    * Example graphs

Moving items to V8:
- [ ] add in more grid examples?
- [ ] check nested symbols and styles - quicker editing ???
- [ ] [Dynamic icons ](https://uxdesign.cc/dynamic-icons-in-sketch-29463c946434)

**Comment by aagonzales** [comment]
- [ ] Date picker icons need to be updated
  - currently they look like this: 
<img width="517" alt="screen shot 2017-06-22 at 12 01 50 pm" src="https://user-images.githubusercontent.com/29312997/27443934-b08f469c-5742-11e7-88c3-16fe3766dcb3.png">

**Comment by bsonefeld** [comment]
## Current Checkbox style
![screen shot 2017-06-22 at 2 52 03 pm](https://user-images.githubusercontent.com/11233508/27452991-6466d420-575a-11e7-8d2c-0ea67b710119.png)

## Updated style
* No rounded corners

![screen shot 2017-06-22 at 2 52 07 pm](https://user-images.githubusercontent.com/11233508/27452993-653f5980-575a-11e7-988c-37481ef75de5.png)

**Comment by tay-aitken** [comment]
- [ ] **Structured List**
  - The first column header is not showing up, looks like the text box is too short
  - Several of the items in the first column are cut off, again I thin the text box is too short
![screen shot 2017-07-18 at 8 29 51 am](https://user-images.githubusercontent.com/29312997/28319491-aa2f47ce-6b93-11e7-8fb1-9ddfc8c38e4e.png)
