### ISSUE TITLE
V10 - Create sketch assets for other themes

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#70]
Only the "white" theme has been made in Sketch. Decide if we want separate files or all within one. We still need to deliver: 
- [x] Gray 10
- [x] Gray 90
- [x] Gray 100

**Comment by aagonzales** [comment]
This sprint:
- [ ] experiment with what is possible. Can they all go in one kit is there two or 4?

**Comment by laurenmrice** [comment]
White theme
https://sketch.cloud/s/JaVzz

Gray 10 theme
https://sketch.cloud/s/Onwv2

Gray 90 theme
https://sketch.cloud/s/eo37p

Gray 100 theme
https://sketch.cloud/s/d13Ll
