### ISSUE TITLE
[Question]: Suggested Component(s) for the Context menu (ie. right-click menu)

### ISSUE THREAD

**Issue by kunderwoodatadaptive** [carbon-design-system/carbon-design-kit#702]
### Question for Carbon

We need a customized context menu for various screens and user-roles for our product. I'd like to use a suggested component from Carbon, but in the meantime, I've used the v11 Figma files to create one of my own.

Here is what I created for a context menu:
1. I started with the component, "UI Shell - Left panel" and leveraged the child layers "UI shell - Left panel menu item"
2. I applied a "Shadows/Menu" effect to the entire frame, to add the necessary depth for recognizing a right-click menu as existing off the z-index.

<img width="636" alt="Screen Shot 2023-06-27 at 3 32 05 PM" src="https://github.com/carbon-design-system/carbon/assets/120414992/00a4cd31-aa8c-42f6-8074-491b4a300185">

Is this approach recommended, or is there a Carbon solution to building a context menu?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by laurenmrice** [comment]
Hi @kunderwoodatadaptive 👋

We recently have published the [Menu component](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=31107%3A3280&mode=design&t=7zCbKZAsb1hIhAtl-1) in our Carbon Figma All themes library. I would suggest using this component to build out your right click menu example above.

Our Menu component does have the option to have flyout menus and section dividers like you have above, but you will need to make your own customizations to the visuals if you prefer to have chevron icons versus caret icons, and indented divider lines versus flush divider lines, etc. 

This is what your example would look like using the Carbon menu component in Figma:


![Image](https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/cd57f2ab-c103-4697-a973-1f06fb253d50)
