### ISSUE TITLE
Figma themes deprecation: Update Figma v11 libraries

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#704]
### Add theme variables
- [x] All themes file: Include theme variables to cover all four theme values for color tokens. (White, Gray 10, Gray 90, and Gray 100)

### Renaming libraries
- [x] All themes file: Rename to `(v11) All themes - Carbon Design System`.
- [x] Other theme files:
  - [x] Rename to `🚫(v11) Theme - Carbon Design System [Deprecated]`.
  - [x] Still keep files in the same folder till further notice.
  - [x] Cross link the White theme file url with a disclaimer in the "Description" of the deprecated theme files.

### Read me and About pages
- [x] All themes file: [Follow Thys template](https://www.figma.com/file/XBWlLpk5CiTo9MuEIipGLr/Figma-Deprecation?type=design&node-id=23%3A8913&mode=design&t=fw4GU9CYBsVEae1q-1)
- [x] Other theme files: [Follow Thys template](https://www.figma.com/file/XBWlLpk5CiTo9MuEIipGLr/Figma-Deprecation?type=design&node-id=23%3A8913&mode=design&t=fw4GU9CYBsVEae1q-1)

### Color page
- [x] All themes file: Put notification/disclaimer at top of page that we will eventually be updating it with other theme info.

### Effects page
- [x] All themes file: Put notification/disclaimer at top of page that we we cant use modes/variables for effects yet, but Figma will be implementing this feature in the future.

### Migration artboard
- [x] Add a Migration artboard to the About page.

------

### Publishing

**Update file on Friday, Aug 4**
- [x] **Publish internally:** Add description of the changes/benefits in the release notes.
- [x] **Publish publicly:** Add description and meaningful tags. (Ref [Platform work](https://next.carbondesignsystem.com/design-kits) for library descriptions)

**Comment by thyhmdo** [comment]
Deprecation working file: https://www.figma.com/file/XBWlLpk5CiTo9MuEIipGLr/Figma-Deprecation?type=design&node-id=0%3A1&mode=design&t=w5Xxg47OssX54MFP-1

1. See new updates on the "Decided" column
2. Not sure how it works if other teams have other theme files connected to their kits. (See that sentence in red) ![image](https://github.com/carbon-design-system/carbon-design-kit/assets/77697351/57541ceb-e279-459d-b153-4c2075cbd621)
3. Cross linked everything to the "Deprecation of theme files" and need to add the links once it's created in the files. (x3 for deprecated themes)
4. Lauren will follow up with Juan about two specific questions on the Color page and Utility page
5. What's New and Roadmap: Not prioritized to update now but we should rethink about this content in the future for effective manual update
