### ISSUE TITLE
Figma themes deprecation: Update Figma v10 libraries

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#710]
### Add theme variables
- [x] White theme: Include theme variables to cover all four theme values for color tokens. (White, Gray 10, Gray 90, and Gray 100)
- [x] White theme: Update all components in the white theme to use variables instead of styles

### Renaming libraries
- [x] White theme: Rename to `(v10) Carbon Design System all themes`.
- [x] Rename other theme libraries and mark as [Deprecated] at the end of the name
- [ ] Still keep files in the same folder till further notice.
  - [ ] Also do this for public community files.
  - [ ] Cross link the White theme file url with a disclaimer in the "Description" of the deprecated theme files.

### Read me 
- [x] **Mission artboard:** Remove any information about our four theme files.

### Color page
- [x] Put notification/disclaimer at top of page that we will eventually be updating it with other theme info.
- [x] Juan comments about discrepancies with colors.?? (follow up)

### Utility page
- [x] Setup utility theme variables.

------

### Publishing
- [x] **Publish internally:** Add description of the changes/benefits in the release notes.
- [ ] **Publish publicly:** Add description and meaningful tags. (Ref [Platform work](https://next.carbondesignsystem.com/design-kits) for library descriptions)

**Comment by aagonzales** [comment]
These updates are all complete, we just need to push the updated to the public Figma files.
