### ISSUE TITLE
Inline dropdown: bottom border

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-design-kit#718]
## Detailed description

The inline dropdown has a bottom border in the Figma Kit, whereas neither the coded implementation nor the design guidance show it.

> What version of the Carbon Design System Kit are you using?

(v11) All Themes Figma Kit

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Deopdown > Style: Inline

> What did you expect to happen? What happened instead? What would you like to see changed?

Expected: No bottom border under the value

> Is this issue being filed based on a discrepancy between the website/code and the kit? If so what is the inconsistency?

see above

## Steps to reproduce the issue

1. Insert Dropdown component
2. Change "Style" to "Inline"

## Additional information
Figma Kit:

<img width="763" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/28265588/e13f7a54-cf8d-4368-a61d-5e49da4412a8">

carbondesignsystem.com:
![image](https://carbondesignsystem.com/static/b255c47e425c072c051d289df10c775c/4ea69/dropdown-style-4.png)

**Comment by laurenmrice** [comment]
Done and published in the library
