### ISSUE TITLE
Figma: Replace color styles with color variables

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#723]
Eventually, we need to go through the components and replace all instances of color styles with color variables. Right now we have variables daisy-chained to variables, so not is broken or not working but it will be a better process/file to have the variables linked directly in the components.

I actually already did this in v10 when I did those update so we just ned to do it in v11.

<img width="1792" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/11670886/156a8ce3-7a56-4665-a6df-e87449fe97fd">

**Comment by laurenmrice** [comment]
- [x] All themes
- [ ] Review
