### ISSUE TITLE
Figma: Update color token page with all theme values

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#724]
The color page only show the values for the white theme. We need to update this page to reflect all themes value or redesign how this page works.

<img width="1792" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/11670886/42a785f1-dab0-4371-836c-abfe031384a2">

**Comment by thyhmdo** [comment]
I've tested out a few things. Here is the [Figma branch](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/d3wKdTcOHyXletj7RE0Fdq/(v11)-All-themes---Carbon-Design-System?type=design&node-id=169%3A0&mode=design&t=LHkZ88kBLRRJxV0K-1) for this issue. There are 3 possible solutions: 
- Add a column in the data table to define a theme. Effort: High
- Copy and paste color token data table from other themes for each group. Effort: Medium 
- Copy and paste all the art boards from other themes here. Effort: Low
