### ISSUE TITLE
[Slider] Two Handles Defining the Range: Figma kit

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-design-kit#725]
@KevinCamelo

## Acceptance criteria

Create the range two handle slider in a Figma branch
- [x] All themes file

Get a review from a Figma and Carbon perspective
- [x] Review from Carbon
- [x] Review from Figma expert

Merge the branch into the All theme file
- [x] Merged branch

**Comment by KevinCamelo** [comment]
Hello @sstrubberg @laurenmrice. I've done a pass at creating the Figma component using the updated component spec. I tried mirroring the Carbon component format and naming scheme as best as I could. Please let me know if any additional work is needed. 

https://www.figma.com/file/Jk3pWNBG6ZWIRoldq2tM1x/Range---Slider-Enhancement?type=design&node-id=824%3A5164&mode=design&t=7NHqXCrz8XhGbmdi-1
