### ISSUE TITLE
Selectable components: Tile single select

### ISSUE THREAD

**Issue by Niels200** [carbon-design-system/carbon-design-kit#729]
Figma Gray 10 community library
(https://carbondesignsystem.com/components/tile/usage/)

The single select tile doesn't show an unselected state. I do see an aesthetic-minimalistic benefit in leaving out the radiobutton unchecked icon for the unselected single select tiles. However it misses out on an important use que to provide extra uniform connectedness between the selected and unselected single select tiles. 

The multi select does show the unselected state and in a group of tiles it gives a clear cue what to expect from each tile before interaction. 

1. Why is the the unselected state icon not shown for the single select tile? 
2. These type of design decisions, are these documented somewhere publicly for the community?

![image](https://github.com/carbon-design-system/carbon-design-kit/assets/108858793/e42830db-31cf-46d8-aea8-665b3952c0d8)

**Comment by laurenmrice** [comment]
Hello @Niels200 👋

Thanks for bringing this up. This is something we are currently exploring new design solutions for in issue [#14722](https://github.com/carbon-design-system/carbon/issues/14722), to make our selectable components more visually consistent across the system. If we end up making any visual changes to single-select tile, we will use this issue to tackle it. 

To answer your questions:
1. Your design solution above for single-select tile is currently being considered.
2. We will post a final design spec in an issue in GitHub and then document it on the [Style tab](https://carbondesignsystem.com/components/tile/style) for that component on our website with its specs.

**Comment by laurenmrice** [comment]
Related [#14722](https://github.com/carbon-design-system/carbon/issues/14722)

**Comment by Kritvi-bhatia** [comment]
Hello @Niels200 👋

## Final Design Solution

### **Tiles**
> [Figma file link](https://www.figma.com/file/w4QA4bnNZAiySPskA5qZMW/Selectable-Components?type=design&node-id=389-955&mode=design&t=zS0hyNhwq4lAOXTs-4)
> ![image](https://github.com/carbon-design-system/carbon/assets/148799271/195d6775-d40c-42f4-8295-f481cf3382b0)

-----

_If you want to check for further selectable components - [link](https://github.com/carbon-design-system/carbon/issues/14766#issuecomment-1874852921)_

**Comment by Niels200** [comment]
Thanks for the update
