### ISSUE TITLE
Figma - Issue with Tab Component

### ISSUE THREAD

**Issue by simongranthamibm** [carbon-design-system/carbon-design-kit#730]
When using the tab component and changing a tab to be icon only the tab jumps out of alignment - see attached. 

<img width="971" alt="Screenshot 2023-10-19 at 10 54 42" src="https://github.com/carbon-design-system/carbon-design-kit/assets/142350961/de8f34b9-2393-43ad-b770-cef4f2c45eff">

**Comment by thyhmdo** [comment]
Please refer to this related issue: https://github.com/carbon-design-system/carbon-design-kit/issues/663

It was resolved so feel free to open it again if the issue is still there. Thank you
