### ISSUE TITLE
Can a Dropdown menu really open upwards if at the bottom of a page?

### ISSUE THREAD

**Issue by kunderwoodatadaptive** [carbon-design-system/carbon-design-kit#740]
Hello,

On your website, I read [this section](https://carbondesignsystem.com/components/dropdown/usage/#direction), describing that "A dropdown can open up or down depending on its position on the screen".

**I would like to see an example of this behavior somewhere**, if you can provide a link. I'd like to know, specifically, if the **chevron switches directions in enabled v.s. active states**.

On the UI builder app, I noticed this behavior wasn't applied. See a screenshot of my Fragment, which I used to test this component behavior out. In this example, the comb box at the bottom of the page still opens downward, its menu getting cropped.

<img width="807" alt="Screen Shot 2023-11-22 at 10 18 35 AM" src="https://github.com/carbon-design-system/carbon-design-kit/assets/120414992/9a2e0634-76da-4350-a379-8f5cf7689af2">

**Comment by laurenmrice** [comment]
Hi @kunderwoodatadaptive, Yes, the dropdown can open from the top direction depending on what is better for your usecase. Here is an example in our [React Storybook](https://react.carbondesignsystem.com/?path=/story/components-dropdown--playground&args=direction:top). We use the prop `direction` to set if the dropdown opens from the top or bottom.

**Comment by kunderwoodatadaptive** [comment]
Thank you, @laurenmrice !
