### ISSUE TITLE
[Figma] discrepancy with UI shell header and right panel color tokens

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#742]
## Acceptance criteria

- There seems to be some discrepancies across the code, design kit, and website docs for the color tokens used in the UI Shell Header and the Right panel. 
- Double check to see what the correct color tokens to be and if they are being applied correctly across these three different areas.

**Comment by alina-jacob** [comment]
**Inference**

[Figma reference file](https://www.figma.com/design/BkjBOeF9CtYLiPkjdrebjg/Common-doc---Alina's-Workspace?node-id=370-31037)

---

## UI shell header
- **Style tab**
- [ ] [Color](https://carbondesignsystem.com/components/UI-shell-header/style#color): Add spec for divider - `Divider | border | $border-subtle`
- [ ] [Sub-menu](https://carbondesignsystem.com/components/UI-shell-header/style#sub-menu): Update sub-menu's `Selected` state to `Open / Expanded`. 
- [ ] [Sub-menu](https://carbondesignsystem.com/components/UI-shell-header/style#sub-menu): Update sub-menu item's image to include item's `Selected` state as well. 
- [ ] [Typography](https://carbondesignsystem.com/components/UI-shell-header/style#typography): Add typography spec for sub-menu item - `Sub-menu item | 14 / 0.875 | Regular / 400 | $body-compact-01`

--

- **Figma**
- [ ] [Sub-menu](https://carbondesignsystem.com/components/UI-shell-header/style#sub-menu): Sub-menu item's `Selected` state is missing in Figma.
- [ ] [Header actions](https://carbondesignsystem.com/components/UI-shell-header/style#header-actions): [Enhancement] - The header action buttons can have an open state which opens up a side nav / panel / popover. 

## UI shell right panel
- **Style tab**
- [ ] [Color](https://carbondesignsystem.com/components/UI-shell-right-panel/style/#color): Update Panel's border spec as - `border-left, border-right, border-bottom`
- [ ] [Color](https://carbondesignsystem.com/components/UI-shell-right-panel/style/#color): Should we be adding shadow, overlay specs in our docs? **(Yes, audit for other components as well)**
- [ ] [Item](https://carbondesignsystem.com/components/UI-shell-right-panel/style/#item): Add border spec for Selected state - `border-left | $focus-interactive`

## UI shell left panel
- **Style tab**
- [ ] [Color](https://carbondesignsystem.com/components/UI-shell-left-panel/style#color): [Enhancement] Potential to add border-right and border-left to the UI shell left panel. **(Yes, can be included as a prop)**
_[These](https://github.com/carbon-design-system/carbon/issues/4839#issuecomment-604043001) are the UI shell theme options explored by Anna._ 
- [ ] [Color](https://carbondesignsystem.com/components/UI-shell-left-panel/style#color): Add specs for Overlay - `Overlay | background-color | $overlay`
- [ ] [Icon](https://carbondesignsystem.com/components/UI-shell-left-panel/style#icon): Delete this section as this is repeat information.

**Comment by alina-jacob** [comment]
Updated the story points from 3 to 5 for this issue.
