### ISSUE TITLE
[Selectable Components: Tile & Structured List] Figma Kit 

### ISSUE THREAD

**Issue by Kritvi-bhatia** [carbon-design-system/carbon-design-kit#744]
### Update the All themes Figma kit with any changes that came out of the [final design specs](https://github.com/carbon-design-system/carbon/issues/14766) for selectable components.
- [x] Consult @juanencalada about the build of current Figma components and with any outstanding questions.

---

### **Tiles**
> - [x] Update the radio button icon in **tiles**
> - [x] Update the inconsistencies, bugs, miss
>   - [x] Add the disabled state for enabled state in both single & multi-select
>   - [x] Update all the Titles' and Descriptions' fonts as "body-compact-1"
>   - [x] Link all the text styles
>   - [x] For the disabled states, fix the border color as $border-disabled

---

### **Structured list**
> - [x] Update the icon in the **structured list** (from checkmark to radio button)
> - [x] Add the state where the icon will be on the left
> - [x] Along with the transparent structured list, add the whole set of structured list with background too
> - [x] Remove the flush state from the non-selectable structured list
> - [x] Update all the inconsistencies, bugs, miss
>   - [x] Headers' height inconsistencies
>   - [x] Add all the different states (selected, enabled, hover, focus, disabled)
>   - [x] Link all the text styles

---

### Review
> - [x] Review (carbon designer)
> - [x] Review (figma expert/Juan)

**Comment by juanencalada** [comment]
Hey @Kritvi-bhatia,

1. I updated the order and placement of some of the accessible borders
2. I would reset defaults on the icons so that the vector layer remains locked as is intended from the icon library:
![image](https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/ab81aefc-588a-4669-8385-d21c93e046fc)
3. I would lock this frame and also consider setting up icon swap properties for them and include preferred values based on what IBM Dotcom is doing. I would ask @laurenmrice for her thoughts on this to see if she also feels this is something we'd like to offer to users as a nice to have. At the very least I'd lock the layers to reduce selectability distraction
<img width="965" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/8c01bc95-e90f-4aa4-910d-0feb9d1e9c2e">
<img width="883" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/12b14ab6-8b8c-4e44-93e2-6b44337ad51e">
<img width="712" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/2b262bd6-acc2-446e-83fb-49e81189cbac">

4. There are conflicting variants from having the same properties. I would consider removing the bottom half: 
![image](https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/d502dd3d-9462-4bde-942f-e9f337fb15bc)

**Comment by juanencalada** [comment]
For Structured list:
1. I renamed the second one to Structured list - Selectable
<img width="587" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/3e409424-dbe4-4cce-824a-83f73b0aabaf">

**Comment by juanencalada** [comment]
Depending on why we need the background, we might be able to move the background layer out of the rows, and directly into the whole table as a boolean property that's available only for the hang variants
<img width="147" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/493c487e-b6a8-4f53-8e7b-4fbd67087b62">

**Comment by Kritvi-bhatia** [comment]
> Hey @Kritvi-bhatia,
> 
> 1. I updated the order and placement of some of the accessible borders
> 2. I would reset defaults on the icons so that the vector layer remains locked as is intended from the icon library:
>    ![image](https://private-user-images.githubusercontent.com/24463121/301027265-ab81aefc-588a-4669-8385-d21c93e046fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODgxMDYsIm5iZiI6MTcwNjY4NzgwNiwicGF0aCI6Ii8yNDQ2MzEyMS8zMDEwMjcyNjUtYWI4MWFlZmMtNTg4YS00NjY5LTgzODUtZDIxYzkzZTA0NmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA3NTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MzkwMjc3MmZmNzczMmQ3YWYyZDE0YjczY2FjMzBlYTI5ZTkzNWUyMDM0MzQ5ZGExODg0NjU4ZTUyZmFmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DEKV8qwc3UevDjJdsoK0YPdiKIGqQPJUUI6IUr65k6M)
> 3. I would lock this frame and also consider setting up icon swap properties for them and include preferred values based on what IBM Dotcom is doing. I would ask @laurenmrice for her thoughts on this to see if she also feels this is something we'd like to offer to users as a nice to have. At the very least I'd lock the layers to reduce selectability distraction
> 
> <img alt="image" width="965" src="https://private-user-images.githubusercontent.com/24463121/301027444-8c01bc95-e90f-4aa4-910d-0feb9d1e9c2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODgxMDYsIm5iZiI6MTcwNjY4NzgwNiwicGF0aCI6Ii8yNDQ2MzEyMS8zMDEwMjc0NDQtOGMwMWJjOTUtZTkwZi00YWE0LTkxMGQtMGZlYjlkMWU5YzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA3NTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3Yjc1ZjA2YjQxYzliZmU3MDk0ZjY3NDI4NzNhYmU2NDcwMWFmNzkxZDI3NmE4M2YyNjg0YWViYjkxMTk0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8pXgqbhNUTcHJTPStADXod-m_sTDmjpKfqtFQd-7ue8"> <img alt="image" width="883" src="https://private-user-images.githubusercontent.com/24463121/301027695-12b14ab6-8b8c-4e44-93e2-6b44337ad51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODgxMDYsIm5iZiI6MTcwNjY4NzgwNiwicGF0aCI6Ii8yNDQ2MzEyMS8zMDEwMjc2OTUtMTJiMTRhYjYtOGI4Yy00ZTQ0LTkzZTItNmI0NDMzN2FkNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA3NTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYmFkZjNhNTdmYTJlYzI1ZjdhNzY0ZjFlN2ZmYTY4NDQ4MmVmNzQ1YWU0M2NhZDQ2MDY0ZTU2ODZlOTM2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._c8GMGJK7036uj4H5IPWaRhuKSacqXRBknMWCP-tdJo"> <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/24463121/301027899-2b262bd6-acc2-446e-83fb-49e81189cbac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODgxMDYsIm5iZiI6MTcwNjY4NzgwNiwicGF0aCI6Ii8yNDQ2MzEyMS8zMDEwMjc4OTktMmIyNjJiZDYtYWNjMi00NDZlLTgzZmItNDllODExODljYmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA3NTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTMyNDMyODIzZmZkOWE5Mjk2OGMxNDU2Yzg1YmJhNmU4OWFlOTljOTViMWVmODNkMjFlZDYzZDUwN2JmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M10EBm5stVzgYNux00og9rMZ4tXCoW4kK3Nud1-XtOc">
> 4. There are conflicting variants from having the same properties. I would consider removing the bottom half:
>    ![image](https://private-user-images.githubusercontent.com/24463121/301028011-d502dd3d-9462-4bde-942f-e9f337fb15bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2ODgxMDYsIm5iZiI6MTcwNjY4NzgwNiwicGF0aCI6Ii8yNDQ2MzEyMS8zMDEwMjgwMTEtZDUwMmRkM2QtOTQ2Mi00YmRlLTk0MmYtZTlmMzM3ZmIxNWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA3NTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNWQ2ZGEyMTQ5MDlkYTQwMGM1OWIxZThhZjVjY2I4MjU1ZjA4Y2M4OWRlN2Y4NGNlNjJlNDViMWIzYTE5OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uM_y0SzVVkZ8SY7dJ3aK17f47NGokIaLdssLONINEBw)

Hi @juanencalada!!
1. Thanks for doing that
2. I've done that, thanks for pointing out
3. So I've locked the icon layer but regarding adding the icon swap and all will consider in the next update / issue as currently I'm just focusing only on the selectable components
4. Not sure, nothing is conflicting for me though 🤔
<img width="965" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/148799271/a35109e1-b779-41bd-a876-f68c6e4d2448">

**Comment by Kritvi-bhatia** [comment]
(In reply to [your third comment](https://github.com/carbon-design-system/carbon-design-kit/issues/744#issuecomment-1918310363))
I've [updated it](https://www.figma.com/file/eEftar142RW69BRQO9g5wM/Structured-List-(Selectable-Components)?type=design&node-id=1880-6567&mode=design&t=3Q3bWqeBGbqmvHwB-4) now as you recommended, can you please check now!?

**Comment by juanencalada** [comment]
Hey @Kritvi-bhatia 
What is the background layer for exactly? Is layer-selected-hover-01 the correct token?
<img width="746" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/24463121/eaed5cde-cc6f-4a9a-9fe7-26d266aaaeb9">

**Comment by Kritvi-bhatia17** [comment]
Heyy @juanencalada 
In reply to [the above comment](https://github.com/carbon-design-system/carbon-design-kit/issues/744#issuecomment-1928693271), I've updated it!
