### ISSUE TITLE
[Button]: Extra large button spacing inconsistency in variants

### ISSUE THREAD

**Issue by kutiakos** [carbon-design-system/carbon-design-kit#755]
In the Carbon v11 Figma library the Extra Large buttons have inconsistent heights

Primary and Ghost button height: 64px
Secondary and Tertiary button height: 65x

<img width="1002" alt="Screenshot 2024-01-24 at 11 03 49" src="https://github.com/carbon-design-system/carbon-design-kit/assets/22256173/ecfe6ac6-54af-4b5a-a548-c1f014a13f29">

<img width="1030" alt="Screenshot 2024-01-24 at 11 02 44" src="https://github.com/carbon-design-system/carbon-design-kit/assets/22256173/4619b73f-ed5c-46b7-93b8-9e0e1f9595d0">

<img width="1015" alt="Screenshot 2024-01-24 at 11 03 03" src="https://github.com/carbon-design-system/carbon-design-kit/assets/22256173/8f720049-cb62-495e-8e54-10772deba5a8">

**Comment by laurenmrice** [comment]
Duplicate issue: [#816](https://github.com/carbon-design-system/carbon-design-kit/issues/816)
