### ISSUE TITLE
[Tile] title text overlapping selection icon

### ISSUE THREAD

**Issue by Kritvi-bhatia** [carbon-design-system/carbon-design-kit#756]
### Tiles
> - [x] Merge the tiles with and without the stroke into one
> - [x] Update the inconsistencies and bugs
> - [x] Remove the "margins" element and individually add margin to title, description & slot
> - [x] Fix padding of text so it does not run into the selection icon when a selectable tile is in the selected state ![image](https://github.com/carbon-design-system/carbon-design-kit/assets/148799271/b24c947d-3093-4265-b683-6dddf646ea1c)
> - [x] Make sure there is 16px padding between the end of the text and the icon.

---

### Review
> - [x] Review (carbon designer)
> - [x] Review (figma expert/Juan)

**Comment by laurenmrice** [comment]
Closing because this has be resolved.
