### ISSUE TITLE
[Callout] figma kit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#765]
## Acceptance criteria

Update the v11 All themes Figma kit with the new variant `Callout` for `Notification`.

- [x] Open a new branch in the [(v11) All themes Figma kit](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=58%3A2763&mode=design&t=7FwR6vcBu4JUGzOU-1) and add the Callout to the Notification component.
   - [x] Determine the best strategy to add this new variant. Should it be a new `Type` or should it be its own component because of the property mismatch. 
   - [x] Consult the option with @juanencalada (Figma review) and @alisonjoseph (code connect)
   - [x] Include properties for the high and low contrast styles 
- [x] Review with a Carbon designer.

**Comment by benjamin-kurien** [comment]
A new Callout variant has been added to the notifications component. Additionally, the component has been updated by nesting the inline, toast, and callout variants and introducing a new size property with long and short options. Irrelevant properties, including the type property, timestamp, and actionable, have been removed from specific variants.
