### ISSUE TITLE
[AI kit enhancements] Add AI variant of Tag

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-design-kit#778]

**Comment by RichKummer** [comment]
[Figma branch](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/ZzdL3EghmAsHEQS0usDX69/(v11)-All-themes---Carbon-Design-System?type=design&node-id=481%3A0&mode=design&t=yWpsUj1tWa6sDDxR-1)

**Notes:**
* Used inline AI slug per the specs
* Used boolean layer to display AI tag skeleton
