### ISSUE TITLE
Typo under the REAMME.md on the Code section -->Comoponents.

### ISSUE THREAD

**Issue by erickrenteria** [carbon-design-system/carbon-design-kit#78]
Typo under the README.md file under the Code section:
Comoponents should be Components. 

Please review screenshot: 
![Screen Shot 2019-03-13 at 10 03 00 AM](https://user-images.githubusercontent.com/31827002/54293808-a2246200-457e-11e9-9abd-c02b55eff7f2.png)

**Comment by aagonzales** [comment]
fixed with: https://github.com/carbon-design-system/carbon-design-kit/pull/73
