### ISSUE TITLE
MultiSelect (select all option): figma kit

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#789]
## Acceptance criteria
Update the v11 All themes Figma kit with the new enhancement for Multiselect (select all option).

- [x] Open a new branch in the [(v11) All themes Figma kit](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=58%3A2763&mode=design&t=7FwR6vcBu4JUGzOU-1) and add the Multiselect (select all option).
- [x] Review with a Carbon designer.
- [x] Review with Juan or Eugene.

**Comment by benjamin-kurien** [comment]
All required changes have been done. Branch is ready for merge. 
(Known issue https://github.com/carbon-design-system/carbon-design-kit/issues/826)
