### ISSUE TITLE
Data Table Title symbol isn't resizable

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-design-kit#79]
## Detailed description

The symbol for the **data table / table header / title** component isn't resizable which means it can't be used at different widths without detaching it from the symbol
![2019-03-13 10 55 07](https://user-images.githubusercontent.com/6569324/54294015-e879c100-457e-11e9-9d8b-9bd488fc45a3.gif)

> What version of the Carbon Design System Kit are you using?

Carbon V10 beta from Box, updated Tuesday March 12th, 2019

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

**data table / table header / title**

> What did you expect to happen? What happened instead? What would you like to see changed?

When the component is resized, the text fields should have a fixed width. 
![2019-03-13 10 59 04](https://user-images.githubusercontent.com/6569324/54294122-0e9f6100-457f-11e9-822c-d2ec0b7d72ff.gif)

## Steps to reproduce the issue

1. Insert the data table / header / title component into your sketch file
2. Adjust the horizontal width

## Additional information

Simply a matter of opening the component, selecting the two type fields, and setting them to fixed size - width:
![image](https://user-images.githubusercontent.com/6569324/54294214-3a224b80-457f-11e9-99fd-c8d17bd5da10.png)

## Add labels
I don't have rights to add labels

**Comment by werdnanoslen** [comment]
Still relevant, plz fix

**Comment by aagonzales** [comment]
Updated! It will be fixed with next kit push.
