### ISSUE TITLE
[Figma] list of component breaking changes to make ☂ 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#790]
## Acceptance criteria

This is a list of the top component breaking changes that we want to make in the (v12) All themes Figma kit.

```[tasklist]
### Components
- [ ] https://github.com/carbon-design-system/carbon-design-kit/issues/757
- [ ] Tag?
- [ ] Dropdown? maybe?
- [ ] Any other components?
```

**Comment by Kritvi-bhatia17** [comment]
Hi @laurenmrice, `if this issue is still active` should we add tiles, structured list under this?

**Comment by laurenmrice** [comment]
Closing for now.
