### ISSUE TITLE
[Structured list] Add feature flag

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#792]
## Acceptance criteria

- [x] Note: Start this issue once dev has a PR up for it.

----

- [x] Create Feature flag boolean for the feature flag change.
  - Naming convention for feature flag boolean: "[`name of enhancement`](`feature flag`)".
  - Consider adding an icon before the name for easier scanning of feature flags present in the properties panel. (For example like ⛳ or any other icon that would make sense.)
- [x] Add a feature flag section in the "Description" for the Structured list component.
- [x] Review
     - [x] Lauren
     - [x] Juan

**Comment by thyhmdo** [comment]
After this is done, we can tackle on this issue https://github.com/carbon-design-system/carbon-design-kit/issues/752
