### ISSUE TITLE
[Dropdown] Prototype mouseover acts crazy

### ISSUE THREAD

**Issue by gcate** [carbon-design-system/carbon-design-kit#797]
## Detailed description

I'm seeing a crazy animation when I mouse-over the dropdown options in figma prototype mode,
I see this if dropdown size is small.  
I asked on Carbon design slack channel and was told "this is a bug for all sizes, but different problems on Large and Medium sizes."

> What version of the Carbon Design System Kit are you using?
Figma V11 All themes:

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.
Dropdown - Default.

## Steps to reproduce the issue

1. Step one: in figma, add a Dropdown - Default from the  V11 All themes library
2. Step two: set Size to small, set Open to true. 
3. Step three: view in prototype mode, mouse over the droplist options

## Additional information

* Screenshot
![figma-dropdown-mouse-over](https://github.com/carbon-design-system/carbon-design-kit/assets/4819973/8c608bf4-a058-44dc-9d0c-a88a9b2a5dcb)
* Video
https://github.com/carbon-design-system/carbon-design-kit/assets/4819973/543f6e5c-495d-4ab1-9d68-20a08e70b078

* Notes

**Comment by laurenmrice** [comment]
Duplicate issue: https://github.com/carbon-design-system/carbon-design-kit/issues/797 so going to close
