### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by willowbrae** [carbon-design-system/carbon-design-kit#8]
Can you guys check the grid in the Sketch file please.
Its width - 1296 (not counting external gutters) can't produce 90px wide (12 columns) with 20px gutters in between them. Sketch struggles and puts some guides on half pixels (and some gutters are 19px), which makes snapping to grid hard. 

1300px will produce equally sized gutters. 
http://gridcalculator.dk/#/1300/12/20/0

**Comment by aagonzales** [comment]
We've been looking into this. The example grid shared didn't have the 5% margins. We realize this is a problem but its between doing the math exactly or fudging the math a little to get the pixels correct in Sketch.
