### ISSUE TITLE
[Dropdown] Fixing the open menu item bug

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#804]
- [x] Update the chat prompt to the local dropdown item.
>
> <img width="736" alt="Screenshot 2024-04-23 at 8 00 58 PM" src="https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/dcaac0bd-38ad-464b-897b-ba473074e8db">

---

- [x] Update the open child item from single select to multi-select in: 
>  - [x]  Dropdown - Filterable multi-select - Default
>  - [x]  Dropdown - Filterable multi-select - Fluid
>
> <img width="698" alt="Screenshot 2024-04-23 at 8 04 34 PM" src="https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/e6d4a99c-e739-4c61-81a8-ca0eb09d4465">

---

- [x] Added the tag in the selected Dropdown - Filterable multi-select - Fluid
>
> <img width="372" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/f2944533-d105-443c-b7ef-50b74a68311b">

---

- [x] Fix the variable state 

---

- [x] Review

**Comment by alina-jacob** [comment]
The width of the Inline dropdown menu item needs to be fixed, have already attempted fixing it [here](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/ddLlY8MAZO5wuJiZXbdD6v/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032%3A290630&mode=design&t=3Sco3RHdhxYz1XYi-1), you can use that or the [Multi-select's Inline component](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291515&mode=design&t=8LGHcBstlzBpUkQ4-4) as a refernece

![Frame 37992](https://github.com/carbon-design-system/carbon-design-kit/assets/159760598/28e7ee04-add6-496f-bebb-8991f6701737)
