### ISSUE TITLE
[Password input] Password input - Add the password visibility 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#807]
### Problem
Missing the password visibility toggle

--- 
### Reference
Storybook link example: https://react.carbondesignsystem.com/?path=/story/components-textinput--toggle-password-visibility

![image](https://github.com/carbon-design-system/carbon-design-kit/assets/77697351/045febce-aae9-4623-8257-cbcb4a1b3682)

---
### Tasks
- [x] Fluid styles
- [x] Add the "eye" icon + dot symbol when turning this prop on 

### Review
- [x] Carbon
- [x] Figma

**Comment by laurenmrice** [comment]
@thyhmdo We do have the default style under [Password input](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=3556%3A37675&mode=design&t=EjwLGmzJ20o8M9Uq-1) in Figma, but we don't have the fluid style. Juan may have more context as to why it was split into its own component page.
