### ISSUE TITLE
[Progress indicator]: Hidden nested components are missing component properties

### ISSUE THREAD

**Issue by Jonathan-Bruckbauer** [carbon-design-system/carbon-design-kit#814]
## Detailed description

> What version of the Carbon Design System Kit are you using?

Figma: (V11) All themes - Carbon Design System

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

Progress indicator

> What did you expect to happen? What happened instead? What would you like to see changed?

Hidden nested components are missing component properties.
Link to comment in Figma: https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg?type=design&node-id=1880-5977&mode=design#801041182

## Additional information
![Screen Recording 2024-05-14 at 10 55 17](https://github.com/carbon-design-system/carbon-design-kit/assets/115161875/d3380386-5852-42df-84b6-898f00c5ce3c)

---

**Tasks**
- [x] Fix in the v11 All Themes Figma file
- [x] Carbon review
- [x] Figma Review

**Comment by juanencalada** [comment]
Approved!
