### ISSUE TITLE
[CodeSnippet]: Disabled state missing

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-design-kit#821]
## Detailed description
No disabled state for all three CodeSnippet variants in Figma
https://react.carbondesignsystem.com/?path=/story/components-codesnippet--playground&args=disabled:!true;wrapText:!false
<img width="816" alt="Screenshot 2024-05-20 at 9 09 30 AM" src="https://github.com/carbon-design-system/carbon-design-kit/assets/2753488/3a6a9935-fd20-4b83-a2ae-7bfcea493295">

---

**Add disabled states for the following variants**
- [x] Inline
- [x] Single line
- [x] Multi line

**Review**
- [x] Carbon

**Comment by benjamin-kurien** [comment]
Figma kit updated: Disabled state added for inline, single line and multi line variants.
