### ISSUE TITLE
[Dropdown] Multi-select: Minor bugs related to the background color & label text

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#837]
## Detailed description

1. The background color for the multi-select dropdown when it's in focus state and the menu is open differs for the medium-sized dropdown. This color token needs to be changed to "field-01"
> <img width="990" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/df2a8d37-8104-4b0c-9012-c890246e0d3f">
>
> Solution: 
> `The background color is already set to field-01, but we need to remove the focus border background color (D9D9D9) as shown in the image.`

---

2. Prompt text and selected text can also be updated for filterable multi-select
> <img width="294" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/a2f8d4e7-0d8b-432c-a59f-060f7558c596">

---

Note: This might require a review of the placeholder values for all variants of dropdowns.

**Comment by benjamin-kurien** [comment]
Thanks @Kritvi-bhatia17 for opening this issue. 
1. The prompt text needs to be updated to "Choose options"
2. The bg color on the field needs to be updated to "field-01"

**Comment by Kritvi-bhatia17** [comment]
> Thanks @Kritvi-bhatia17 for opening this issue.
> 
> 1. The prompt text needs to be updated to "Choose options" - for both default and fluid variants
> 2. The bg color on the field needs to be updated to "field-01"

Hi @benjamin-kurien

2. For the second issue, the background color is already set to `field-01`, but we need to remove the focus border background color (D9D9D9) as shown in the image.
<img width="1496" alt="image" src="https://github.com/carbon-design-system/carbon-design-kit/assets/158570656/f2bdc850-4795-4b9d-a08b-6f88cfc1657d">
