### ISSUE TITLE
[Structured list] Need to remove the deprecated variant

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#838]
## Acceptance criteria

**Background**: Remove the deprecated Structured list: "Selectable structured list (Flush state)" because it is past the required date for keeping deprecation notices (1 month).

## Tasks
- [x] Change the name of the property from `"Alignment" as a variant -> "Flush" as a toggle property`.
   > - [x] Connected with Lauren for the confirmation
   > - [x] Confirmed with Juan whether this be a significant change for users, or is it acceptable to proceed with this update.
   >
   > ![image](https://github.com/user-attachments/assets/3a0a3a02-43c3-428f-bea3-642afbdc0714)

- [x] Remove the Flush states from:
   > - [x] Structured list - [Selectable](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=61653-7458&t=JaC9g8exVpPkhD2j-4)
   > - [x] Structured list - [header row item](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=61634-2136&t=JaC9g8exVpPkhD2j-4)

---

**Review**
- [x] Carbon designer
- [x] Figma expert

**Comment by juanencalada** [comment]
Hi @Kritvi-bhatia17 I just reviewed and merged the branch! Feel free to publish when you're ready!

cc @laurenmrice

**Comment by Kritvi-bhatia17** [comment]
Thank you so much @juanencalada ✨
Sure will do that!
