### ISSUE TITLE
[FluidSearch]: Skeleton state missing from Figma

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-design-kit#839]
## Acceptance criteria

There is no skeleton state for the fluid search in Figma.

<img width="247" alt="Screenshot 2024-06-17 at 3 31 27 PM" src="https://github.com/carbon-design-system/carbon-design-kit/assets/2753488/ee11ab94-0590-403c-a53e-984f2487c801">

---

**Tasks**
- [x] Add the skeleton state for the fluid search in Figma.

**Review**
- [x] Carbon designer

**Comment by benjamin-kurien** [comment]
Figma kit updated: Added a new variant “skeleton” under the property "state".
