### ISSUE TITLE
duplicate symbols in v10

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon-design-kit#84]
you can see two "2"s  symbols if you follow this path in Sketch

Carbon Design System -> Theme: gray 10 -> checkbox ->group ->

**Comment by willowbrae** [comment]
This has been fixed, thank you.

Seem like Theme Gray 90 has a similar issue - checkbox > group > "2" has three copies.

**Comment by aagonzales** [comment]
Updated! Fix will appear in next kit push.
