### ISSUE TITLE
[Dropdown] Fix inconsistent state transitions for all variants

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#842]
## Acceptance criteria

- After the auditing in issue [#818](https://github.com/carbon-design-system/carbon-design-kit/issues/818), fix the following interaction state transition bugs below that are occurring in Dropdown, Multiselect, and Combobox. 

- There is a [Figma branch](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/branch/cUdgsD2aNvNLEexPDoQzAc/(v11)-Carbon-Design-System?m=auto&node-id=14032-290630&t=PAnVV9BOgQgsuqag-1) created for this that you can use for this work.
-------

#### Selected state

- [x] Toggling on "Selected" transitions to the "Read-only selected state" instead of keeping it in the "Enabled selected state".
- [x] Toggling off "Selected" transitions to the "Read-only enabled state" rather than just returning to the "Enabled" state.

------------

#### Enabled state

- [x] Toggling on "Open" transitions to the "Focused selected", but closing it returns to "Focused (Collapsed)". It should just transition to the "Enabled open state" with focus on the field.

------------

#### Selected state

- [x] Toggling on "Open" and then toggling on “Selected”  the top field indicates that an option has been selected which is correct, but the option in the menu that is selected does not have a background color change or checkmark icon indicator.

------------

#### Error state
- [x] When you open the Combobox, it directly puts you into an error state. This should not be an error state and is causing confusion to our users. 

![error combobox](https://github.com/carbon-design-system/carbon-design-kit/assets/43969356/8eaaf84b-d17a-4c9d-85fd-de9b81c2c128)

-------

### Multi variants

- [x] Focus state options were missing in many variants ---> Reset and changed to the correct state while turning on the border

------------

**Comment by laurenmrice** [comment]
Blocked on starting this issue until combobox work is completed and implemented on the dev side, because it could affect the final specs of focus states ([#6102](https://github.com/carbon-design-system/carbon/issues/6102))

**Comment by sstrubberg** [comment]
Waiting for [Combobox work](https://github.com/carbon-design-system/carbon/issues/6102) to finish.
