### ISSUE TITLE
Duplicated buttons in v10

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#85]
Button is duplicated 4 times
Symbols > Theme: grey 10 > button > 01 primary > default text > 01 enabled

Button has 2 instances
Symbols > Theme: grey 10 > button > 01 primary > default text and icon > 01 enabled

Button is duplicated 3 times
Symbols > Theme: grey 10 > button > 01 primary > small text > 01 enabled

Button has 2 instances
Symbols > Theme: grey 10 > button > 01 primary > small text and icon > 01 enabled

Button has 2 instances
Symbols > Theme: grey 10 > button > 04 ghost > small text and icon > 01 enabled

**Comment by mariuszmickiewicz** [comment]
Button mentioned above are corrected now, thank you.

Seems like these in other themes also need a clean up:
Theme: gray 90 > button > 01 primary > default text > 01 enabled has three copies now
Theme: gray 100 > button > 01 primary > default text > 01 enabled has two copies
Theme: gray 100 > button > 01 primary > small text > 01 enabled has two copies

**Comment by laurenmrice** [comment]
fixed ! 🎉
- [x] Theme: gray 90 > button > 01 primary > default text > 01 enabled has three copies now
- [x] Theme: gray 100 > button > 01 primary > default text > 01 enabled has two copies
- [x] Theme: gray 100 > button > 01 primary > small text > 01 enabled has two copies
