### ISSUE TITLE
[MenuButton] Icon is not the right color in a few Button variants

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#855]
## Detailed description

The icon doesn't change color correctly in Button variants (Tertiary, Ghost, and Danger)

[Bug issue in Slack](https://ibm-studios.slack.com/archives/C0M053VPT/p1721326801513869?thread_ts=1721325374.418759&cid=C0M053VPT) 

## Two things may happen 

1. Check the Button variant. We may need to duplicate the Menu Button variants so that one icon's color does not override the other. 
2. Reset the menu button + Change the title + Change the icon

**Comment by Kritvi-bhatia17** [comment]
Hi Thy! Thanks for confirming as well, this issue is now fixed!
