### ISSUE TITLE
[Pagination] Update the height in Pagination + Data table

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-design-kit#857]
### Detailed description
In data table, the pagination height doesn't change accordingly. 

---

### Steps to reproduce the issue

1.  Go to the [Pagination](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=490-11) page, change the height from `Fixed `to `Hug` 
2. Go to the [Data table](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=24-0) page, and make sure that all paginations are updated in the Data table.

### Review
- [x] Carbon designer

**Comment by juanencalada** [comment]
@alina-jacob looks good! Great work! One thing I noticed is that the pagination bars have different Auto layout alignments:
These bound ones have top right:
<img width="1207" alt="image" src="https://github.com/user-attachments/assets/56911d90-6148-4fde-ba76-89a0886fcf41">

These unbound ones have center right:
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/63be6a7f-7d7f-4eee-8102-f06a929c275a">

I think these can be the same
