### ISSUE TITLE
Components not available in Figma 

### ISSUE THREAD

**Issue by SrikantNaidu1** [carbon-design-system/carbon-design-kit#858]
Hello,

We utilize Figma and the IBM Carbon Design System to create high-fidelity prototypes. We have noticed that many components displayed on the Carbon Design System website, Storybook v11.2 (https://ibm-products.carbondesignsystem.com/?path=/story/overview-welcome--overview&globals=viewport:basic), and React library are not available in the Figma design kits. 

Examples of components and pattens not available in Figma include:
- AI Tile groups = https://carbondesignsystem.com/components/tile/usage
- InterstitialScreen = https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-onboarding-interstitial-screen-interstitialscreen--docs
- Data spreadsheets = https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-data-spreadsheet-dataspreadsheet--docs
- Side panels = https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-side-panel-sidepanel--docs
- Other essential components

The absence of these components in the Figma design kit significantly hinders our ability to create accurate prototypes and maintain design consistency. Could you please let us know if there are plans to include these components in the Figma design kit? 

Additionally, any guidance on how we can design using these components in the meantime would be greatly appreciated.

We appreciate your attention and support.

**Comment by laurenmrice** [comment]
Hi @SrikantNaidu1 👋

The components that you have listed above are actually maintained in a different Figma library than ours by another team called "Carbon for IBM Products", which is a pattern asset library for specific components that products that are not in our core system. See their [Figma libraries](https://www.figma.com/files/902667414815738345/project/67151397/(v11)-Carbon-for-IBM-Products?fuid=834811722516621897). They have the same Figma library in different themes and are currently working on creating one Figma file with all themes, which is in Beta.

**Comment by Kritvi-bhatia17** [comment]
Hi @SrikantNaidu1! 

Just adding on to what Lauren mentioned, you can also reach out to their Slack channels for further help or doubts:
- For designer-related queries: [#ibmproducts-pal](https://ibm-studios.slack.com/archives/CQGR0HC05)
- For developer-related queries: [#ibmproducts-pal-dev](https://ibm-casdesign.slack.com/archives/C013ZTX0N6B)

**Comment by SrikantNaidu1** [comment]
Hi @laurenmrice and @Kritvi-bhatia17, 

Thank you both for your responses and for the helpful information regarding the components we mentioned. We appreciate your guidance.

@laurenmrice, the link you shared seems to direct us to our own library. Could you please provide the link to the Carbon for IBM Products library in Figma? We have not been able to find it. 

We appreciate your support!

**Comment by laurenmrice** [comment]
@SrikantNaidu1 

- That link directs me to this page with all of the available Carbon for IBM Product libraries, which is correct. Is this what you see? 

<img width="1532" alt="Screenshot 2024-08-06 at 2 53 57 PM" src="https://github.com/user-attachments/assets/60701229-28bf-4115-990a-86a304e7b06e">

- I will also link to their actual [Gray 10 theme file](https://www.figma.com/design/GqvE8KdjEfxyS6viCHpX6Q/(v11)-Gray-10---IBM-Products?m=auto&node-id=4395-242870&t=6lV55NQEHUTjxwsr-1) which is the theme used the most. Let me know if you can access that.

**Comment by SrikantNaidu1** [comment]
Hi @laurenmrice,

Thank you for providing the links. 

When I click on the link you provided, it takes me to a request access page instead of showing the libraries (screenshot attached). I requested access but have not heard back yet.
<img width="1533" alt="Screenshot 2024-08-06 at 10 13 08 PM" src="https://github.com/user-attachments/assets/92d40448-6699-4d40-b8fa-7e72637abcd7">


Could you please advise on the best way to gain access to the Gray 10 theme file or any other necessary steps I should take? Any additional guidance on how to proceed would be greatly appreciated.

Thank you again for your help!

**Comment by laurenmrice** [comment]
@SrikantNaidu1 Do you work at IBM?

**Comment by SrikantNaidu1** [comment]
Hey @laurenmrice,

I do not work at IBM. 

Is there a way for us to still access the Carbon for IBM Product libraries, especially the Figma libraries?

**Comment by laurenmrice** [comment]
@SrikantNaidu1 Oh okay, the Carbon for IBM Products Figma library is not publicly available and is only an internal library for IBMers. However you can still use the main Carbon Design System Figma library which is public and build off of it to create things you might need that are in Carbon for IBM Products.
