### ISSUE TITLE
Symbol resizing: Tags

### ISSUE THREAD

**Issue by mariuszmickiewicz** [carbon-design-system/carbon-design-kit#86]
Please switch text layer inside tag symbols to "fixed" to allow easier resizing which would keep exact right padding required (and removing guessing where the text layer ends).

**Comment by werdnanoslen** [comment]
Still relevant, plz fix

**Comment by aagonzales** [comment]
We should also probably add a "spacer" to help with the resizing as well.

**Comment by mariuszmickiewicz** [comment]
@aagonzales If text is changed to _Fixed_ and both left and right _pin to edge_ elements are selected then no spacer is needed. After typing new text simply resize symbol down until text breaks into two lines, then go up in width one pixel to get the perfect size.

**Comment by mariuszmickiewicz** [comment]
@aagonzales 
Gif is a bit slow after the conversion.

![carbontag](https://user-images.githubusercontent.com/12408951/57126725-3d230680-6d8e-11e9-9382-084f4d903896.gif)

**Comment by laurenmrice** [comment]
fixed 🎉
