### ISSUE TITLE
Figma type styles code-01/code-02 are using IBM Plex Sans

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-design-kit#860]
## Detailed description

The font styles `code-01` and `code-02` are using IBM Plex Sans instead of IBM Plex Mono.

> What version of the Carbon Design System Kit are you using?

(v11) All themes

> Is this issue related to a specific component? If so please give the page, artboard, and layer/symbol name.

- Non-variable/Utility styles/code-01
- Non-variable/Utility styles/code-02

**Tasks** 
- [x] Update Text style library to use mono instead of sans

## Additional information

<img width="939" alt="image" src="https://github.com/user-attachments/assets/aea6e241-237d-4168-b5ef-23de79399290">

<img width="501" alt="image" src="https://github.com/user-attachments/assets/ada986a0-de00-40aa-95e6-f9a4a4af06d5">

This affects the CodeSnippet component:

![image](https://github.com/user-attachments/assets/c85eab06-5dcf-4a61-8b90-8f6b80a66420)

**Comment by juanencalada** [comment]
Created a font family collection:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/ae2aad29-f553-40ad-9820-322d4f57b181">
and linked it to the code variables:
<img width="240" alt="image" src="https://github.com/user-attachments/assets/6529242d-3026-4cf4-9ea0-6778fe82da0f">

**Comment by laurenmrice** [comment]
This has been fixed in the `(v11) Text styles - Carbon Design System` library and updated and published in the `(v11) All themes - Carbon Design System library`.
