### ISSUE TITLE
[Dropdown]: Menu item bug on hover

### ISSUE THREAD

**Issue by benjamin-kurien** [carbon-design-system/carbon-design-kit#862]
## Detailed description
Dropdown menu item has a move in from left transition, on hover which appears to be unintentional
This issue occurs only on the "small" variant for the dropdown menu "size" property.

Carbon Design System Kit version: V11

https://github.com/user-attachments/assets/ffaf3a75-c5c7-4010-b3ce-d41968cdaf25

## Steps to reproduce the issue

1. Add a dropdown instance on a figma file
2. Change the the menu size property to small
3. View prototype
4. Hover on the menu item

## Additional information
The dropdown menu seems to have a "move in from left" transition added on hover. Removing this transition could solve the issue.

![dropdown menu bug](https://github.com/user-attachments/assets/91574846-8e2a-4962-b7d5-9c2bef16070f)

**Comment by alina-jacob** [comment]
Duplicate issue: https://github.com/carbon-design-system/carbon-design-kit/issues/797
