### ISSUE TITLE
[Icons]: icon artboard naming mistakes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-design-kit#873]
## Acceptance criteria
Looks like recently there were large overall changes to the layout of the Icon Figma library. With the layout change, there are now several naming mistakes throughout the library that need to be fixed.

- [x] Fix the naming mistakes. These naming mistakes are not happening on the icon assets themselves, but they occur on the icons card and folder it sits in.
- [x] Make the cards smaller on the page to make the icons easier to scan. I like the checkmark and last updated part, but we got a comment as well in Slack that this is difficult to scan through.
- [x] Remove the checkmark icon, as its redundant in this library. Keep the status of when it was last updated though.

**Comment by laurenmrice** [comment]
Thanks Juan! This has been fixed and merged.

**Comment by juanencalada** [comment]
My pleasure, @laurenmrice!
