### ISSUE TITLE
[Date Picker - Single]: Extra space in "Show label " property name

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-design-kit#875]
Super tiny low priority thing.

The "Show label" component property has a space at the end that is breaking code connect for some reason. 

These are the component properties for Date picker - Single date - Default, you can see the space here. 

```
Show label =true;
Show helper=false;
Label text="Label (mm/dd/yyyy)";
Helper text="month/day/year";
Error text="Error message goes here";
Warning text="Warning message goes here";
Date unselected="mm/dd/yyyy";
Date selected="12/25/2022";
```

**Comment by laurenmrice** [comment]
This should be fixed now. The extra space has been taken out after "Show label"
![Image](https://github.com/user-attachments/assets/f6fca0ab-562b-4c8c-8215-5bc7ef13346a)
