### ISSUE TITLE
[Bug] Fix 4px spacing in fluid Dropdown

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-design-kit#877]
## Detailed description
An unexpected 4px spacing is observed between the parent field and the menu list in the fluid dropdown component under the following states:
- State: Focus, Open: True, Selected: False ([link](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?node-id=14966-303189&t=jqA80IkKLUDkUnpp-4))
- State: Focus, Open: True, Selected: True ([link](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?node-id=63335-19878&t=jqA80IkKLUDkUnpp-4))

![Image](https://github.com/user-attachments/assets/2766aabd-d389-4d45-b730-cb52091077fe)

## Steps to reproduce the issue
1. Navigate to the fluid dropdown component in the specified states.
2. Observe the 4px spacing between the parent field and the menu list.

## Suggested fix
- [x] The issue can be resolved by moving the` _Dropdown menu list - Fluid input` layer under the `Dropdown menu overflow` layer.

- [x] Figma Review

 ![Image](https://github.com/user-attachments/assets/6824af8d-cc37-49c0-a6a3-14336a41accf)

**Comment by thyhmdo** [comment]
Updated:

Section updated: https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?node-id=14505-302528&t=aGt8O7HNTqJwpn4A-4

- Hid menus and had them toggled on with a boolean 
- Even when you toggle the menu on, the spacing issue shouldn't be there anymore
- Users will have to change the chevron and states manually
