### ISSUE TITLE
[Bug]: Vertical tab border

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-design-kit#878]
## Detailed description

> In the storybook, the vertical selected tab doesn't have border on the right side, while the Figma component still has it.

- [x] Selected vertical tab should not have border right—need to take out border-right in selected variant.

**Comment by thyhmdo** [comment]
Possible solution:
1. Lose the Fill and the Stroke on the high level (A)
2. Add a Spacing layer between the Vertical tab items. Add back the Fill and the Stroke. Set the width and height Fill (B)

![Image](https://github.com/user-attachments/assets/4adb683a-34bc-4a2e-b727-7a1c928ec9d4)

**Comment by thyhmdo** [comment]
Fixed this
