### ISSUE TITLE
Issue with "Loading - Small" symbol in Grey 10 theme

### ISSUE THREAD

**Issue by JordanWSmith15** [carbon-design-system/carbon-design-kit#90]
Carbon Design Kit, V10

Loading>Small symbol in Grey 10 theme is incomplete. Only displays a circle. Small loader on white theme is fine.
![Screen Shot 2019-04-14 at 10 24 22 AM](https://user-images.githubusercontent.com/21066152/56094202-91c61680-5e9f-11e9-8720-05dbfafd09f4.png)

**Comment by JordanWSmith15** [comment]
@laurenmrice @aagonzales

**Comment by laurenmrice** [comment]
@JordanWSmith15 this has been resolved in the newest sketch library updates 🎉
