### ISSUE TITLE
Small table toolbar missing button override

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon-design-kit#91]
In the latest Sketch Library ([from Cloud](https://sketch.cloud/s/JaVzz)), the `Theme: white / data table / table header / tool bar / small` symbol does not provide a primary button override, preventing me from having a simple two-icon toolbar without the primary action as intended.

![image](https://user-images.githubusercontent.com/764090/56607396-6f867400-65d6-11e9-9177-c6d9a9c38e53.png)

**Comment by werdnanoslen** [comment]
not stale, but I noticed an update:

Now there seems to be overrides for the text, icon, and spacer, but still no ability to remove the button itself:
![image](https://user-images.githubusercontent.com/764090/57802457-f89b5180-7723-11e9-8cef-be3471a07bf6.png)

**Comment by laurenmrice** [comment]
fixed 🎉!
