### ISSUE TITLE
Data Table Toolbar symbol isn't resizable

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon-design-kit#94]
In the latest Sketch Library (from Cloud), the `Theme: white / data table / table header / tool bar / small` symbol isn't resizable which means it can't be used at different widths without detaching it from the symbol.

![sample](https://user-images.githubusercontent.com/764090/56693612-e729d100-66b2-11e9-89bb-ec646c971d9f.gif)

When the component is resized, the row objects should have a fixed position from the right and not scale, like so:
![other sample](https://user-images.githubusercontent.com/6569324/54294122-0e9f6100-457f-11e9-822c-d2ec0b7d72ff.gif)

**Comment by laurenmrice** [comment]
fixed in all kits! 🎉
