### ISSUE TITLE
Text input w/helper text missing an Enabled symbol

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon-design-kit#97]
There is no `enabled` symbol for the `Theme: white / text input / 05 helper text` component. The only symbols available are `focus`, `active`, and `disabled`:

![image](https://user-images.githubusercontent.com/764090/56835361-ff7c2600-6841-11e9-8480-00d041c78974.png)

**Comment by laurenmrice** [comment]
Fixed in all kits 🎉. Also added some more states for helper text inputs. Also nested text area symbol within text input.
